### ISSUE TITLE
[Release Radar Request] Snippets for VSCode v2.1.0

### ISSUE THREAD

**Issue by tahabasri** [github/release-radar#10]
### Open Source Project name

Snippets for VSCode

### What is your project?

VSCode extension that lets you play with your code snippets without quitting your editor. Offers advanced UI panel with various options for snippets management.

### Version

2.1.0

### Date

November 02, 2021

### Description of changes

Latest version includes support for opening snippets via IntelliSense (`Ctrl+Space`) or by typing character '>' :

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/051-open-snippet-suggestion.gif" 
alt="Open Snippet using Suggestions">

Also, your snippets will be synced across all your devices using VSCode built-in feature **Settings Sync**.

### GitHub Repo

https://github.com/tahabasri/snippets

### Website

https://tahabasri.github.io/portfolio/

### Link to changelog

https://github.com/tahabasri/snippets/releases/tag/2.1.0

### Social media

https://www.linkedin.com/feed/update/urn:li:activity:6861441336596328448/

### Anything else to add?

Here is an overview of the top features you can do using the extension (full list [here](https://github.com/tahabasri/snippets/blob/main/README.md)) :

### Create Snippet

You can easily create a snippet from your open editor in VSCode.

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/01-new-snippet.gif" 
alt="Create Snippet">

You can add code snippet directly from outside VSCode via your clipboard.

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/02-new-snippet-clipboard.gif" 
alt="Create Snippet from Clipboard">

If you have a command in mind, just add it manually.

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/03-new-snippet-manual.gif" 
alt="Create Snippet Manually">

### Organize Snippets

You have the flexibility to reorder your snippets, there is no default order.

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/04-snippets-reorder.gif" 
alt="Reorder Snippets">

### Open Snippet

Add your snippet with a single click.

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/05-open-snippet-click.gif" 
alt="Open Snippet">

You're a keyboard guru ? Open your snippets using magic key `>` or using IntelliSense (`Ctrl+Space`).

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/051-open-snippet-suggestion.gif" 
alt="Open Snippet using Suggestions">

### Edit Snippet

Edit your snippet easily and benefit from support of VSCode built-in [Snippet Syntax](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax).

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/09-edit-snippet.gif" 
alt="Edit Snippet">

**Comment by tahabasri** [comment]
Submission is live ! You can check it out [here](https://github.com/github/release-radar/issues/10)

**Comment by mishmanners** [comment]
This was included in our November Release Radar 🎉 congrats
