### ISSUE TITLE
[Release Radar Request] Capri 4.0

### ISSUE THREAD

**Issue by fgnass** [github/release-radar#100]
### Open Source Project name

Capri

### What is your project?

Capri is a static site generator with partial hydration for React, Preact, SolidJS and Svelte.

### Version

4.0

### Date

June 25, 2022

### Description of breaking changes

Capri now supports Svelte! You can create interactive islands just by naming your components `*.island.svelte`.

### GitHub Repo

https://github.com/capri-js/capri

### Website

https://capri.build/

### Link to changelog

https://capri.build/docs/migration/

### Social media

https://twitter.com/fgnass/status/1540666350900740096

### Anything else to add?

Capri is still super young, the 1.0.0 release was only two weeks ago (https://twitter.com/fgnass/status/1536005613897011202). As we strictly stick to semver versioning, we already hit 4.0.0. We are now super happy with the public API and expect no further breaking changes for a while.

**Comment by mishmanners** [comment]
Congrats on being featured in the June Release Radar 🥳

- Read the blog [here](https://github.blog/2022-07-27-release-radar-jun-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1555011732053012480)
- Check out our [YouTube video](https://youtu.be/bnXGngNKbbw) for the June Release Radar promo 😄
