### ISSUE TITLE
[Release Radar Request] Jira CLI v1.0.0

### ISSUE THREAD

**Issue by ankitpokhrel** [github/release-radar#102]
### Open Source Project name

Jira CLI

### What is your project?

[JiraCLI](https://github.com/ankitpokhrel/jira-cli) is an interactive command line tool for [Atlassian Jira](https://www.atlassian.com/software/jira).

### Version

1.0.0

### Date

July 03, 2022

### Description of breaking changes

Breaking changes from the previous beta releases.

* Replace limit flag with paginate
* Append components on edit instead of overriding
* Append labels on edit instead of overriding
* Move `board` and `project` list to sub-command

### GitHub Repo

https://github.com/ankitpokhrel/jira-cli

### Website

https://github.com/ankitpokhrel/jira-cli

### Link to changelog

https://github.com/ankitpokhrel/jira-cli/releases/tag/v1.0.0

### Social media

https://twitter.com/ankitpokhrel/status/1543676990821105665

**Comment by mishmanners** [comment]
Congrats on being featured in the MONTHOF Release Radar 🥳

- Read the blog [here](https://github.blog/2022-08-05-release-radar-jul-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1557773344996458497)
- [Feel free to retweet Mish's tweet mentioning you](https://twitter.com/MishManners/status/1564440638556622848)
- Check out our [Release Radar YouTube video](https://youtu.be/pAD2ZYYBHKA) for the July Release Radar promo video 😄
