### ISSUE TITLE
[RR Request]: LocalStack v1.0

### ISSUE THREAD

**Issue by HarshCasper** [github/release-radar#103]
### Open Source Project name

LocalStack

### What is your project?

LocalStack is a cloud service emulator that runs in a single container on your laptop or in your CI environment. With LocalStack, you can run your AWS applications or Lambdas entirely on your local machine without connecting to a remote cloud provider! Whether you are testing complex CDK applications or Terraform configurations, or just beginning to learn about AWS services, LocalStack helps speed up and simplify your testing and development workflow.

### Version

v1.0.0

### Date

July 13, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/localstack/localstack

### Website

https://localstack.cloud/

### Link to changelog

https://localstack.cloud/blog/2022-07-13-announcing-localstack-v1-general-availability/

### Social media

https://twitter.com/_localstack/status/1552221468649394176

### Anything else to add?

Thanks for the initiative!

**Comment by mishmanners** [comment]
Congrats on being featured in the July Release Radar 🥳

- Read the blog [here](https://github.blog/2022-08-05-release-radar-jul-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1557773344996458497)
- [Feel free to retweet Mish's tweet mentioning you](https://twitter.com/MishManners/status/1564440638556622848)
- Check out our [Release Radar YouTube video](https://youtu.be/pAD2ZYYBHKA) for the July Release Radar promo video 😄
