### ISSUE TITLE
[Release Radar Request] <Wikipedia Scraper> 1.0

### ISSUE THREAD

**Issue by Jai-Verma-04** [github/release-radar#104]
### Open Source Project name

Wikipedia Scraper

### What is your project?

The project is very handy for students  (or anyone looking for information) to get their desired Wikipedia Article onto their desktop in seconds.
All the student would need is to enter the title of the article they want.

### Version

1.0

### Date

16 July 2022

### Description of breaking changes

This is the first version for the Wikipedia Scraper.

### GitHub Repo

https://github.com/Jai-Verma-04/WikiPedia-Scraper

### Website

None

### Link to changelog

https://github.com/Jai-Verma-04/WikiPedia-Scraper/releases/tag/v1.0

### Social media

https://www.instagram.com/p/CWxXO6BjdgON9UteK1rcitrDL7svGWSUjwYNmY0/

**Comment by mishmanners** [comment]
Congrats on being featured in the MONTHOF Release Radar 🥳

- Read the blog [here](https://github.blog/2022-08-05-release-radar-jul-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1557773344996458497)
- [Feel free to retweet Mish's tweet mentioning you](https://twitter.com/MishManners/status/1564440638556622848)
- Check out our [Release Radar YouTube video](https://youtu.be/pAD2ZYYBHKA) for the July Release Radar promo video 😄

**Comment by Jai-Verma-04** [comment]
Very thankful for the same Mam, and I hope you are doing fine.

I would like to inquire that I am not able to see my project on the blog,
although mentioned that i have been featured in the July released radar.

Regards
Jai Verma
Twitter: @Jai_Verma-_04
