### ISSUE TITLE
[RR Request]: VSLook

### ISSUE THREAD

**Issue by sudoaugustin** [github/release-radar#105]
### Open Source Project name

VSLook

### What is your project?

A vscode theme that can be customized, and cloned from other themes. Exporting theme is also available.

![What vslook does](https://raw.githubusercontent.com/sudoaugustin/vslook/main/.github/media/overview.gif)

### Version

0.3

### Date

July 13 2022

### Description of breaking changes

I have included exporting theme and clone styles from other themes in this release.

### GitHub Repo

https://github.com/sudoaugustin/vslook

### Website

https://github.com/sudoaugustin/vslook#readme

### Link to changelog

https://github.com/sudoaugustin/vslook/blob/main/CHANGELOG.md

### Social media

https://twitter.com/sudoaugustin/status/1538276113491054592

### Anything else to add?

The version may be v0.3 but it's very stable. Already shipped to [marketplace](https://marketplace.visualstudio.com/items?itemName=sudoaugustin.vslook).

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
