### ISSUE TITLE
[Release Radar Request] Infracost VSCode Extension

### ISSUE THREAD

**Issue by alikhajeh1** [github/release-radar#107]
### Open Source Project name

Infracost VSCode Extension

### What is your project?

Infracost's VSCode extension shows you cost estimates for Terraform right in your editor! Prevent costly infrastructure changes before they get into production.

### Version

v0.1.16

### Date

July 18, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/infracost/vscode-infracost/

### Website

https://www.infracost.io/

### Link to changelog

https://github.com/infracost/vscode-infracost/releases/

### Social media

https://twitter.com/hugo_rut/status/1542168246232793089

### Anything else to add?

I posted this on reddit and it caused the repo to start trending on github, [here's the](https://www.reddit.com/r/devops/comments/vs5tj5/vscode_extension_to_see_cost_estimates_for/) post I made.

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄

**Comment by alikhajeh1** [comment]
@mishmanners awesome - thanks! Will do :)
