### ISSUE TITLE
[Release Radar Request] ZITADEL Version 2.0

### ISSUE THREAD

**Issue by hifabienne** [github/release-radar#108]
### Open Source Project name

ZITADEL

### What is your project?

ZITADEL provides everything you need to manage users in your project. Roles, single sign-on, a secure login with support for passkeys are there for you to use. ZITADEL is built on proven Standards like OpenID Connect, OAuth, FIDO2 and more to  allow integration into your apps in minutes. It combines the best of two worlds - the quick setup of Auth0 in the cloud and is open source (and self-hostable) like Keycloak.

### Version

2.0

### Date

July 29, 2022

### Description of breaking changes

The new version of ZITADEL allows you to have multiple instances in parallel, think of virtual instances sharing the same underlying process and infrastructure. The possibility to configure multiple custom domains and settings like message providers (SMTP, SMS, etc) and token lifetimes are newly added. Also the developer experience got massively improved with the ultimate goal to get your own instance up and running within 5 minutes.

### GitHub Repo

github.com/zitadel/zitadel

### Website

zitadel.com

### Link to changelog

https://github.com/zitadel/zitadel/releases/tag/v2.0.0

### Social media

https://twitter.com/zitadel/status/1553020042782167040?s=20&t=YWir4oClS3Fh806VMG4qIQ

**Comment by hifabienne** [comment]
Hi @mishmanners 
Did I miss out for the release radar of July?

**Comment by mishmanners** [comment]
Yeah sorry @hifabienne we already shipped the July Release Radar. Please definitely submit again for version 3.0 and we'd love to consider your project 😄
