### ISSUE TITLE
[RR Request]: svgps.app v1.0.0

### ISSUE THREAD

**Issue by aykutkardas** [github/release-radar#109]
### Open Source Project name

svgps.app

### What is your project?

SVGPS converts your icons into a single JSON file that is ready to use in your frontend or mobile projects.

### Version

1.0

### Date

August 1, 2022

### Description of breaking changes

0

### GitHub Repo

https://github.com/aykutkardas/svgps.app

### Website

https://svgps.app

### Link to changelog

https://github.com/aykutkardas/svgps.app/releases/tag/v1.0.0

### Social media

https://twitter.com/gizemnkorkmaz/status/1553972308020285440

**Comment by mishmanners** [comment]
Congrats on being featured in the MONTHOF Release Radar 🥳

- Read the blog [here](https://github.blog/2022-08-05-release-radar-jul-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1557773344996458497)
- [Feel free to retweet Mish's tweet mentioning you](https://twitter.com/MishManners/status/1564440638556622848)
- Check out our [Release Radar YouTube video](https://youtu.be/pAD2ZYYBHKA) for the July Release Radar promo video 😄

**Comment by mishmanners** [comment]
Congrats on being featured in the July Release Radar 🥳

- Read the blog [here](https://github.blog/2022-08-05-release-radar-jul-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1557773344996458497)
- [Feel free to retweet Mish's tweet mentioning you](https://twitter.com/MishManners/status/1564440638556622848)
- Check out our [Release Radar YouTube video](https://youtu.be/pAD2ZYYBHKA) for the July Release Radar promo video 😄
