### ISSUE TITLE
[Release Radar Request] <Crypto Profit App>

### ISSUE THREAD

**Issue by fcancelinha** [github/release-radar#11]
### Open Source Project name

Crypto Profit

### What is your project?

A crypto profit/loss calculator with FIAT conversion and 

### Version

2.0.0

### Date

November 29 2021

### Description of changes

Improved UI
Currency Marquee
Dark Mode improved

### GitHub Repo

https://github.com/fcancelinha/crypto-profit

### Website

https://fcancelinha.github.io/crypto-profit/

### Link to changelog

https://github.com/fcancelinha/crypto-profit/releases

### Social media

no

### Anything else to add?

You're an amazing company and website\service ! Keep rocking!

**Comment by mishmanners** [comment]
Sorry we couldn't include this in the November Release Radar as that had already shipped. Please definitely submit again for v2.0 and we'd love to consider your project 😄
