### ISSUE TITLE
[Release Radar Request] Planby - Schedule / Timeline / Electronic Program Guide for React

### ISSUE THREAD

**Issue by karolkozer** [github/release-radar#110]
### Open Source Project name

Planby

### What is your project?

Planby is a component for a quick implementation of EPG, schedules, music events, timelines, and many more ideas. It uses a custom virtual view which allows you to operate on a really big amount of data. The component has a simple API that you can easily integrate with other third-party UI libraries. The component theme is customized to the needs of the application design.

### Version

0.4.0

### Date

29.07.2022

### Below is a list of new functionalities:

- custom time ranges

- hour format 24h or 12h (AM / PM)

- custom width of a hour, e.g. 300px, etc.

- custom sidebar's width

- custom event's height

- RTL support

- custom UI of an event, sidebar and timeline. (Material UI, Chakra UI, Antd etc.)

### GitHub Repo

https://github.com/karolkozer/planby

### Website

https://planby.netlify.app/

### Link to changelog

https://worldofreact.hashnode.dev/electronic-program-guide-react-planby

### Social media

https://twitter.com/reactnewsletter/status/1527020955024900099

### Anything else to add?

Website with description and examples:
https://planby.netlify.app/
https://github.com/karolkozer/planby

Newsletters:
React Newsletter / [ui.dev](http://ui.dev/) / [bytes.dev](http://bytes.dev/): https://lnkd.in/eW42VpBD
CSSWeekly: https://tinyurl.com/css-weekly-planby-newsletter

Articles:
hashnode: https://tinyurl.com/2p8b39ra
medium / DigitalHero / linkedin : https://tinyurl.com/medium-article-planby
hackernoon: https://tinyurl.com/36xnesz3
devto: https://tinyurl.com/4fzwppyu
justjoinit (interview): https://tinyurl.com/mu8zybx7

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
