### ISSUE TITLE
[Release Radar Request] gh-dash

### ISSUE THREAD

**Issue by dlvhdr** [github/release-radar#111]
### Open Source Project name

gh-dash

### What is your project?

A GitHub (gh) CLI extension to display a dashboard with pull requests and issues by filters you care about.

### Version

3.0

### Date

April 1, 2022

### Description of breaking changes

Issues support, keybindings support, themes support and ad-hoc search support

### GitHub Repo

https://github.com/dlvhdr/gh-dash

### Website

https://github.com/dlvhdr/gh-dash

### Link to changelog

https://github.com/dlvhdr/gh-dash/releases/tag/v3.0.0

### Social media

https://twitter.com/dlvhdr/status/1509946564013346816?s=21&t=V-tuFxKYbuWlj93lnWjx6w

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the April Release Radar, as that had already shipped. Please definitely submit again for version 2.0 and we'd love to consider your project 😄
