### ISSUE TITLE
[Release Radar Request] Simple Data Analysis  v1.0.0

### ISSUE THREAD

**Issue by nshiab** [github/release-radar#114]
### Open Source Project name

Simple Data Analysis

### What is your project?

Simple Data Analysis is an easy-to-use JavaScript library for most common data analysis tasks. The goal is that data journalists who are not programming experts and web developers who are not data specialists can learn it quickly.

### Version

1.0

### Date

August 9, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/nshiab/simple-data-analysis.js

### Website

https://github.com/nshiab/simple-data-analysis.js

### Link to changelog

https://observablehq.com/@nshiab/simple-data-analysis?collection=@nshiab/simple-data-analysis-in-javascript

### Social media

https://twitter.com/NaelShiab/status/1557084533945663488

### Anything else to add?

Thank you! :)

**Comment by mishmanners** [comment]
Congrats on being featured in the August 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-09-02-release-radar-aug-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1570095096258863104)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1566419465725562880)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a August Release Radar promo video 😄
