### ISSUE TITLE
[RR Request]: Amplication v1.0.0

### ISSUE THREAD

**Issue by MichaelSolati** [github/release-radar#115]
### Open Source Project name

Amplication

### What is your project?

Amplication is a flexible open-source Node.js app development tool. It helps you build production-ready Node.js applications without wasting time on repetitive coding.

### Version

1.0

### Date

September 20, 2022

### Description of breaking changes

Install plugins to add new capabilities and more to your Amplication-generated code. Continuously sync your code between GitHub and Amplication, so your code is always up to date. Each component or service in your application can be synced to a different location on your git organization; break silos and monoliths with ease without the overhead of maintenance that comes with it.

### GitHub Repo

https://github.com/amplication/amplication

### Website

https://amplication.com/

### Link to changelog

https://github.com/amplication/amplication/releases/tag/v1.0.0

### Social media

https://twitter.com/amplication/status/1572119139413622784?s=20&t=TVe-63kCcazjSyIsPCU70A

**Comment by mishmanners** [comment]
Okay thanks, we'll look at this when it gets closer to October. Please update this issue when you have released 1.0

**Comment by MichaelSolati** [comment]
@mishmanners we've launched, so I've updated the issue with the relevant links. Please let me know if there's anything else you need from me. 😁

**Comment by souravjain540** [comment]
excited to see amplication in next edition :)

**Comment by mishmanners** [comment]
We had a delay, but you're in. Also good luck for Hacktoberfest. I see Amplication is doing a LOT of things for it!

**Comment by souravjain540** [comment]
@mishmanners that's good to hear. thanks for the post on Twitter as well.

will love to collaborate in future as well :)

**Comment by MichaelSolati** [comment]
@mishmanners I saw the post and we're so happy to be featured, though I think I saw a typo...

In the first sentence you wrote 

> Node.js is another popular framework and Amplication is here to help.

I'm assuming you meant NestJS, though if you meant Node, it's weird to see it referred to as a framework and not a language.

If I'm wrong let me know, I just wanted to raise it as a potential mistake.

**Comment by mishmanners** [comment]
Congrats on being featured in the September 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-10-28-release-radar-sept-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1586410284784156672)
