### ISSUE TITLE
X4JS typescript framework

### ISSUE THREAD

**Issue by eco747** [github/release-radar#116]
### Open Source Project name

x4js

### What is your project?

X4 is a full typescript framework to develop Web or Desktop applications. Included more than 50 controls like grids, charts, etc. Everything needed to push the limits of your creativity. If these components are not enough, you can create your in few lines.

### Version

1.4.43

### Date

2022-08-01

### Description of breaking changes

nil

### GitHub Repo

https://github.com/rlibre/x4js

### Website

https://x4js.org

### Link to changelog

https://x4js.org

### Social media

nil

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 2.0 and we'd love to consider your project for feature 😄
