### ISSUE TITLE
[RR Request]: JSON Crack v2.0.0

### ISSUE THREAD

**Issue by AykutSarac** [github/release-radar#118]
### Open Source Project name

JSON Crack

### What is your project?

JSON Crack (previously JSON Visio) is a visualization tool for JSON data, making developers lives easier to view and even for non-developers to understand data. Either type directly into the editor or import/fetch json from locally or URL!

### Version

2.0

### Date

August 27, 2022

### Description of breaking changes

**Since the v1 to v2, JSON Crack received following features:**

- Fetch JSON
- Download File
- Share Link
- Settings
- Copy/Download Graph
- Search Nodes
- Light Theme
- Fullscreen View
- VS Code's Monaco Editor
- Expand/Collapse Nodes
- JSON Validator

### GitHub Repo

https://github.com/AykutSarac/jsonvisio.com

### Website

https://jsoncrack.com/

### Link to changelog

https://github.com/AykutSarac/jsonvisio.com/releases/tag/v2.0.0

### Social media

https://twitter.com/aykutsarach/status/1563573958984667137

### Anything else to add?

JSON Crack was known as JSON Visio previously and shared on GitHub's twitter https://twitter.com/github/status/1519363257794015233

**Comment by mishmanners** [comment]
Congrats on being featured in the August 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-09-02-release-radar-aug-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1570095096258863104)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1566419465725562880)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a August Release Radar promo video 😄
