### ISSUE TITLE
[Release Radar Request] Spaceship Prompt v4.0

### ISSUE THREAD

**Issue by denysdovhan** [github/release-radar#119]
### Open Source Project name

Spaceship Prompt

### What is your project?

Spaceship is a modular, customizable Zsh prompt. One of the most popular terminal prompt out there. It shows the context of the current environment, like versions of the compiler, runtimes, repository statuses, background jobs, etc

### Version

4.x

### Date

September 1, 2022

### Description of breaking changes

* **Asynchronous rendering.** Most of the computation happens in a separate process, so a user can type the next command right away, without waiting for complex checks to be performed.
* **Registry for sections.** Users now have a better API for creating custom sections and can explore and submit them to the registry on our website.
* **Configuration file.** Spaceship configuration now can be placed in a single file `~/.spaceshiprc.zsh` or `~/.config/spaceship.zsh` and it will be automatically loaded.
* **Command Line Interface.** CLI will help to perform common tasks easiear, like editing configuration, adding and removing sections, etc.

There are more features described in our blog announcement: https://spaceship-prompt.sh/blog/2022-spaceship-v4

### GitHub Repo

https://github.com/spaceship-prompt/spaceship-prompt

### Website

https://spaceship-prompt.sh/

### Link to changelog

https://spaceship-prompt.sh/blog/2022-spaceship-v4

### Social media

https://twitter.com/SpaceshipPrompt/status/1566742940759650305

### Anything else to add?

This release is mostly made during the wartime. I was working on this release mostly to get my mind off the reality. This release is partly made when I was sitting in a shelter.

**Comment by mishmanners** [comment]
Congrats on being featured in the September 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-10-28-release-radar-sept-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1586410284784156672)
