### ISSUE TITLE
[Release Radar Request] Chips-n-Salsa

### ISSUE THREAD

**Issue by cicirello** [github/release-radar#120]
### Open Source Project name

Chips-n-Salsa

### What is your project?

Chips-n-Salsa is a Java library of customizable, hybridizable, iterative, parallel, stochastic, and self-adaptive local search algorithms. The library includes genetic algorithms as well as evolutionary algorithms more generally, as well as stochastic local search algorithms, such as simulated annealing, hill climbers, as well as constructive search algorithms such as stochastic sampling. 

### Version

6.0.0

### Date

September 2, 2022

### Description of breaking changes

The latest release includes additional support for evolving solutions to problems whose solutions are represented with permutations. In particular, this release adds a wide variety of crossover operators for permutations. This release also cleans up other parts of the library such as removing previously deprecated classes.

### GitHub Repo

https://github.com/cicirello/Chips-n-Salsa

### Website

https://chips-n-salsa.cicirello.org/

### Link to changelog

https://github.com/cicirello/Chips-n-Salsa/blob/master/CHANGELOG.md

### Social media

Didn't post to social media

**Comment by mishmanners** [comment]
Congrats on being featured in the September 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-10-28-release-radar-sept-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1586410284784156672)

**Comment by cicirello** [comment]
@mishmanners thanks!
