### ISSUE TITLE
[Release Radar Request] Contribute to open source: the right way 3rd edition

### ISSUE THREAD

**Issue by Mte90** [github/release-radar#121]
### Open Source Project name

Contribute to open source: the right way

### What is your project?

A free and open source book based on my personal experience in the last 12 years in various communities from Mozilla to WordPress in for national and international roles as develop/localizer/community manager/support/evangelist and my others condensed in 134 pages.

A simple way to help newcomers on contributing to open source to skilled one that want to learn from other experiences with a lot of external resources.

### Version

3rd edition

### Date

September 02, 2022

### Description of breaking changes

New sections about Burnout, fundings and why giving money to open source is not enough.

### GitHub Repo

https://github.com/Mte90/Contribute-to-opensource-the-right-way/

### Website

https://daniele.tech

### Link to changelog

https://github.com/Mte90/Contribute-to-opensource-the-right-way/releases/tag/2022.1

### Social media

https://twitter.com/Mte90Net/status/1565640758681542658

### Anything else to add?

It is the 3rd edition in 4 years and it is a working in progress based on reader feedback

**Comment by mishmanners** [comment]
Congrats on being featured in the September 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-10-28-release-radar-sept-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1586410284784156672)

**Comment by Mte90** [comment]
Thanks but it is sad to discover it after a month...
