### ISSUE TITLE
[Release Radar Request] Pew pew needless GitHub repos!

### ISSUE THREAD

**Issue by adrianmg** [github/release-radar#123]
### Open Source Project name

github-pewpew

### What is your project?

Have you ever had too much fun with the GitHub API and ended up creating too many dummy repos? Me too 😅! I made this little CLI tool to clean up repositories quickly.

### Version

1.2.2

### Date

April 2022

### Description of breaking changes

No breaking changes!

### GitHub Repo

http://github.com/adrianmg/github-pewpew

### Website

https://adrianmato.com/pewpew

### Link to changelog

https://github.com/adrianmg/github-pewpew/releases/tag/v1.2.2

### Social media

https://twitter.com/adrianmg/status/1510855137115328515

### Anything else to add?

Here's the npm link! https://www.npmjs.com/package/github-pewpew

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 2.0 and we'd love to consider your project for feature 😄 We also already posted the April Release Radar back in May this year.
