### ISSUE TITLE
[RR Request]: RxDB 13.0.0

### ISSUE THREAD

**Issue by pubkey** [github/release-radar#124]
### Open Source Project name

RxDB

### What is your project?

RxDB (short for <b>R</b>eactive <b>D</b>ata<b>b</b>ase) is an <a href="https://rxdb.info/offline-first.html">offline-first</a>, NoSQL-database for JavaScript Applications like Websites, hybrid Apps, Electron-Apps, Progressive Web Apps and Node.js.
  Reactive means that you can not only query the current state, but <b>subscribe</b> to all state changes like the result of a query or even a single field of a document.
  This is great for UI-based <b>realtime</b> applications in a way that makes it easy to develop and also has great performance benefits but can also be used to create fast backends in Node.js.<br />
  RxDB provides an easy to implement <a href="https://rxdb.info/replication.html">protocol</a> for realtime <b>replication</b> with your existing infrastructure or any compliant CouchDB endpoint.<br />
  RxDB is based on a storage interface that enables you to swap out the underlaying storage engine. This increases <b>code reuse</b> because you can use the same database code for different JavaScript environments by just switching out the storage settings.

### Version

13.0.0

### Date

September 15, 2022

### Description of breaking changes

- A new, faster and easier replication protocol. https://rxdb.info/replication.html
- A FoundationDB RxStorage implementation https://rxdb.info/rx-storage-foundationdb.html
- A websocket replication plugin https://rxdb.info/replication-websocket.html
- Many other improvements and performance optimizations.

### GitHub Repo

https://github.com/pubkey/rxdb

### Website

https://rxdb.info/

### Link to changelog

https://github.com/pubkey/rxdb/blob/master/CHANGELOG.md

### Social media

https://twitter.com/rxdbjs/status/1570371958201798657

### Anything else to add?

Link to the release notes for 13.0.0 https://rxdb.info/releases/13.0.0.html

**Comment by mishmanners** [comment]
Congrats on being featured in the September 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-10-28-release-radar-sept-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1586410284784156672)

**Comment by mishmanners** [comment]
My pleasure @pubkey. Apologises for being slack on notifying you on this. Looking forward to seeing what's next!
