### ISSUE TITLE
[Release Radar Request] Xcodes

### ISSUE THREAD

**Issue by MattKiazyk** [github/release-radar#125]
### Open Source Project name

Xcodes CLI

### What is your project?

Xcodes is a simple command line interface to download multiple versions of Xcode quickly and pain free. Using aria2 to download 3-5x faster then regular downloads. 

### Version

1.0

### Date

September 18, 2022

### Description of breaking changes

New for v1.0 is the removal of using your Apple ID and password in order to download Xcode - no longer having to type in your 2FA code again. 

### GitHub Repo

https://github.com/RobotsAndPencils/xcodes

### Website

https://www.xcodes.app

### Link to changelog

https://github.com/RobotsAndPencils/xcodes/releases/tag/1.0.0

### Social media

https://twitter.com/xcodesapp/status/1571706560287481860?s=20&t=7mDtt8Un8lfyz4YiiemcBA

### Anything else to add?

This release is a long time in the making for not requiring a username/password to download Xcode from Apple!

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the September 2022 Release Radar and we couldn't include them all. Please submit your project again for consideration when you have version 2.0 released.
