### ISSUE TITLE
[RR Request]: lazytrivy v1.0.0

### ISSUE THREAD

**Issue by owenrumney** [github/release-radar#126]
### Open Source Project name

Lazytrivy

### What is your project?

lazytrivy is a wrapper for [Trivy (the vulnerability and misconfiguration scanner)](https://github.com/aquasecurity/trivy) that allows you to run Trivy without remembering the command arguments.

lazytrivy will run Trivy in a docker container and display the results in a terminal UI, the intention is that this will make it more stable across all platforms.

![scan_all](https://user-images.githubusercontent.com/3049157/191484662-83286a7c-9240-4594-b9f4-16d7ad58930f.png)

### Version

v1.0.0

### Date

21st September 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/owenrumney/lazytrivy

### Website

https://github.com/owenrumney/lazytrivy

### Link to changelog

https://www.owenrumney.co.uk/lazy-trivy-introduction/

### Social media

https://twitter.com/owenrum/status/1572536592270491649

**Comment by mishmanners** [comment]
Congrats on being featured in the September 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-10-28-release-radar-sept-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1586410284784156672)
