### ISSUE TITLE
[Release Radar Request] Wails v2 Released

### ISSUE THREAD

**Issue by leaanthony** [github/release-radar#127]
### Open Source Project name

Wails

### What is your project?

Wails is a project that enables you to write desktop applications using Go and web technologies. It is a lightweight and fast Electron alternative for Go and is currently used in both Open Source and commercial applications. 

### Version

2.0.0

### Date

September 22, 2022

### Description of breaking changes

Native application menu & dialogs, rich runtime API including window manipulation and obfuscation support via Garble.
Windows builds now support Microsoft's WebView2 with no need to redistribute any DLLs, no CGO means no external mingw compiler required, NSIS installer generation and full native theming support including Mica & Acrylic effects. Apple M1 support has been added

### GitHub Repo

https://github.com/wailsapp/wails

### Website

https://wails.io

### Link to changelog

https://wails.io/changelog

### Social media

https://www.reddit.com/r/golang/comments/xknc4p/announcement_wails_v2_released/

**Comment by mishmanners** [comment]
Congrats on being featured in the September 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-10-28-release-radar-sept-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1586410284784156672)
