### ISSUE TITLE
[Release Radar Request] GitStory 1.0

### ISSUE THREAD

**Issue by swve** [github/release-radar#128]
### Open Source Project name

GitStory

### What is your project?

GitStory is a Wayback Time machine app for GitHub projects, powered by the GitHub API.
📆 Use the Reactive calendar to go back in time.
🌴 Check commits by day, month and year.
🔎 Scan for commits activity of a given month by clicking on the month button in the calendar.
📸 Explore "snapshots" of GitHub repositories by navigating to the exact commit.
🌍 Explore and see the beginnings of popular Open source projects.

### Version

1.0

### Date

28 September 2022

### Description of breaking changes

This is the first release

### GitHub Repo

https://github.com/swve/gitstory

### Website

https://gitstory.app/

### Link to changelog

https://github.com/swve/gitstory/releases/tag/v1.0

### Social media

https://twitter.com/swveio/status/1575221271310499840

**Comment by mishmanners** [comment]
Congrats on being featured in the September 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-10-28-release-radar-sept-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1586410284784156672)
