### ISSUE TITLE
[RR Request]: <Name and version of your open source project>

### ISSUE THREAD

**Issue by adrianmg** [github/release-radar#129]
### Open Source Project name

github-pewpew

### What is your project?

Have you ever had too much fun with the GitHub API and ended up creating too many dummy repos? Me too 😅! I made this little CLI tool to clean up repositories and codespaces quickly.

### Version

1.3.1

### Date

October 01, 2022

## ✨ Major Release with Codespaces!
- Added `ghpew codespaces` command to delete codespaces #37
- Added `ghpew help` as the default command
- Added `ghpew repos` command to delete repos
- Added instructions to press `space` to select choices
- Fixed configuration directory issues #38
- Improved configuration directory for Unix users
- Migrated dependencies from CommonJS to ES modules
- Updated dependencies #40 #41 #42
- Full changelog https://github.com/adrianmg/github-pewpew/compare/v1.2.2...v1.3.1

### GitHub Repo

https://github.com/adrianmg/github-pewpew

### Website

https://adrianmato.com/pewpew

### Link to changelog

https://github.com/adrianmg/github-pewpew/releases/tag/v1.3.1

### Social media

https://twitter.com/adrianmg/status/1576446811669078016

### Anything else to add?

I was [told](https://github.com/github/release-radar/issues/123) not to submit minor changes, I hope this major release adding support for Codespaces can make the cut 😄

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the October Release Radar and we couldn't include them all. Please submit your project again for consideration when you have version 2.0 released.
