### ISSUE TITLE
[RR Request]: Constellation v2.0.0

### ISSUE THREAD

**Issue by datosh** [github/release-radar#130]
### Open Source Project name

Constellation

### What is your project?

Constellation is a Kubernetes engine that aims to provide the best possible data security. It wraps your K8s cluster into a single confidential context that is shielded from the underlying cloud infrastructure. Everything inside is always encrypted, including at runtime in memory. For this, Constellation leverages confidential computing (see the [whitepaper](https://content.edgeless.systems/hubfs/Confidential%20Computing%20Whitepaper.pdf)) and more specifically Confidential VMs.

### Version

2.0.0

### Date

September 12, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/edgelesssys/constellation

### Website

https://constellation-docs.edgeless.systems/

### Link to changelog

https://blog.edgeless.systems/hi-open-source-community-confidential-kubernetes-is-now-on-github-2347dedd8b0c

### Social media

https://twitter.com/EdgelessSystems

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the September Release Radar and we couldn't include them all. Please submit your project again for consideration when you have version 3.0 released.
