### ISSUE TITLE
[Release Radar Request] KeussServer version 2.0

### ISSUE THREAD

**Issue by mjkwak** [github/release-radar#132]
### Open Source Project name

Keuss Server

### What is your project?

Job Queues server accessible via STOMP, AMQP 1.0 and REST, built with keuss (another open source project I'm involved in).

[https://pepmartinez.github.io/keuss-server/docs/](https://pepmartinez.github.io/keuss-server/docs/)

### Version

2.0

### Date

October 9, 2022

### Description of breaking changes

Version 2.0 Added support for Exchanges! 
[https://pepmartinez.github.io/keuss-server/docs/Usage/exchanges](https://pepmartinez.github.io/keuss-server/docs/Usage/exchanges)

### GitHub Repo

https://github.com/pepmartinez/keuss-server

### Website

https://pepmartinez.github.io/keuss-server/

### Link to changelog

https://pepmartinez.github.io/keuss-server/blog/exchanges

### Social media

Nope

### Anything else to add?

You rock! :)

**Comment by mishmanners** [comment]
Apologises that I didn't get this one in. Please submit when you have version 3.0 and we'd love to feature you.

**Comment by mjkwak** [comment]
Hi!
Don´t worry! You did mention our little project on the October Edition! You
rock!

https://github.blog/2022-12-09-release-radar-october-2022/
