### ISSUE TITLE
[RR Request]: Error Prone Support

### ISSUE THREAD

**Issue by japborst** [github/release-radar#133]
### Open Source Project name

Error Prone Support

### What is your project?

Error Prone Support is a [Picnic](https://blog.picnic.nl/)-opinionated extension of Google's [Error Prone](https://github.com/google/error-prone). It aims to improve code quality, focussing on maintainability, consistency, and avoidance of common pitfalls.

### Version

0.4

### Date

13 October 2022

### Description of breaking changes

No breaking changes

### GitHub Repo

https://github.com/PicnicSupermarket/error-prone-support

### Website

https://error-prone.picnic.tech/

### Link to changelog

https://github.com/PicnicSupermarket/error-prone-support/releases/tag/v0.4.0

### Social media

https://twitter.com/picnic/status/1580490192984559617

### Anything else to add?

We realize v0.4 might not sound like a major release, but it was. This is after a 5yr internal project got finally open sourced. Even though it's built upon Google's Error Prone, there have been major under the hood improvements; especially to be able to do efficient, large-scale Java rewrites.

https://github.com/github/release-radar/issues/133#tasklist-block-dd5bc706-6b25-49de-9373-28efaa11a763

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
