### ISSUE TITLE
[Release Radar Request] Box CLI Maker v2

### ISSUE THREAD

**Issue by Delta456** [github/release-radar#134]
### Open Source Project name

Box CLI Maker

### What is your project?

Make Highly Customized Terminal Boxes in CLI.

### Features
- Make a Terminal Box in 8️⃣ inbuilt different styles
- 16 Inbuilt Colors and True Color Support 🎨
- Custom Title Positions 📏
- Make your Terminal Box style 📦
- Support for ANSI, Tabbed, Multi-line and Line Wrapping boxes 📑
- Align the text according to your needs 📐
- Unicode, Emoji and [Windows Console](https://en.wikipedia.org/wiki/Windows_Console) Support 😋

### Version

2.0

### Date

Nov 09, 2020

### Changelog
- Use struct embedding to make the code cleaner
- Custom Color support via RGB (`[]uint`) and Hex (`uint`)
- Added support for Windows Console
- Optimized code
- Optimized `toString()` method
- Added a warning for invalid `TitlePos` provided then use the default position i.e. `Inside`
- Fix vertical alignment for multi line strings (#13)
- Make `Single` Style as Default if Style isn't provided
- Added support for tab lines
- `doc.go` for documentation on `pkg.go.dev`
- Added tests
- Fixed a bug when the alignment was given empty but still the error was reported
- Added more comments for making the code more readable
- Updated `go.mod` file to `v2`

### GitHub Repo

https://github.com/Delta456/box-cli-maker

### Website

https://pkg.go.dev/github.com/Delta456/box-cli-maker/v2

### Link to changelog

https://github.com/Delta456/box-cli-maker/releases/tag/v2.0.0

### Social media

https://twitter.com/Delta2315/status/1329315566641770496

### Anything else to add?

`v2` is a major release but `v2.3.0` should be used as many bugs and features were added.

https://github.com/github/release-radar/issues/134#tasklist-block-0f48a29a-4a7d-4b60-a4f1-d9bd50631ea8

**Comment by mishmanners** [comment]
Congrats on being featured in the November 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-12-16-release-radar-nov-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1604224922716454913)
