### ISSUE TITLE
[Release Radar Request] React-PDF

### ISSUE THREAD

**Issue by wojtekmaj** [github/release-radar#136]
### Open Source Project name

React-PDF

### What is your project?

React-PDF is a React library that allows you to easily render PDFs in your React applications.

### Version

6.0

### Date

November 8, 2022

### Description of breaking changes

The latest release included first-class Vite support, which has been a highly anticipated feature. It's also the first that ships modern JS by default, following IE 11 sunset. Aside from that, it bumps Mozilla's `pdfjs-dist` version, thus providing numerous performance and rendering quality improvements.

### GitHub Repo

https://github.com/wojtekmaj/react-pdf

### Website

https://projekty.wojtekmaj.pl/react-pdf

### Link to changelog

https://github.com/wojtekmaj/react-pdf/releases/tag/v6.0.0

### Social media

-

**Comment by mishmanners** [comment]
Congrats on being featured in the November 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-12-16-release-radar-nov-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1604224922716454913)
