### ISSUE TITLE
[Release Radar Request] React95 🕹🌈

### ISSUE THREAD

**Issue by arturbien** [github/release-radar#137]
### Open Source Project name

React95

### What is your project?

Windows 95 style UI component library for React ❤️

![v4](https://user-images.githubusercontent.com/28541613/201535179-fb8a9526-0ef4-4c81-8934-3dcd25447eb5.png)

### Version

4.0

### Date

13 November

### Description of breaking changes

1. Web version completely rewritten with TypeScript.
2. Released v1.0 of the React Native version

### GitHub Repo

https://github.com/react95-io/React95

### Website

https://react95.io/

### Link to changelog

https://github.com/react95-io/React95/releases/tag/v4.0.0

### Social media

https://twitter.com/react95_io/status/1591845891299999744?s=20&t=0JSaywgjjTOI87a_X5cYNg

**Comment by mishmanners** [comment]
Congrats on being featured in the November 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-12-16-release-radar-nov-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1604224922716454913)
