### ISSUE TITLE
[RR Request]: Llama 1.2.0

### ISSUE THREAD

**Issue by antonmedv** [github/release-radar#138]
### Open Source Project name

Llama

### What is your project?

Llama — a terminal file manager. A simple cd and ls replacement. 

### Version

1.2.0

### Date

21.11.2022

### Description of breaking changes

Vim key bindings. Preview mode. File deletions. 

### GitHub Repo

https://github.com/antonmedv/llama

### Website

https://github.com/antonmedv/llama

### Link to changelog

https://github.com/antonmedv/llama/releases/tag/v1.2.0

### Social media

https://twitter.com/antonmedv/status/1594982134267383809?s=46&t=SxgcPKrMPtqDK4kLn7DwQg

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 2.0 and we'd love to consider your project for feature 😄
