### ISSUE TITLE
[Release Radar Request] Dependabot Changelog Helper v2.0.0

### ISSUE THREAD

**Issue by dangoslen** [github/release-radar#139]
### Open Source Project name

Dependabot Changelog Helper

### What is your project?

A GitHub Action to help you easily manage dependabot package updates by adding them to your changelog!

Built around the [Keep-a-Changelog](https://keepachangelog.com/) format, this action will look for an entry line for an updated package and either
* Add it if not found (including adding the ### Dependencies and ## [<version>] sections!)
* Update it if the package has been upgraded after an initial entry was written

### Version

2.0.0

### Date

November 26

### Description of breaking changes

`newVersionLineNumber` is removed. Instead, if a version is not found, this action now looks for an unreleased version. If neither version can be found, the action will error. Read more in the [README.md](https://github.com/dangoslen/dependabot-changelog-helper/blob/v2.0.0/README.md#version)

### GitHub Repo

https://github.com/dangoslen/dependabot-changelog-helper

### Website

N/A

### Link to changelog

https://github.com/dangoslen/dependabot-changelog-helper/blob/main/CHANGELOG.md

### Social media

N/A

### Anything else to add?

N/A

**Comment by mishmanners** [comment]
Congrats on being featured in the November 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-12-16-release-radar-nov-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1604224922716454913)
