### ISSUE TITLE
[Release Radar Request] ArkScript v3.1.2, a scripting language for C++ projects

### ISSUE THREAD

**Issue by SuperFola** [github/release-radar#14]
### Open Source Project name

ArkScript

### What is your project?

ArkScript is a small, fast, functional and scripting language for C++ projects. Easy to embed in projects, using modern C++ and extensible through modules in a blink!

### Version

3.1.2

### Date

November 2, 2021

### Description of changes

Adding builtins mutating lists in place (to avoid temporary copies), improving the compiler errors, refactoring the code to remove useless functions and improve its readability for newcommers.

### GitHub Repo

https://github.com/ArkScript-lang/Ark

### Website

https://arkscript-lang.github.io/

### Link to changelog

https://github.com/ArkScript-lang/Ark/blob/dev/CHANGELOG.md#312---2021-11-02

### Social media

https://twitter.com/ArkScriptLang/status/1456236095323131912

### Anything else to add?

The project is still young (about 2 year old) but improving every day, and we are getting closer and closer to an official release on Arch Linux repositories!

**Comment by mishmanners** [comment]
Sorry we couldn't include this in the November Release Radar as that had already shipped. Please definitely submit again for v4.0 and we'd love to consider your project 😄
