### ISSUE TITLE
[Release Radar Request] CLI for Microsoft 365

### ISSUE THREAD

**Issue by Adam-it** [github/release-radar#140]
### Open Source Project name

CLI for Microsoft 365

### What is your project?

Using the CLI for Microsoft 365, you can manage your Microsoft 365 tenant and SharePoint Framework projects on any platform. No matter if you are on Windows, macOS or Linux, using Bash, Cmder or PowerShell, using the CLI for Microsoft 365 you can configure Microsoft 365, manage SharePoint Framework projects and build automation scripts.

### Version

6.0

### Date

November 30 2022

### Description of breaking changes

- Extended documentation with commands output
- Configure how you want to display commands help
- Create list items in batch
- Extended support for managing Power Platform (Manage Power Platform cards, Manage Dataverse tables, Manage Power Platform solutions and publishers)
- Manage versions of files stored in SharePoint

### GitHub Repo

https://github.com/pnp/cli-microsoft365

### Website

https://pnp.github.io/cli-microsoft365/

### Link to changelog

https://pnp.github.io/cli-microsoft365/about/release-notes/#v600

### Social media

https://twitter.com/climicrosoft365

### Anything else to add?

- CLI for Microsoft 365 just had its 5th birthday 🎂🥳
- we reached over 670 stars 🌟
- we broke the 100 contributors milestone 🤩 (thank you all for the awesome work on creating this open source tool 💪)

**Comment by mishmanners** [comment]
Congrats on being featured in the November 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-12-16-release-radar-nov-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1604224922716454913)
