### ISSUE TITLE
[Release Radar Request] typed-rpc 3.0.0

### ISSUE THREAD

**Issue by fgnass** [github/release-radar#142]
### Open Source Project name

typed-rpc

### What is your project?

Lightweight [JSON-RPC](https://www.jsonrpc.org/specification) solution for TypeScript projects with support for Node/Express, Deno, Cloudflare Workers and other edge runtimes.

### Version

3.0.0

### Date

December 8, 2022

### Description of breaking changes

Version 3 of `typed-rpc` is now backend agnostic and supports a wide range of server frameworks and JavaScript runtimes, including Deno.

### GitHub Repo

https://github.com/fgnass/typed-rpc

### Website

https://github.com/fgnass/typed-rpc

### Link to changelog

https://github.com/fgnass/typed-rpc/releases/tag/v3.0.0

### Social media

https://twitter.com/fgnass/status/1600854063628820480

### Anything else to add?

Typed-rpc has no fancy project homepage, and that's intentional. We believe that the documentation of a simple library should fit into a single, equally simple README file.

**Comment by mishmanners** [comment]
Congrats on being featured in the Dec/Jan Festive Release Radar 🥳

- Read the blog [here](https://github.blog/2023-02-08-release-radar-dec-2022-jan-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1624876004421271555)
