### ISSUE TITLE
[RR Request]: Sponsor v1.0.0

### ISSUE THREAD

**Issue by zhyd1997** [github/release-radar#143]
### Open Source Project name

Sponsor

### What is your project?

Sponsor devs on github but using crypto and streaming per second.

### Version

1.0.0

### Date

Dec 12, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/zhyd1997/sponsor

### Website

https://sponsor-zhyd1997.vercel.app/

### Link to changelog

https://github.com/zhyd1997/sponsor/releases/tag/v1.0.0

### Social media

https://twitter.com/zhyd007/status/1588094921507946496?s=20&t=n2d0iOFa5kZpp7mQrSaN9g

### Anything else to add?

[Slides and Recording video](https://drive.google.com/drive/folders/1oMR5YTAWBXX3SzPt5E-SeIcewGeO1gb8?usp=sharing)

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the Dec/Jan Release Radar and we couldn't include them all.
