### ISSUE TITLE
[Release Radar Request] AMPHP v3

### ISSUE THREAD

**Issue by kelunik** [github/release-radar#144]
### Open Source Project name

AMPHP

### What is your project?

AMPHP is a collection of event-driven libraries for PHP designed with fibers and concurrency in mind. Its packages allow building entire applications using non-blocking I/O to allow for concurrency in long-running processes and server applications.

### Version

3.0.0

### Date

December 18, 2022

### Description of breaking changes

Amp no longer ships its own event loop. It's now based on [Revolt](https://revolt.run/). Promises and generators have been replaced with futures and fibers, which allows reusing existing interfaces designed for blocking code with non-blocking I/O under the hood.

### GitHub Repo

https://github.com/amphp/amp

### Website

https://amphp.org

### Link to changelog

https://github.com/amphp/amp/releases/tag/v3.0.0

### Social media

https://twitter.com/asyncphp/status/1604865620641734657

### Anything else to add?

The base library `amphp/amp` and [`amphp/sync`](https://github.com/amphp/sync/releases/tag/v2.0.0) have been released in December 2022. Other libraries of the project will see stable releases of the current beta versions soon this year.

**Comment by kelunik** [comment]
If you want to include visuals in the post, please use the [orange arrow logo](https://github.com/amphp/logo/blob/79a515cf4f3028644bcf07ce8337cddc6169a771/repos/amp-v3-logo.png), which is the v3 version.

**Comment by mishmanners** [comment]
Congrats on being featured in the Dec/Jan Festive Release Radar 🥳

- Read the blog [here](https://github.blog/2023-02-08-release-radar-dec-2022-jan-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1624876004421271555)

**Comment by kelunik** [comment]
Thank you! 🥳
