### ISSUE TITLE
[Release Radar Request] Blaze v3.0.0

### ISSUE THREAD

**Issue by blenderskool** [github/release-radar#145]
### Open Source Project name

Blaze

### What is your project?

Blaze is a peer-to-peer file sharing web app that works across all networks and devices without requiring any native apps to be installed. Since file sharing is peer-to-peer, files are never persisted on a server making it extremely useful in moments when you just want to transfer a file from one device to another. It also supports peer-to-peer file sharing with multiple devices at once which many file sharing apps lack ⚡️

### Version

3.0

### Date

January 4, 2023

### Description of breaking changes

Major changes(None of them are breaking):
- Local network rooms to share files with devices in the local network.
- Most requested settings page, support page w
- UI redesign with smooooth page transitions and animations!

### GitHub Repo

https://github.com/blenderskool/blaze

### Website

https://blaze.now.sh

### Link to changelog

https://github.com/blenderskool/blaze/releases/tag/v3.0.0

### Social media

https://twitter.com/blenderskool/status/1610637269391802368

### Anything else to add?

I also made a promo video to celebrate this release!

**Comment by mishmanners** [comment]
Congrats on being featured in the Dec/Jan Festive Release Radar 🥳

- Read the blog [here](https://github.blog/2023-02-08-release-radar-dec-2022-jan-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1624876004421271555)
