### ISSUE TITLE
[RR Request]: DiceBear 5.0

### ISSUE THREAD

**Issue by FlorianKoerner** [github/release-radar#146]
### Open Source Project name

DiceBear

### What is your project?

With DiceBear you create avatars for your profiles, designs, websites or apps. Piece by piece or based on a seed. Whether you are looking for abstract shapes or lovingly designed characters, you will find something suitable among our avatar styles. And no matter how and for what you want to use the avatars, DiceBear offers the right solution!

### Version

5.0

### Date

Jan. 10, 2023

### Description of breaking changes

With the new version there are 6 more new avatar styles to choose from. The export is now also possible in the formats PNG and JPG. Also new: The playground to create and test the avatars directly in the browser.

### GitHub Repo

https://github.com/dicebear/dicebear

### Website

https://dicebear.com

### Link to changelog

https://github.com/dicebear/dicebear/discussions/255

### Social media

https://github.com/dicebear/dicebear/discussions/255

**Comment by mishmanners** [comment]
Congrats on being featured in the Dec/Jan Festive Release Radar 🥳

- Read the blog [here](https://github.blog/2023-02-08-release-radar-dec-2022-jan-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1624876004421271555)
