### ISSUE TITLE
[RR Request]:  ToolJet v2.0

### ISSUE THREAD

**Issue by withshubh** [github/release-radar#147]
### Open Source Project name

ToolJet

### What is your project?

[ToolJet](https://www.tooljet.com) is an open-source low-code framework to build and deploy custom internal tools.

ToolJet ships with its built-in database called [ToolJet DB](https://docs.tooljet.com/docs/tooljet-database) (built on top of PostgreSQL). You can also connect to external data sources such as databases ( PostgreSQL, MongoDB, MS SQL Server, Snowflake, BigQuery, etc ), API/GraphQL endpoints, SaaS tools ( Airtable, Stripe, Google Sheets, etc ), and cloud object storage services ( AWS S3, Google Cloud Storage and Minio ).

Once the data sources are connected, ToolJet can run queries on these data sources to fetch and update data. The data fetched from data sources can be visualized and modified using the UI widgets such as tables, charts, forms, etc. You can also use [Javascript](https://docs.tooljet.com/docs/data-sources/run-js) or [Python](https://docs.tooljet.com/docs/data-sources/run-py) queries for writing business logic or interacting with the user interface of the application.

### Version

2.0

### Date

January 10, 2023

### Description of breaking changes

Here is the list of new features that we’ve shipped in ToolJet v2.0:
- Refreshed user interface (App Builder, Homepage, Query Panel)
- ToolJet Database: ToolJet now comes with an in-built no-code database that is built on top of PostgreSQL.
- Added support for multi-page applications.
- now you can also use Python within ToolJet
- Form component
- Multi-Environment for applications

### GitHub Repo

https://github.com/ToolJet/ToolJet

### Website

https://www.tooljet.com/

### Link to changelog

https://github.com/ToolJet/ToolJet/releases/tag/v2.0.0

### Social media

https://twitter.com/ToolJet/status/1612778740945424386

### Anything else to add?

https://blog.tooljet.com/announcing-tooljet-2-0/

**Comment by mishmanners** [comment]
Congrats on being featured in the Dec/Jan Festive Release Radar 🥳

- Read the blog [here](https://github.blog/2023-02-08-release-radar-dec-2022-jan-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1624876004421271555)
