### ISSUE TITLE
[RR Request]: neo.mjs v5.0.0

### ISSUE THREAD

**Issue by tobiu** [github/release-radar#148]
### Open Source Project name

neo.mjs

### What is your project?

neo.mjs is a multithreaded JavaScript frontend framework for building high-performance, responsive, and scalable web applications. It follows the "an application worker being the main actor" paradigm.

### Version

5.0

### Date

January 26, 2023

### Description of breaking changes

Version 5 simplifies the class config system a lot to enhance the developer experience plus further boosting the rendering performance and evolving widgets. Developers will need to replace `static getConfig() {return {/**/}}` with just `static config = {/**/}`.

### GitHub Repo

https://github.com/neomjs/neo

### Website

https://neomjs.github.io/pages/

### Link to changelog

https://github.com/neomjs/neo/releases/tag/5.0.0

### Social media

https://tobiasuhlig.medium.com/the-next-generation-of-front-end-development-65887c59b173?source=friends_link&sk=51654f60033120e84454791015d8d205

### Anything else to add?

[update] added the release blog post

**Comment by tobiu** [comment]
@mishmanners thanks for mentioning neo inside the latest blog! :)

2 things i noticed:
1. title: neo.msj => neo.mjs (module JS)
2. 2000 changed lines of code does not give us justice :) 

it would be super nice, in case you could adjust this.

version 4 was at 7876 commits:
https://github.com/neomjs/neo/tree/57e2a69c0976b4cb9c9177a0e0c13c3e3c6ac6bb

version 5 was at 9749 commits:
https://github.com/neomjs/neo/tree/69348806fb4b07812fb507dce1f3e3d7e325a75f

my wild guess is that we touched (changed) more than 50.000 lines of code several times. in theory you could compare the 2 versions and get the exact number. you are the experts on git after all :) please let me know in case you do, now i got curious ;)

Best regards,
Tobi

**Comment by mishmanners** [comment]
Thanks for this Tobi. I took the 2000 lines of code from your post announcement. I'll get this updated asap

**Comment by mishmanners** [comment]
Updated.

**Comment by tobiu** [comment]
@mishmanners thank you <3

Exciting times in general, now that we start with upskilling more developers in neo. The blog post went kind of viral:
<img width="953" alt="Screenshot 2023-02-01 at 11 10 14" src="https://user-images.githubusercontent.com/1177434/218250816-9662c383-10dc-4bb4-934b-5936a2c95353.png">

Best regards & enjoy the weekend,
Tobi

**Comment by mishmanners** [comment]
Congrats on being featured in the Dec/Jan Festive Release Radar 🥳

- Read the blog [here](https://github.blog/2023-02-08-release-radar-dec-2022-jan-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1624876004421271555)
