### ISSUE TITLE
[RR Request]: Roadmap Voting App v1.0

### ISSUE THREAD

**Issue by harinij** [github/release-radar#149]
### Open Source Project name

Roadmap

### What is your project?

Product roadmap app that can be shared publicly with your users to collect valuable feedback. Users can upvote/downvote on features, add comments, and request new features. Open-source and fully free. 

App’s frontend is built with Remix and the backend is built with [Rowy](https://www.rowy.io/?utm_source=github&utm_campaign=readme&utm_medium=roadmap) (a lowcode platform for Firebase).

### Version

1.0

### Date

January 26, 2023

### Description of breaking changes

nil

### GitHub Repo

https://github.com/rowyio/roadmap

### Website

https://roadmap.vote

### Link to changelog

https://github.com/rowyio/roadmap/releases/tag/v1.0.0

### Social media

https://twitter.com/rowyio/status/1618610641618751488?s=20&t=3i5C5IZsb3bY7Uhga-tR0g

**Comment by mishmanners** [comment]
Congrats on being featured in the Dec/Jan Festive Release Radar 🥳

- Read the blog [here](https://github.blog/2023-02-08-release-radar-dec-2022-jan-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1624876004421271555)
