### ISSUE TITLE
[Release Radar Request] soketi - Just another simple, fast, and resilient open-source WebSockets server. 📣

### ISSUE THREAD

**Issue by rennokki** [github/release-radar#15]
### Open Source Project name

soketi

### What is your project?

Just another simple, fast, and resilient open-source WebSockets server. 📣

soketi implements the Pusher Protocol v7 (and soon, more!) so that any Pusher-maintained client can connect to it, bringing a just-change-the-pusher-client-credentials experience for the already-built frontend apps.

### Version

0.17.0

### Date

November 27, 2021

### Description of changes

- Dropped Node.js 14.x build for Docker (there was no reason for 14.x if it ran in 16.x which is LTS)
- @stayallive pointed out in #124 that exposing the `/metrics` and `/usage` endpoints to `6001` (which is public) was a bad idea in terms of security. Starting with this version, the server will run the metrics to a different port (`9601`) which may **not** be exposed to the internet. This way, you can run the Prometheus Scrape service within your server or in your private network.

Notable milestone achieved before this update: AWS Lambda invocations for Webhooks (https://github.com/soketi/soketi/pull/147)

### GitHub Repo

https://github.com/soketi/soketi

### Website

https://renoki.org

### Link to changelog

https://github.com/soketi/soketi/releases/tag/0.17.0

### Social media

-

### Anything else to add?

-

**Comment by mishmanners** [comment]
Sorry we couldn't include this in the November Release Radar as that had already shipped. Please definitely submit again for your next version and we'd love to consider your project 😄
