### ISSUE TITLE
[Release Radar Request] RIFE2 Java web framework v1.0.0

### ISSUE THREAD

**Issue by gbevin** [github/release-radar#150]
### Open Source Project name

RIFE2

### What is your project?

RIFE2 is a full-stack, no-declaration, framework to quickly and effortlessly create web applications with modern Java.

RIFE2 is built on the foundations of the original RIFE framework that was popular from 2002-2010. Since then, the world and Java have changed and many of the original RIFE APIs could finally be replaced with pure Java, no-XML, no-YAML, leaving only type-safe expressive code.

### Version

1.0.0

### Date

January 22, 2023

### Description of breaking changes

Complete re-invention of the original RIFE framework.

### GitHub Repo

https://github.com/gbevin/rife2

### Website

https://rife2.com

### Link to changelog

https://github.com/gbevin/rife2/discussions/11

### Social media

https://twitter.com/gbevin/status/1616894386096295936

### Anything else to add?

Thanks for considering my project!

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the January Release Radar, as that had already shipped. Please definitely submit again for version 2.0 and we'd love to consider your project 😄
