### ISSUE TITLE
[Release Radar Request] ShareX 15.0.0

### ISSUE THREAD

**Issue by Jaex** [github/release-radar#151]
### Open Source Project name

ShareX

### What is your project?

ShareX is a free and open source program that lets you capture or record any area of your screen and share it with a single press of a key. It also allows uploading images, text or other types of files to many supported destinations you can choose from.

### Version

15.0.0

### Date

January 18, 2023

### Description of breaking changes

* A new dark theme [*](https://twitter.com/ShareX/status/1558720652768694273)
* Updated [our website](https://getsharex.com) theme to fit to new ShareX dark theme
* A new "Pin to screen" tool that lets you place a screenshot on display and keep it there [*](https://twitter.com/ShareX/status/1550406179003813894)
* Improved hotkey settings window with new drop-down menus that allow changing tasks without opening the task settings window [*](https://twitter.com/ShareX/status/1553798642523316224)
* The screen recorder now allows pausing the ongoing recording and moving the region when on pause [*](https://twitter.com/ShareX/status/1566154367887183873) [*](https://twitter.com/ShareX/status/1566471627000479745)
* A new "Freehand arrow" annotation tool
* All ShareX builds now include [FFmpeg](https://github.com/ShareX/FFmpeg/releases/tag/v5.1) built-in

### GitHub Repo

https://github.com/ShareX/ShareX

### Website

https://getsharex.com

### Link to changelog

https://getsharex.com/changelog

### Social media

https://twitter.com/ShareX/status/1615543455119446018

### Anything else to add?

Now we are using [GitHub Actions](https://github.com/ShareX/ShareX/blob/develop/.github/workflows/build.yml) to release builds and we also have [GitHub Sponsors profile](https://github.com/sponsors/Jaex).

GitHub rocks!

**Comment by mishmanners** [comment]
Congrats on being featured in the Dec/Jan Festive Release Radar 🥳

- Read the blog [here](https://github.blog/2023-02-08-release-radar-dec-2022-jan-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1624876004421271555)
