### ISSUE TITLE
[Release Radar Request] Moby 23.0.0

### ISSUE THREAD

**Issue by neersighted** [github/release-radar#152]
### Open Source Project name

Moby (fomerly Docker Engine)

### What is your project?

Moby (formerly known as the Docker Engine) is the original Linux Container runtime & the most used set of development tools for Linux Containers. It deployed in production by many, and comes with many powerful features included, such as networking and the Swarm orchistrator.

### Version

23.0.0

### Date

February 2, 2023

### Description of breaking changes

Moby 23.0.0 is the first major release in two years, and brings too many change to list. Some highlights include that BuildKit/Buildx are now the default build experience on Linux, alternate container runtimes are now better supported, and SwarmKit gains new features such as experimental support for CSI (Container Storage Interface) plugins.

There is a laundry list of additional features, and enhancements, and significant numbers of deprecations have been turned into removals -- users should review the release notes carefully, and test in a lab environment before migrating in production.

### GitHub Repo

https://github.com/moby/moby

### Website

https://mobyproject.org

### Link to changelog

https://docs.docker.com/engine/release-notes/23.0/

### Social media

https://twitter.com/scottcjohnston/status/1622636829781417984

**Comment by mishmanners** [comment]
Congrats on being featured in the [February 2023 Release Radar](https://github.blog/2023-03-05-release-radar-feb-2023/).
