### ISSUE TITLE
[Release Radar Request] Snippets for VSCode v3.0.0

### ISSUE THREAD

**Issue by tahabasri** [github/release-radar#153]
### Open Source Project name

Snippets for VSCode

### What is your project?

VSCode extension that lets you play with your code snippets without quitting your editor. Offers advanced UI panel with various options for snippets management.

### Version

3.0.0

### Date

February, 13, 2023

### Description of breaking changes

Many users asked for the **Drag and Drop** support! It's available now and it made organizing snippets much simpler ✨

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/056-drag-and-drop.gif" alt="Drag and Drop Snippets">

### GitHub Repo

https://github.com/tahabasri/snippets

### Website

https://github.com/tahabasri/snippets

### Link to changelog

https://github.com/tahabasri/snippets/releases/tag/3.0.0

### Social media

https://www.linkedin.com/posts/activity-7030707238163869696-sWnA?utm_source=share&utm_medium=member_desktop

### Anything else to add?

Snippets is used by more than 18k users ✅ Check the [full list](https://github.com/tahabasri/snippets/blob/main/README.md) of the amazing features it offers.

**Comment by mishmanners** [comment]
Congrats on being featured in the [February 2023 Release Radar](https://github.blog/2023-03-05-release-radar-feb-2023/).
