### ISSUE TITLE
[RR Request]: Front Matter v8.3.0

### ISSUE THREAD

**Issue by estruyf** [github/release-radar#154]
### Open Source Project name

Front Matter

### What is your project?

Experience the best of both worlds with Front Matter, the CMS that runs within Visual Studio Code, GitPod, and many more. Get the control over your static generator's content by bringing in the CMS features from Front Matter. Start creating and previewing content in real-time - no complicated setup - choose Front Matter CMS and start creating amazing content today.

### Version

8.3.0

### Date

February 14, 2023

### Description of breaking changes

FrontMatter is back and better than ever with its latest release, version 8.3.0! This update is packed with new features and improvements, including external config support, allowing you to easily import configurations from external files. Plus, with VSCode theme support, you can customize your development environment to your heart's content. But that's not all - there are many other exciting additions and enhancements waiting for you. Check out the release notes to see what's new and upgrade to FrontMatter 8.3.0 today!

### GitHub Repo

https://github.com/estruyf/vscode-front-matter

### Website

https://frontmatter.codes/

### Link to changelog

https://frontmatter.codes/updates/v8.3.0

### Social media

https://twitter.com/frontmattercms/status/1625522515337531392?s=20&t=UWUZVAuzyirUbnNCOUa_xg

### Anything else to add?

Keep on rocking 🤘

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project, and we have loved featuring Front Matter in previous release radars. The Release Radar features major version releases. Please submit again when you have version 9.0 and we'd love to consider your project for feature again 😄
