### ISSUE TITLE
[Release Radar Request] Brainchop V2.0.0

### ISSUE THREAD

**Issue by Mmasoud1** [github/release-radar#156]
### Open Source Project name

Brainchop

### What is your project?

[Brainchop](https://github.com/neuroneural/brainchop) is a web-based tool that allows scientists and clinicians to perform volumetric analysis of structural Magnetic Resonance Imaging (MRI) using pre-trained deep learning models, without the need for technical expertise or setup of AI solutions. It is the first browser-based front-end MRI segmentation tool that can process full brain volumes in a single pass, using the lightweight MeshNet segmentation model. In addition to offering extensibility through an open-source framework, Brainchop also addresses privacy concerns by performing client-side processing and leveraging hardware acceleration across different brands and architectures. 

### Version

2.0.0

### Date

February 21, 2023

### Description of breaking changes

With v2.0.0, Brainchop accumulated  many features for the first time in the browser including its preprocessing pipeline for reshaping/normalizing/resampling MRI raw input data,  3D real-time rendering of the input and output volumetric data,  3D Image processing algorithms for data denoising and enhancing,   full brain volume inference in a single pass,  bar chart to plot  segmentation output volumes, multiple built-in models to perform different brain segmentation task, post-processing algorithm for  noise removal. 

### GitHub Repo

https://github.com/neuroneural/brainchop

### Website

https://github.com/neuroneural/brainchop

### Link to changelog

https://trendscenter.org/in-browser-3d-mri-segmentation-brainchop-org/

### Social media

https://twitter.com/MMasoud2021

**Comment by Mmasoud1** [comment]
![BrainchopBanner](https://user-images.githubusercontent.com/36082112/220264337-1ff1ee1d-8193-43b6-afbd-e71c3b918eb0.png)

**Comment by mishmanners** [comment]
Congrats again on being featured in the [February 2023 Release Radar](https://github.blog/2023-03-05-release-radar-feb-2023/).
