### ISSUE TITLE
[RR Request]: Qdrant v1.0

### ISSUE THREAD

**Issue by azayarni** [github/release-radar#157]
### Open Source Project name

Qdrant

### What is your project?

Qdrant is an open-source Vector Search Database written in Rust 🦀. It deploys as an API service providing a search for the nearest high-dimensional vectors. With Qdrant, embeddings or neural network encoders can be turned into full-fledged applications for matching, searching, recommending, and much more solutions to make the most of unstructured data. It is easy to use, deploy and scale, blazing fast and is accurate simultaneously.

### Version

1.0

### Date

February 8, 2023

### Description of breaking changes

With two years of development and 37 previous versions we successfully completed the core API, prepared an extendable platform for upcoming features, delivered full horizontal scalability for both size and speed as well as achieved industry leading performance. https://qdrant.tech/benchmarks/

### GitHub Repo

https://github.com/qdrant/qdrant

### Website

https://qdrant.tech

### Link to changelog

https://github.com/qdrant/qdrant/releases/tag/v1.0.0

### Social media

https://www.linkedin.com/feed/update/urn:li:activity:7029060075751129088/

### Anything else to add?

Maybe also worth to mention. We take part in this year's Google Summer of Code https://summerofcode.withgoogle.com/programs/2023/organizations/qdrant, and there is an upcoming Hackathon with cohere.ai and Qdrant. https://lablab.ai/event/multilingual-semantic-search-hackathon Since you like Hackathons :) 

Thanks, Mish! You Rock :)

**Comment by mishmanners** [comment]
Congrats on being featured in the [February 2023 Release Radar](https://github.blog/2023-03-05-release-radar-feb-2023/).
