### ISSUE TITLE
[Release Radar Request] Dallecli v1.0.0

### ISSUE THREAD

**Issue by raiyanyahya** [github/release-radar#158]
### Open Source Project name

DalleCli

### What is your project?

Provide users with the ability to generate, edit and filter images using the DALL-E 2 API provided by OpenAI, all from the command line.

### Version

1.0.0

### Date

24th February 2023

### Description of breaking changes

This version 1 includes error handling and fixes for minor bugs when creating filters.

### GitHub Repo

https://github.com/raiyanyahya/dallecli

### Website

https://dallecli.com

### Link to changelog

https://github.com/raiyanyahya/dallecli/releases/tag/v1.0.0

### Social media

https://twitter.com/raiyan_yahya/status/1629193278489784322?t=oj8n4a6sYz4Ds9EvbFwpJQ&s=19

### Anything else to add?

Thank you.

**Comment by mishmanners** [comment]
Congrats on being featured in the [February 2023 Release Radar](https://github.blog/2023-03-05-release-radar-feb-2023/).

**Comment by raiyanyahya** [comment]
Thank you @mishmanners . This made my day!
