### ISSUE TITLE
[RR Request]: Chat Analytics v1.0.0

### ISSUE THREAD

**Issue by mlomb** [github/release-radar#159]
### Open Source Project name

Chat Analytics

### What is your project?

A web app that takes chat exports from supported platforms and generates a single HTML file containing information, statistics and interactive graphs about them. It has privacy as its main concern; no data ever leaves the device when generating reports.

### Version

v1.0.0

### Date

March 3, 2023

### Description of breaking changes

nil

### GitHub Repo

https://github.com/mlomb/chat-analytics

### Website

https://chatanalytics.app

### Link to changelog

https://github.com/mlomb/chat-analytics/releases/tag/v1.0.0

### Social media

NA

### Anything else to add?

After more than two years of developing this tool in my free time, I feel the app has reached a point that I can call version one 😄

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.

**Comment by mlomb** [comment]
Than you very much! 🎊😄
