### ISSUE TITLE
[RR Request]: Bootiful 1.0 - A "Tailwind-like" Bootstrap v5 template 

### ISSUE THREAD

**Issue by bdavidxyz** [github/release-radar#16]
### Open Source Project name

Bootiful

### What is your project?

A free, open-source, Bootstrap v5 theme. It has focus on classic pages, profile pages, and admin pages. All the code is based on utility classes, so it's a "Tailwind-like" template, but with Bootstrap v5. Only 4 scss file to include in your project.

### Version

1.0

### Date

12 november 2021

### Description of changes

First release.

### GitHub Repo

https://github.com/bdavidxyz/bootiful/

### Website

https://bootiful.org

### Link to changelog

https://bootiful.org/changelog

### Social media

https://twitter.com/anthonynsimon/status/1464278988675854336

### Anything else to add?

Thanks !

**Comment by mishmanners** [comment]
Sorry we couldn't include this in the November Release Radar as that had already shipped. Please definitely submit again for v2.0 and we'd love to consider your project 😄
