### ISSUE TITLE
[Release Radar Request] <QuestDB 7.0>

### ISSUE THREAD

**Issue by tris0laris** [github/release-radar#160]
### Open Source Project name

QuestDB

### What is your project?

QuestDB is an open source time-series database focused on performance and simplicity. It is built for real-time analytics of any scale using just SQL. QuestDB is well suited for financial market data, sensor data, user-facing dashboards, real-time analytics, and infrastructure monitoring.

### Version

7.0

### Date

Thursday 2, 2023

### Description of breaking changes

QuestDB 7.0. implements a new storage engine layer, introducing a Write Ahead Long (WAL) to improve data ingestion speed, concurrency and reliability. QuestDB 7.0 also packs a new UI for the SQL web console.

Benefits include:
- Ingestion throughput is 3x higher, reaching up to 4.4M rows/sec. Benchmark specifics can be found in the release notes.
- Lock-free concurrent writes across all interfaces.
- Foundational groundwork for High Availability: Replication will work with WAL tables only

The new SQL console can be accessed via https://demo.questdb.io/

### GitHub Repo

https://github.com/questdb/questdb

### Website

https://questdb.io/

### Link to changelog

https://github.com/questdb/questdb/releases/tag/7.0.1

### Social media

https://twitter.com/QuestDb/status/1630884443400425472

### Anything else to add?

7.0.1 is the production-ready release of 7.0: https://github.com/questdb/questdb/releases/tag/7.0.1

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.
