### ISSUE TITLE
[Release Radar Request] Microsoft Kiota v1.0

### ISSUE THREAD

**Issue by baywet** [github/release-radar#161]
### Open Source Project name

Microsoft Kiota

### What is your project?

Kiota is a modern client code generator for OpenAPI and REST. It supports multiple languages and provides model classes, a chained API surface to build requests and much more! 
Kiota differentiates itself from other generators by its simplicity, un-opiniated choices about the serialization formats/libraries, HTTP clients or authentication schemes/libraries.
Additionally, Kiota enables selecting just the parts of the API that you need to call and generates out a client for your needs.

### Version

1.0.0

### Date

2023-03-09

### Description of breaking changes

This first major version comes with the C#/dotnet language as a stable language and Go/Java/TypeScript/PHP/Python/Ruby/CLI as preview languages. Right now the generator is available as a CLI and we're working to enable additional experiences (GUI/CI/...).
We're also working to get the other languages to a stable maturity level as well as to add more languages.

### GitHub Repo

https://github.com/microsoft/kiota

### Website

https://microsoft.github.io/kiota

### Link to changelog

https://github.com/microsoft/kiota/blob/main/CHANGELOG.md

### Social media

upcoming

**Comment by baywet** [comment]
For information the website now moved to here https://learn.microsoft.com/openapi/kiota/

**Comment by baywet** [comment]
Thank you for sharing this release in this month's edition! Closing this issue.

**Comment by mishmanners** [comment]
Our pleasure! Glad you enjoyed it. For reference, here's the [link to the blog post](https://github.blog/2023-07-13-release-radar-spring-23/).
