### ISSUE TITLE
[Release Radar Request] Prompt v1.0.0

### ISSUE THREAD

**Issue by raiyanyahya** [github/release-radar#162]
### Open Source Project name

Prompt

### What is your project?

A command line application to interact with OpenAI ChatGPT API.

`prompt` is designed to provide users a command-line interface for the ChatGPT API, which uses OpenAI's GPT language model to generate text based on user input.

The application helps you start a session with ChatGPT so that the `context` is preserved and longer conversions with contexts are considered. The user's prompts and the responses are sent back to ChatGPT everytime.

The ChatGPT api usage depends on the number of tokens used and it is important that you use the tokens wisely. After a prompt has been answered the application will resend the last prompt and answer in the next prompt, this makes sure you can have a continued conversion with ChatGPT `(much like using ChatGPT in a single chat session)`. This makes the token count larger and larger as you continue to chat. If you are not concerned with context use the `--clear` flag which will save your token usage.

### Version

1.0.0

### Date

March 11 2023

### Description of breaking changes

This is the first version of the cmd line app. It fixes some bugs in error handling and also brings in some feature requests made.

### GitHub Repo

https://github.com/raiyanyahya/prompt

### Website

https://promptcli.com

### Link to changelog

https://github.com/raiyanyahya/prompt/releases/tag/v1.0.0

### Social media

https://twitter.com/raiyan_yahya/status/1631947350989045760

### Anything else to add?

Thank you for considering this project!

**Comment by raiyanyahya** [comment]
Hi @mishmanners are you still considering submissions ?

**Comment by mishmanners** [comment]
Apologises for this, we combined March-June into a Spring edition. Thank you for submitting your project. We had a lot of projects submitted for our latest Release Radar and we couldn't include them all. Please submit your project again for consideration when you have version 2.0.
