### ISSUE TITLE
[RR Request]: Ionic Framework v7.0

### ISSUE THREAD

**Issue by liamdebeasi** [github/release-radar#163]
### Open Source Project name

Ionic Framework

### What is your project?

Ionic is an open source UI toolkit for building performant, high-quality mobile apps using web technologies — HTML, CSS, and JavaScript — with integrations for popular frameworks like Angular, React, and Vue.

### Version

7.0

### Date

March 29, 2023

### Description of breaking changes

The latest changes include the ability to write declarative overlay components, a simplified form control syntax, and event emission consistency improvements. We also improved the performance of tabs switches in Ionic React and Ionic Vue as well as component initialization in Ionic Angular. Finally, we removed IonSlides in favor of using Swiper.js directly and IonVirtualScroll in favor of solutions provided by more JavaScript Frameworks.

### GitHub Repo

https://github.com/ionic-team/ionic-framework

### Website

https://ionicframework.com/

### Link to changelog

https://ionic.io/blog/ionic-7-is-here

### Social media

https://twitter.com/Ionicframework/status/1641425291254923265

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.

**Comment by liamdebeasi** [comment]
Thank you very much!
