### ISSUE TITLE
[Release Radar Request] Karate 1.4.0

### ISSUE THREAD

**Issue by ptrthomas** [github/release-radar#164]
### Open Source Project name

Karate

### What is your project?

Karate is the only open-source tool to combine API test-automation, mocks, performance-testing and even UI automation into a single, unified framework.

### Version

1.4.0

### Date

April 03, 2023

### Description of breaking changes

☕ The minimum Java version is 11
🔐 Important security fixes

### GitHub Repo

https://github.com/karatelabs/karate

### Website

https://karatelabs.github.io/karate/

### Link to changelog

https://github.com/karatelabs/karate/releases/tag/v1.4.0

### Social media

https://twitter.com/getkarate/status/1642700648532819969

### Anything else to add?

Karate Labs is a GitHub Technology Partner: https://twitter.com/getkarate/status/1618577728617451520

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 2.0 and we'd love to consider your project for feature 😄
