### ISSUE TITLE
[RR Request]: LocalStack v2.0

### ISSUE THREAD

**Issue by HarshCasper** [github/release-radar#165]
### Open Source Project name

LocalStack

### What is your project?

LocalStack is a cloud service emulator that runs in a single container on your laptop or in your CI environment. With LocalStack, you can run your AWS applications or Lambdas entirely on your local machine without connecting to a remote cloud provider! Whether you are testing complex CDK applications or Terraform configurations, or just beginning to learn about AWS services, LocalStack helps speed up and simplify your testing and development workflow.

### Version

2.0

### Date

March 30, 2023

### Description of breaking changes

https://discuss.localstack.cloud/t/upcoming-changes-for-localstack-v2/239/2

### GitHub Repo

https://github.com/localstack/localstack

### Website

http://localstack.cloud/

### Link to changelog

https://localstack.cloud/blog/2023-03-29-announcing-localstack-2.0-general-availability/

### Social media

https://twitter.com/_localstack/status/1641459073152593923

### Anything else to add?

Thanks for the initiative!

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.
