### ISSUE TITLE
[RR Request]: FerretDB 1.0

### ISSUE THREAD

**Issue by AlekSi** [github/release-radar#166]
### Open Source Project name

FerretDB

### What is your project?

A truly Open Source MongoDB alternative, built on Postgres.

### Version

1.0

### Date

April 11, 2023

### Description of breaking changes

After several months of development, FerretDB is now production-ready. We are excited to announce the general availability of FerretDB, a truly Open Source MongoDB alternative, built on PostgreSQL, and released under the Apache 2.0 license.

### GitHub Repo

https://github.com/FerretDB/FerretDB

### Website

https://www.ferretdb.io

### Link to changelog

https://github.com/FerretDB/FerretDB/releases/tag/v1.0.0

### Social media

https://twitter.com/ferret_db/status/1645767000029818882

### Anything else to add?

https://techhub.social/@ferretdb/110180201048321859

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for our latest Release Radar and we couldn't include them all. Please submit your project again for consideration when you have version 2.0.
