### ISSUE TITLE
[Release Radar Request] Unpoly 3

### ISSUE THREAD

**Issue by triskweline** [github/release-radar#169]
### Open Source Project name

Unpoly

### What is your project?

[Unpoly](https://unpoly.com/) is an unobtrusive JavaScript framework for server-side web applications.
It enables fast and flexible frontends while keeping rendering logic on the server.

### Version

3.0.0

### Date

April 17, 2023

### Description of breaking changes

The main concern of Unpoly 3 is to **fix all the concurrency issues** arising from real-world production use:

- Forms where many fields depend on the value of other fields
- Multiple users working on the same backend data (stale caches)
- User clicking faster than the server can respond
- User losing connection while requests are in flight
- Lie-Fi (spotty Wi-Fi, EDGE, tunnel)

Unpoly 3 also ships numerous **quality of life improvements** based on community feedback.

There is also a [slide deck](http://triskweline.de/unpoly3-slides/) explaining the most relevant changes in more detail.

### GitHub Repo

https://github.com/unpoly/unpoly

### Website

https://unpoly.com

### Link to changelog

https://github.com/unpoly/unpoly/discussions/472

### Social media

https://twitter.com/unpolyjs/status/1647953406001029123

### Anything else to add?

Thank you for this opportunity to spread the word about our project.

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for our latest Release Radar and we couldn't include them all. Please submit your project again for consideration when you have version 4.0.
