### ISSUE TITLE
Release Radar Request

### ISSUE THREAD

**Issue by codewithpom** [github/release-radar#17]
### Open Source Project name

moviez

### What is your project?

It is a simple site that shows movies and going to work on it much more and created the release just right now.

### Version

1.0

### Date

December 3 2021

### Description of changes

Initial Release

### GitHub Repo

https://github.com/codewithpom/moviez

### Website

http://moviez-nu.vercel.app/

### Link to changelog

https://github.com/codewithpom/moviez/releases/tag/v1.0

### Social media

not yet

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the December 2021 Release Radar and we couldn't include them all. Please submit your project again for consideration when you have another major version release and we'd love to consider your project.
