### ISSUE TITLE
[Release Radar Request] humble 1.23

### ISSUE THREAD

**Issue by rfc-st** [github/release-radar#170]
### Open Source Project name

humble

### What is your project?

A humble, and **fast**, security-oriented HTTP headers analyzer.

### Version

1.23

### Date

April 30, 2023

### Description of breaking changes

* New parameter ('-a')!: Showing statistics of scans performed against a URL.
* 8 new fingerprint headers.
* Earlier versions were accepted in Kali Linux (https://pkg.kali.org/pkg/humble) and OWASP (https://owasp.org/www-project-secure-headers/#div-technical)!.

### GitHub Repo

https://github.com/rfc-st/humble/

### Website

https://github.com/rfc-st/humble/

### Link to changelog

https://github.com/rfc-st/humble/releases/tag/1.23

### Social media

https://www.linkedin.com/feed/update/urn:li:activity:7058451454767902720/

### Anything else to add?

Humble and small projects, which have the **same** illusion as the great figures, also deserve a chance to be known! :).

Thank you!.

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 2.0 and we'd love to consider your project for feature 😄
