### ISSUE TITLE
[RR Request]: fipv v1.0.0

### ISSUE THREAD

**Issue by eredotpkfr** [github/release-radar#171]
### Open Source Project name

fipv

### What is your project?

`fipv` (fast ip validator) is a python package build with `C` language. Simply it includes basic IP address validator functions as a `C` function, so works faster than others.

### Version

1.0.0

### Date

May 7, 2023

### Added
- Added project documentation page on github pages.
- New python version tests.

### Changed
- Minimum required python version upgraded to `3.9`.
- Make compatiable for new python versions.

### GitHub Repo

https://github.com/eredotpkfr/fipv

### Website

https://www.erdoganyoksul.com/fipv/

### Link to changelog

https://github.com/eredotpkfr/fipv/blob/main/CHANGELOG.md

### Social media

https://twitter.com/eredot_pkfr/status/1655227141494013957

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for our latest Release Radar and we couldn't include them all. Please submit your project again for consideration when you have version 2.0.
