### ISSUE TITLE
[RR Request]: NUKE 7.0

### ISSUE THREAD

**Issue by matkoch** [github/release-radar#172]
### Open Source Project name

NUKE

### What is your project?

NUKE brings your build automation to an even level with every other .NET project. How? It's a regular console application allowing all the OOP goodness! Besides, it solves many common problems in build automation, like parameter injection, path separator abstraction, access to solution and project models, and build step sharing across repositories. NUKE can also generate CI/CD configurations (YAML, etc.) that automatically parallelize build steps on multiple agents to optimize throughput!

### Version

7.0.0

### Date

6.5.2023

### Description of breaking changes

In the latest release, `Nuke.Common` was split into multiple packages, allowing more fine-grained references and easier updates on our side.

### GitHub Repo

https://github.com/nuke-build/nuke

### Website

https://nuke.build

### Link to changelog

https://github.com/nuke-build/nuke/blob/develop/CHANGELOG.md

### Social media

https://twitter.com/nukebuildnet

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.

**Comment by matkoch** [comment]
Thank you!
