### ISSUE TITLE
[Release Radar Request] Yachay AI Geotagging Model v1.0.0

### ISSUE THREAD

**Issue by ingakaspar** [github/release-radar#173]
### Open Source Project name

Yachay AI

### What is your project?

We built an NLP model that predicts coordinates from text only. Yachay is building a community of Deep Learning developers to advance the intersection of Geospatial field and NLP through improved research and open-source solutions.

### Version

V1.0.0

### Date

June 11, 2023

### Description of breaking changes

- Implemented a new architecture combining a ByT5 encoder and confidence-based prediction.
- Achieved a median average deviation of 19.22 km and a mean average deviation of 434.16 km for the top 10% of samples by confidence, indicating enhanced precision in geotagging predictions.
- Introduced two curated datasets for geotagging model training and validation and added comprehensive documentation for ease of use and understanding.

### GitHub Repo

https://github.com/Yachay-AI/byt5-geotagging

### Website

https://www.yachay.ai/

### Link to changelog

https://github.com/Yachay-AI/byt5-geotagging/releases/tag/v1.0.0

### Social media

https://twitter.com/YachayAi/status/1668235949137096704?s=20

### Anything else to add?

We are also [visualizing the application of the text-to-location models](https://github.com/Yachay-AI/use-cases) ,  you can check thorough analysis on our twitter.

For instance! We predicted coordinates for social media posts that mention Git services in India: https://yachay-ai.github.io/use-cases/git/

Our team achieved breaking results in validation metrics, resulting in significantly reduced distance errors for improved geolocation accuracy. So we are sharing the model architecture and datasets with geospatial community. Application of the models can be numerous like social media analysis, emergency response, urban planning, tourism and travel, environmental studies, market research, etc.

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.
