### ISSUE TITLE
[Release Radar Request] Major Release Zammad

### ISSUE THREAD

**Issue by JuliaDenise** [github/release-radar#174]
### Open Source Project name

Zammad

### What is your project?

Zammad is a web based open source helpdesk/customer support system. It helps the support team to manage customer issues and reports from several channels like phone, Facebook, emails, Twitter and chat.

### Version

6.0

### Date

June 6, 2023

### Description of breaking changes

The latest changes includes Mobile View, Duplicate Detection, MS Teams Integration and further enhancements.

### GitHub Repo

https://github.com/zammad/zammad

### Website

https://zammad.org

### Link to changelog

https://github.com/zammad/zammad/blob/6.0.0/CHANGELOG.md

### Social media

https://twitter.com/zammadhq/status/1666046874833367096

### Anything else to add?

Image of Zammad on mobile device
![Mobile View](https://github.com/github/release-radar/assets/132340206/c8111760-bf39-4783-b854-11b1f25a7c34)

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.
