### ISSUE TITLE
[RR Request]: VineJS@1

### ISSUE THREAD

**Issue by thetutlage** [github/release-radar#175]
### Open Source Project name

VineJS

### What is your project?

VineJS is a highly performant and type-safe validation library for Node.js.

### Version

1.0

### Date

June 16th, 2023

### Description of breaking changes

Nil

### GitHub Repo

https://github.com/vinejs/vine

### Website

https://vinejs.dev/

### Link to changelog

https://github.com/vinejs/vine/releases

### Social media

https://twitter.com/AmanVirk1/status/1669575264328732675

**Comment by Roseydog67** [comment]
> ### Open Source Project name
> VineJS
> 
> ### What is your project?
> VineJS is a highly performant and type-safe validation library for Node.js.
> 
> ### Version
> 1.0
> 
> ### Date
> June 16th, 2023
> 
> ### Description of breaking changes
> Nil
> 
> ### GitHub Repo
> https://github.com/vinejs/vine
> 
> ### Website
> https://vinejs.dev/
> 
> ### Link to changelog
> https://github.com/vinejs/vine/releases
> 
> ### Social media
> https://twitter.com/AmanVirk1/status/1669575264328732675
> 
> ### Anything else to add?
> _No response_

> https://github.com/github/release-radar/issues/175#issue-1761652992

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.

**Comment by thetutlage** [comment]
@mishmanners 

Thanks a ton for considering VineJS :)
