### ISSUE TITLE
[RR Request]: JSON Crack v3.0.0

### ISSUE THREAD

**Issue by AykutSarac** [github/release-radar#176]
### Open Source Project name

JSON Crack

### What is your project?

JSON Crack is a visualization tool for JSON, YAML, XML and couple more data types converting them into interactive graphs. It helps you to understand and explore data very quickly with the use of handy tools.

### Version

3.0

### Date

June 18, 2023

### Description of breaking changes

* New UI
* Many new features since the last major release
* Account & Cloud functions

### GitHub Repo

https://github.com/AykutSarac/jsoncrack.com

### Website

https://jsoncrack.com/

### Link to changelog

https://github.com/AykutSarac/jsoncrack.com/releases/tag/v3.0.0

### Social media

https://twitter.com/jsoncrack/status/1670369114236280832

**Comment by mishmanners** [comment]
Thanks so much for submitting! We loved your project and it was [featured in our Spring Release Radar edition](https://github.blog/2023-07-13-release-radar-spring-23/) which is a round up of projects submitted between March and July. We hope you enjoyed some promo and we wish you all the best with the project.
