### ISSUE TITLE
[Release Radar Request] <Connected Spaces Platform>

### ISSUE THREAD

**Issue by marketingmagnopus** [github/release-radar#177]
### Open Source Project name

Connected Spaces Platform

### What is your project?

We take it as given that users expect to interact with the next internet across a wide range of hardware and software interfaces, including mobile devices, head-mounted displays, desktops, and laptops. That’s why we’ve built the Connected Spaces Platform (CSP), to enable the interoperability and accessibility of cross-reality spaces. It defines a protocol for different applications to transact data in real-time, whether written using C#, C++, or Javascript. Users can move between physical, augmented, and virtual spaces, with persistence and sync. We’ve open-sourced our code so anyone can contribute to it, and use it for their own connected space projects

### Version

4.4.0

### Date

July 25 2023

### Description of breaking changes

Nil

### GitHub Repo

https://github.com/magnopus-opensource/connected-spaces-platform 

### Website

www.magnopus.com/csp

### Link to changelog

https://www.magnopus.com/blog/open-sourcing-our-connected-spaces-platform

### Social media

https://www.linkedin.com/feed/update/urn:li:activity:7089588149269450752

### Anything else to add?

We really hope you can support this launch, it would mean a lot to the team! Please let us know if there is anything else we can share with you!
Twitter [HERE](https://twitter.com/magnopus/status/1683823355302912000?s=20). 
Facebook [HERE](https://www.facebook.com/MagnopusINC/posts/798247598968363).

**Comment by mishmanners** [comment]
Thanks so much for submitting this @marketingmagnopus. We take Major project releases for the release radar, so it'd be great if you can submit when you have version 5.0 😄 we'd love to feature it.

**Comment by marketingmagnopus** [comment]
Hi @mishmanners - Although this release is labeled 4.4.0, it is our first public release of this repo so technically a 'major' release!
