### ISSUE TITLE
[RR Request]: Front Matter CMS - Version 9.0.0

### ISSUE THREAD

**Issue by estruyf** [github/release-radar#178]
### Open Source Project name

Front Matter CMS

### What is your project?

Experience the best of both worlds with Front Matter, the CMS that runs within Visual Studio Code, GitPod, and many more. Get the control over your static generator's content by bringing in the CMS features from Front Matter. Start creating and previewing content in real-time - no complicated setup - choose Front Matter CMS and start creating amazing content today.

### Version

9.0.0

### Date

August 21, 2023

### Description of breaking changes

Front Matter CMS is now available in English, German, and Japanese. We are still looking to support other languages which Visual Studio Code supports.

We've put the Visual Studio Code theme support out of experimental mode, which means that the UI of our CMS will now adapt to the used theme in VSCode.

Support for Astro new assets location has been added.

More UI extensibility options with our extensibility library: https://www.npmjs.com/package/@frontmatter/extensibility

### GitHub Repo

https://github.com/estruyf/vscode-front-matter

### Website

https://frontmatter.codes

### Link to changelog

https://frontmatter.codes/updates/v9.0.0

### Social media

https://twitter.com/frontmattercms/status/1693564998088319474?s=20

### Anything else to add?

Would be cool to highlight Front Matter CMS again in your show 🙏

**Comment by mishmanners** [comment]
Congrats on being featured in the August-September, Hacktoberfest Release Radar Special 🥳

- Read the blog [here](https://github.blog/2023-10-30-release-radar-hack-23/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1719236745458557018)
