### ISSUE TITLE
[Release Radar Request] Open Props just announced v1 🎉 

### ISSUE THREAD

**Issue by argyleink** [github/release-radar#18]
### Open Source Project name

Open Props

### What is your project?

350 free CSS custom properties to help accelerate adaptive and consistent design: 
aka, free expertly crafted web design tokens.

### Version

1.0.0

### Date

December 1, 2021

### Description of changes

nil

### GitHub Repo

https://github.com/argyleink/open-props

### Website

https://open-props.style/

### Link to changelog

https://github.com/argyleink/open-props/releases/tag/v1.0.0

### Social media

https://twitter.com/argyleink/status/1466086683577700352?s=20

### Anything else to add?

Thanks for considering it!

**Comment by mishmanners** [comment]
Congrats on being featured in the December Release Radar 🥳 
- [Read the blog here](https://github.blog/2022-01-21-release-radar-dec-2021/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1484671401659359235)
- [Feel free to retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1485499076775137280)

Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github/videos) for a December Release Radar promo video 😄
