### ISSUE TITLE
[RR Request]: framework-x v4.0

### ISSUE THREAD

**Issue by msamgan** [github/release-radar#180]
### Open Source Project name

3rd planets's framework x

### What is your project?

framework x is  all about substance over style! 3rd Planet's Framework X is like a well-oiled machine for API development, powered by Node.js and Express. It's all about getting the job done efficiently and effortlessly. No flashy gimmicks, just pure development bliss.

### Version

4.0

### Date

August 10th, 2023

### Description of breaking changes

nill

### GitHub Repo

https://github.com/3rd-planet/framework-x

### Website

https://3rd-planet.github.io/framework-x/

### Link to changelog

https://github.com/3rd-planet/framework-x/compare/v3.6.1...v4.0.0

### Social media

https://twitter.com/msamgank/status/1690054063293898760

**Comment by mishmanners** [comment]
Congrats on being featured in the August-September, Hacktoberfest Release Radar Special 🥳

- Read the blog [here](https://github.blog/2023-10-30-release-radar-hack-23/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1719236745458557018)
