### ISSUE TITLE
[RR Request]: Snippets — Supercharge Snippets in VS Code v3.1.0

### ISSUE THREAD

**Issue by tahabasri** [github/release-radar#181]
### Open Source Project name

Snippets — Supercharge Snippets in VS Code

### What is your project?

Code snippets are valuable additions for anyone looking to save time during development. They simplify the process of entering repetitive code, such as loops, complex HTML structures or reusable methods.

VS Code already provides robust support for snippets, including integration with IntelliSense, tab-completion, and a dedicated snippet picker. This extension takes snippets to another level by introducing new features that enhance code snippet management.

### Version

3.1.0

### Date

September 14, 2023

### Description of breaking changes

**The best Snippets tool for VS Code, just got better 🎉**

### Support for Programming Languages
Most requested feature has been added to Snippets ✅ **You can now create language-specific snippet.**

Snippets created from a language-specific editor/file will keep reference of the programming language used. The same Snippet will be suggested only in editors/files of same programming language.

> A Snippet bound to a programming language will get an icon for that particular language natively.

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/038-language-scope.gif" 
alt="Bind Snippets to Languages">

You can explicitly set a programming language by appending the language file extension to the Snippet name at the creation prompt.

<img src="https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/038-language-scope-by-name.gif" 
alt="Manually Bind Snippets to Languages">

### Other major changes
- Sort Snippets alphabetically.
- New command for Troubleshooting Snippets.
- Support for folder icons.
- Support for Drag and Drop into active editor.
- Additional bug fixes.

### GitHub Repo

https://github.com/tahabasri/snippets

### Website

https://tahabasri.com/

### Link to changelog

https://github.com/tahabasri/snippets/releases/tag/3.1.0

### Social media

https://www.linkedin.com/feed/update/urn:li:activity:7108093536582938624/

### Anything else to add?

Snippets is used by more than 23k users ✅ Check the [full list](https://github.com/tahabasri/snippets/blob/main/README.md) of the amazing features it offers.

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 4.0 and we'd love to consider your project for feature 😄
