### ISSUE TITLE
[RR Request]: OpenObserve v0.6.4 

### ISSUE THREAD

**Issue by prabhatsharma** [github/release-radar#185]
### Open Source Project name

OpenObserve

### What is your project?

OpenObserve is a cloud native observability platform built specifically for logs, metrics, traces and analytics designed to work at petabyte scale.

It is very simple and easy to operate as opposed to Elasticsearch which requires a couple dozen knobs to understand and tune which you can get up and running in under 2 minutes.

It is a drop-in replacement for Elasticsearch if you are just ingesting data using APIs and searching using kibana (Kibana is not supported nor required with OpenObserve. OpenObserve provides its own UI which does not require separate installation unlike kibana).

You can reduce your log storage costs by ~140x compared to Elasticsearch by using OpenObserve. Below are the results when we pushed logs from our production kubernetes cluster to Elasticsearch and OpenObserve using fluentbit. OpenObserve stored data in Amazon s3 and Elasticsearch stored data on Amazon EBS volumes.

### Version

v0.6.4

### Date

Oct 1st, 2023

### Description of breaking changes

Migration from sled db to sqlite for local mode metadata and fie list storage (auto migration included)
Availability of MySQL, Postgres and DynamoDB for metadata and file list storage for distributed mode

### GitHub Repo

https://github.com/openobserve/openobserve

### Website

https://openobserve.ai/

### Link to changelog

https://github.com/openobserve/openobserve/releases/tag/v0.6.4

### Social media

https://twitter.com/OpenObserve/status/1708675882980958504

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
