### ISSUE TITLE
[RR Request]: CLI for Microsoft 365 v7

### ISSUE THREAD

**Issue by Adam-it** [github/release-radar#186]
### Open Source Project name

CLI for Microsoft 365

### What is your project?

Using the CLI for Microsoft 365, you can manage your Microsoft 365 tenant and SharePoint Framework projects on any platform. No matter if you are on Windows, macOS or Linux, using Bash, Cmder or PowerShell, using the CLI for Microsoft 365 you can configure Microsoft 365, manage SharePoint Framework projects and build automation scripts.
CLI for Microsoft 365 is a [Microsoft 365 Platform Community](https://pnp.github.io/) (PnP) project. Microsoft 365 Platform Community is a virtual team consisting of Microsoft employees and community members focused on helping the community make the best use of Microsoft products.

### Version

7.0

### Date

1.10.2023

### Description of breaking changes

😍 **huge stuff (breaking changes)** :
👉 interactive by default 🚀. This means CLI will ask the user with a prompt for any missing required option, or to select one of the required options and even will ask to select a single value when multiple were found and a single was expected. This is awesome (IMO 😜) check it out (till now user had to type the exact command and be sure to specify all required options)
![cli-interactivity](https://github.com/github/release-radar/assets/58668583/50b7d1fe-2f9e-4ec7-9249-97a5db6c2282)
👉 we refactored our code base (sick PR, over 2k files changed) and moved to using ECMAScript Modules (ESM) instead of CommonJS modules. This is huge as CLI for M365 is not only a CLI tool but may also be used programmatically as a single API to everything around Microsoft 365 (for example other products base on it like [VS Code extension Viva Connections Toolkit](https://marketplace.visualstudio.com/items?itemName=m365pnp.viva-connections-toolkit). In this case, if CLI npm packages are used in some Node.js app then this app also needs to be refactored to ESM.

🤷 **small stuff (breaking changes)**:
👉 we have renamed the option `--confirm` to `--force` in all commands. This change aims to be more consistent with other CLI tools where `--force` is used to suppress prompts.
👉 bunch of command and options renaming 
👉 updated some commands output 

checkout the link to upgrade guidance to help folks update scripts from v6 to v7 
https://pnp.github.io/cli-microsoft365/v7-upgrade-guidance

📝link to the release blog post which also covers most of the stuff: 
https://pnp.github.io/blog/cli-for-microsoft-365/cli-for-microsoft-365-v7-0/

### GitHub Repo

https://github.com/pnp/cli-microsoft365

### Website

https://pnp.github.io/cli-microsoft365/

### Link to changelog

https://pnp.github.io/cli-microsoft365/about/release-notes#v700

### Social media

https://twitter.com/climicrosoft365/status/1708798784149352784

### Anything else to add?

Of course, You Rock 🤩.

I know I have already written to much but just wanted to point out some awesome milestoned we did/had along this awesome (and veeery long) year full of work on the product:
👉 we migrated our docs to Docusaurus 🦖 and we introduced AI based search, to give direct answer to a prompt, on the page powered by Mendable
👉 we had one month with over 100 PR opened created by contributors outside of the maintainers team 🤯. Even as I write we have 77 (lucky seven 😜) PRs opened. This is awesome for us to see how the open source community actually creates this product 👍
👉 to keep up to date with our community we created a Discord Server to be in constant contact with our community and contributors: https://aka.ms/cli-m365/discord. We have a help section, announcements... etc and we even did our first time office hours to meet our contributors 'face to face' (screen to screen 😋)
👉 we introduced a AI based command which we call CLI assistant (chili 🌶️ ). Directly in any consol shell users may ask prompts regarding CLI for M365 to get for example a command which will execute and output what they ask for. Check it out: https://pnp.github.io/cli-microsoft365/user-guide/chili
👉 since the last release (v6) we added 129 new commands 🤯 to help manage almost any area of Micorosft 365 (SharePoint, Power Platfrom, Planner.... etc or manage your SPFx projects). For example we added a command that generates a CI/CD GitHub workflow for your SPFx project 😉 https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-github-workflow-add
👉... I could gooo on forever 😜. give it a check

**Comment by mishmanners** [comment]
This is so awesome. You've done so much stuff!

**Comment by mishmanners** [comment]
Congrats on being featured in the MONTHOF Release Radar 🥳

- Read the blog [here](https://github.blog/2023-12-19-release-radar-dec-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1737873817056276729)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1744503149162115110)
