### ISSUE TITLE
Error in description of OpenAPI in last RR 

### ISSUE THREAD

**Issue by skagedal** [github/release-radar#188]
Hello! The [last RR](https://github.blog/2023-10-30-release-radar-hack-23/) contains this paragraph:

> There’s a lot of buzz around generative artificial intelligence (AI) and open source APIs. [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) is one such project.

[openapi-generator](https://github.com/OpenAPITools/openapi-generator) is about [OpenAPI](https://www.openapis.org/). It has nothing at all to do with generative artificial intelligence. I'm guessing this might be a mix-up with [OpenAI](https://openai.com/)? 

Anyway, I thought that might be worth correcting. Thanks for the blog!

**Comment by mishmanners** [comment]
Thanks for pointing this out.
