### ISSUE TITLE
[RR Request]: Cake 2.0.0

### ISSUE THREAD

**Issue by pascalberger** [github/release-radar#19]
### Open Source Project name

Cake

### What is your project?

Cake (C# Make) is a free and open source cross-platform build automation system with a C# DSL for tasks such as compiling code, copying files and folders, running unit tests, compressing files and building NuGet packages.

### Version

2.0.0

### Date

November 30, 2021

### Description of changes

C# 10 & .NET 6 support
Improved dotnet CLI support
Improved GitHub Actions integration
Improved Azure Pipelines integration
Refactored docker images

### GitHub Repo

https://github.com/cake-build

### Website

https://cakebuild.net

### Link to changelog

https://cakebuild.net/blog/2021/11/cake-v2.0.0-released

### Social media

https://twitter.com/cakebuildnet/status/1465726209673814016

**Comment by mishmanners** [comment]
November 30 is 1st December here, so I can get it into the December Release Radar based on Australian times 😄

**Comment by mishmanners** [comment]
Congrats on being featured in the December Release Radar 🥳 
- [Read the blog here](https://github.blog/2022-01-21-release-radar-dec-2021/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1484671401659359235)
- [Feel free to retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1485499076775137280)

Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github/videos) for a December Release Radar promo video 😄
