### ISSUE TITLE
[RR Request]: Rowy v3.0

### ISSUE THREAD

**Issue by harinij** [github/release-radar#190]
### Open Source Project name

Rowy

### What is your project?

Rowy is low-code backend platform for building and managing a database on spreadsheet like UI. You can also extend it beyond a database to visually build your backend cloud functions and logic right from the browser with AI - create powerful API, scheduled jobs and backend tasks with no code using [BuildShip](https://buildship.com/).

### Version

3.0

### Date

October 28. 2023

### Description of breaking changes

nil

### GitHub Repo

https://github.com/rowyio/rowy

### Website

https://www.rowy.io

### Link to changelog

https://github.com/rowyio/rowy/releases/tag/v3.0.0

### Social media

https://twitter.com/rowyio/status/1717964335774142844?s=20

**Comment by mishmanners** [comment]
Congrats on being featured in the December 2023 Release Radar 🥳

- Read the blog [here](https://github.blog/2023-12-19-release-radar-dec-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1737873817056276729)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1744503149162115110)
