### ISSUE TITLE
[Release Radar Request] Dependabot Changelog Helper v3.7.0

### ISSUE THREAD

**Issue by dangoslen** [github/release-radar#191]
### Open Source Project name

Dependabot Changelog Helper

### What is your project?

Automatically update your changelog on Dependabot pull requests! No more manually updating a changelog for dependency upgrades. Just fast and easy dependency upgrades.

### Version

v3.7.0

### Date

November 27th 2023

### Description of breaking changes

Now supports [Dependabot multi-package updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups). Each dependency upgrade will form a new line under the configured [section](https://github.com/dangoslen/dependabot-changelog-helper/blob/v3.7.0/README.md#sectionheader) as if the upgrade was from it's own pull request.

### GitHub Repo

https://github.com/dangoslen/dependabot-changelog-helper

### Website

N/A

### Link to changelog

https://github.com/dangoslen/dependabot-changelog-helper/releases/tag/v3.7.0

### Social media

N/A

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 4.0 and we'd love to consider your project for feature 😄
