### ISSUE TITLE
[Release Radar Request] simple-data-analysis@2.0

### ISSUE THREAD

**Issue by nshiab** [github/release-radar#192]
### Open Source Project name

simple-data-analysis

### What is your project?

I created simple-data-analysis because, as a computational journalist, I needed an easy-to-use JavaScript library for my data analysis. My projects are published on our website, and I wanted to do as much as possible with one language instead of switching between Python, R, and JavaScript all the time. But all of the great data analysis libraries were in different languages, like Pandas with Python and the Tidyverse with R. So I created this library about a year and a half ago and haven't stopped using it since!

### Version

2.0

### Date

November 30, 2023

### Description of breaking changes

To increase the library's performance, I had to rewrite it completely. Under the hood, it now uses [DuckDB](https://github.com/duckdb/duckdb). And it worked! In my tests, which you can see in [the repo](https://github.com/nshiab/simple-data-analysist), the library now runs six times faster than before. Also, I took the time to document each class and related methods with examples.

### GitHub Repo

https://github.com/nshiab/simple-data-analysis

### Website

https://nshiab.github.io/simple-data-analysis/

### Link to changelog

https://github.com/nshiab/simple-data-analysis

### Social media

https://twitter.com/NaelShiab/status/1730327428059250884

### Anything else to add?

Thanks! :)

**Comment by mishmanners** [comment]
Congrats on being featured in the December 2023 Release Radar 🥳

- Read the blog [here](https://github.blog/2023-12-19-release-radar-dec-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1737873817056276729)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1744503149162115110)

**Comment by nshiab** [comment]
Thanks @mishmanners !
