### ISSUE TITLE
[Release Radar Request] raylib 5.0

### ISSUE THREAD

**Issue by raysan5** [github/release-radar#193]
### Open Source Project name

raylib

### What is your project?

raylib is a simple and easy-to-use library to enjoy videogames programming.

### Version

5.0

### Date

November 18, 2023

### Description of breaking changes

rcore module has been split per-platform/backend, simplifying the task to add new platforms/backend support to the library. As a prof-of-concept, support for SDL and Nintendo Switch has been added.

### GitHub Repo

https://github.com/raysan5/raylib

### Website

https://www.raylib.com/

### Link to changelog

https://github.com/raysan5/raylib/releases/tag/5.0

### Social media

https://twitter.com/raysan5/status/1725851421327655389

### Anything else to add?

It's the 10th year anniversary of raylib!

**Comment by mishmanners** [comment]
Thanks for this - we already had you down anyway 😉 the blog post will be published tomorrow 😄

**Comment by mishmanners** [comment]
Congrats on being featured in the December 2023 Release Radar 🥳

- Read the blog [here](https://github.blog/2023-12-19-release-radar-dec-2023/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1737873817056276729)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1744503149162115110)

**Comment by raysan5** [comment]
@mishmanners Thank you very much for featuring `raylib 5.0` on Release Radar! 😄
