### ISSUE TITLE
[RR Request]:HistoJS v1.0.0

### ISSUE THREAD

**Issue by Mmasoud1** [github/release-radar#194]
### Open Source Project name

HistoJS

### What is your project?

**HistoJS** is a new web-based interactive tool designed to overcome the challenges of using highly-multiplexed immunofluorescence (HMIF) images for spatial biology research. HistoJS provides open-source and extensible tools for analyzing spatial-molecular patterns, offering a deeper understanding of single-cell spatial relationships. It also features machine learning algorithms in a user-friendly interactive interface for the biomedical community.

### Version

1.0.0

### Date

12/31/2023

### Description of breaking changes

- Support for accessing and managing Digital Slide Archive (DSA), including hosted immunofluorescence image data and meta-data.
- Navigation of OME-TIFF datasets on DSA.
- Visualization of immunofluorescence images, including channel grouping for further analysis.
- Real-time image processing and analysis, covering tasks such as cell segmentation, phenotyping, classification, correlations, spatial analysis, and quantification of cell types to unveil cell interactions.
- Detection of cell neighbors with spatial plotting and analysis using Delaunay neighborhood graphs.
- Interactive features facilitating the identification of disease-specific signatures, offering valuable insights into the molecular basis of diseases.

### GitHub Repo

https://github.com/Mmasoud1/HistoJS

### Website

https://mmasoud1.github.io/HistoJS/

### Link to changelog

https://github.com/Mmasoud1/HistoJS/releases/tag/v1.0.0

### Social media

https://twitter.com/MMasoud2021

### Anything else to add?

This is the first release of HistoJS 
![image](https://github.com/github/release-radar/assets/36082112/265313c1-c911-4ad0-a0e7-d5cf9d65ac60)

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2024-02-02-release-radar-jan-2024/)
- [Check out our GitHub Tweet](https://twitter.com/GitHubEducation/status/1755272652430733367)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1753370157718593741)
