### ISSUE TITLE
[RR Request]: OpenTofu v1.6.0

### ISSUE THREAD

**Issue by cube2222** [github/release-radar#196]
### Open Source Project name

OpenTofu

### What is your project?

OpenTofu is an OSS tool for building, changing, and versioning infrastructure safely and efficiently. It's the open-source fork of Terraform.

### Version

v1.6.0

### Date

January 10, 2023

### Description of breaking changes

This is the first stable release of OpenTofu.

This version includes the [new module testing feature](https://opentofu.org/docs/cli/commands/test/), an [updated s3 backend](https://opentofu.org/docs/language/settings/backends/s3/), tons of minor improvements, bug fixes, and performance improvements. It also includes [our new registry](https://github.com/opentofu/registry).

### GitHub Repo

https://github.com/opentofu/opentofu

### Website

https://opentofu.org

### Link to changelog

https://github.com/opentofu/opentofu/releases/tag/v1.6.0

### Social media

https://x.com/OpenTofuOrg/status/1745104624808612213?s=20

### Anything else to add?

Also blog post available here: https://opentofu.org/blog/opentofu-is-going-ga/

**Comment by mishmanners** [comment]
Thanks for submitting this. We have a tonne of projects that shipped major version releases in January so we have to give preference to those. We'd love to feature this project, so please submit when you have version 1.0 and we can feature it 😄

**Comment by cube2222** [comment]
@mishmanners Hey, to be clear, this is "our" 1.0.

For most projects 1.0 is the first stable version. 

For us, since we're a fork that continues the previous versioning scheme, the 1.6.0 release **is** the first stable version of the project.

**Comment by mishmanners** [comment]
Oh that makes a lot more sense! I'll update the form for that in future. Blog post has already been sent to editors for this month though.

**Comment by mishmanners** [comment]
Oh that makes a lot more sense! I'll update the form for that in future. Blog post has already been sent to editors for this month though.

**Comment by cube2222** [comment]
Do you think we could get into next month's issue? @mishmanners

**Comment by mishmanners** [comment]
We feature the previous months releases. So the next issue will feature February releases.
