### ISSUE TITLE
[RR Request]: AdonisJS@v6

### ISSUE THREAD

**Issue by thetutlage** [github/release-radar#198]
### Open Source Project name

AdonisJS

### What is your project?

AdonisJS is a TypeScript-first web framework for building web apps and API servers. It comes with support for testing, modern tooling, an ecosystem of official packages, and more.

### Version

6.0

### Date

January 24, 2024

### Description of breaking changes

This is a major release after almost 4 years. So it's improves the framework on several fronts. Following are some of the highlights.

- Migrate to ES modules
- Rewrite the IoC container to be simple and less magical
- Type-safety in Routes and Controllers bindings
- Type-safe event emitter and environment variables.
- Changes to the default folder structure. 

### GitHub Repo

https://github.com/adonisjs/core

### Website

https://adonisjs.com

### Link to changelog

https://adonisjs.com/blog/adonisjs-v6-announcement

### Social media

https://twitter.com/adonisframework/status/1750151728408748409

**Comment by Mehdi-Azmoudeh** [comment]
Hi.. Just wanted to know if usage of TypeScript is still optional in v6 or not? Cause I have a massive codebase in v4.1 and want to move it to v6 as fast as possible. TypeScript being mandatory is a big concern right now.

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2024-02-02-release-radar-jan-2024/)
- [Check out our GitHub Tweet](https://twitter.com/GitHubEducation/status/1755272652430733367)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1753370157718593741)

**Comment by thetutlage** [comment]
Thanks for considering AdonisJS 🙏
