### ISSUE TITLE
[RR Request]: Probot v13

### ISSUE THREAD

**Issue by AaronDewes** [github/release-radar#199]
### Open Source Project name

Probot

### What is your project?

Probot is a framework for building GitHub apps. It makes building apps that integrate with GitHub and receive webhooks easy.

### Version

13.0.0

### Date

January 25, 2024

### Description of breaking changes

This major release brings Probot up-to-date with support & test for modern Node, the latest Octokit releases to allow use of the latest GitHub features, and allows writing apps in ESM.

### GitHub Repo

https://GitHub.com/probot/probot

### Website

https://probot.github.io

### Link to changelog

https://github.com/probot/probot/compare/v12.3.3...v13.0.0

### Social media

No

### Anything else to add?

@gr2m @Uzlopak  and @wolfy1339 are also probot maintainers and main contributors to this release, so I'd like to get their approval too.

**Comment by gr2m** [comment]
let's go team! Awesome to see v13 out in the wild!

**Comment by Uzlopak** [comment]
So three thumbs up => we approve it ;)

**Comment by AaronDewes** [comment]
It's already too late for a :-1:

https://github.blog/2024-02-02-release-radar-jan-2024/
