### ISSUE TITLE
[Release Radar Request] Luciferin, bias lighting and ambient light project.

### ISSUE THREAD

**Issue by sblantipodi** [github/release-radar#2]
This is the first submission so I'll try to give you some context.

### Open Source Project name

Luciferin

### What is your project?

Luciferin is a generic term for the light-emitting compound found in organisms that generate bioluminescence like Fireflies and Glow Worms. The `Luciferin` project takes its cue from this world.  
`Firefly Luciferin` is a Java Fast Screen Capture PC software designed for the `Glow Worm Luciferin` C++ Arduino firmware,
**the combination of these software create the perfect Bias Lighting and Ambient Light system for PC**.

Here two videos that shows Luciferin in action on a videogame, DooM Eternal.  

[![Luciferin YouTube Video #3](https://github.com/sblantipodi/firefly_luciferin/blob/master/data/img/doom_eternal.png?raw=true)](https://youtu.be/oiMIVGKndQs)  

and on a standard youtube video:  

[![Luciferin YouTube Video #1](https://github.com/sblantipodi/glow_worm_luciferin/blob/master/assets/img/ambilight_viddeo.jpg?raw=true)](https://youtu.be/Hd6BtPp40I0)

### Version

2.0

### Date

November 15, 2021

### Description of changes

- **Added an option menu to the [Web Interface](https://github.com/sblantipodi/firefly_luciferin/wiki/Remote-Access#luciferin-web-interface)** where you can change all firmware related settings without the needs of reflashing the microcontroller.

### GitHub Repo

https://github.com/sblantipodi/firefly_luciferin
https://github.com/sblantipodi/glow_worm_luciferin

### Website
https://github.com/sblantipodi/firefly_luciferin/wiki
https://sblantipodi.github.io/glow_worm_luciferin

### Link to changelog

https://github.com/sblantipodi/firefly_luciferin/releases/tag/v2.3.1

### Social media

https://twitter.com/sblantipodi/status/1460195000336232451

### Anything else to add?

In addition to the dynamic halo effect behind the monitor, with Luciferin you can control the LED strip behind your monitor (or whereever you want) like any normal RGB strip using a Web Interface  

![web_interface](https://user-images.githubusercontent.com/4722227/141768122-b84894a0-db80-4bc3-9709-5a47392368bb.jpg)

 or with the Home Assistant Integration  

![HA_mobile_client_screenshot](https://user-images.githubusercontent.com/4722227/141768199-ffb3e74a-4fdc-4216-a6b8-412c4a5630bc.jpg)

Firefly Luciferin PC software gives you more control over all the features  
 
![settings_screen](https://github.com/sblantipodi/firefly_luciferin/blob/master/data/img/settings_screen.png?raw=true)  

There are a lot of light effects and a music mode:  

<img align="center" width="450" src="https://github.com/sblantipodi/firefly_luciferin/blob/master/data/img/effects.jpg?raw=true">

Firefly Luciferin PC software is a very optimized software and it has nearly no impact on your system performance, it's written in Java but thanks to JNA it has access to the OS API that uses GPU hardware acceleration.

<img width="600" src="https://raw.githubusercontent.com/sblantipodi/firefly_luciferin/dhcp/data/img/info_screen.png">

--- 

This is the simple circuit to create the hardware needed for Luciferin.  
Basically you need an Arduino (ESP8266 or ESP32), a LED strip, some resistors and capacitors and a logic level converter.  

![ambilight_bb](https://user-images.githubusercontent.com/4722227/141768506-10b60d8c-e4f4-4cbd-a8ef-4d7bfbf497aa.png)  

for people who are not able to create a circuit, I released a Gerber file, the gerber file is a file that you can "print" using your favourite PCB Fabrication Manufacturer. In this way you don't need to do all the traces in the circuit.  

![pre_after](https://user-images.githubusercontent.com/4722227/141768800-55b9fc7c-fea7-4628-9a22-41889f2d7906.jpg)  

the PC software, the firmware and the Gerber files for the PCBs are all open source on the github repo.
there is even a complete wiki to getting started here:
https://github.com/sblantipodi/firefly_luciferin/wiki

Firefly Luciferin PC software can run on Windows and Linux, macOS version is coming when it's ready.

**Comment by mishmanners** [comment]
Amazing! This is awesome and very comprehensive! Thank you ❤️

**Comment by sblantipodi** [comment]
added some more infos and screenshots of the PC software.  
thank you for creating such a great community Mish!

**Comment by mishmanners** [comment]
Can you please @ me when you've got the next big version of this. Would love to feature it but we have too many others with major changes that were done in November. I would especially love to release it when you have the macOS version available since a lot of our readers will love that!

**Comment by sblantipodi** [comment]
As you wish, mish!

Feel free to close the issue. :)

bye bye Davide

Il 01/12/2021 01:29, MishManners®™ ha scritto:

**Comment by mishmanners** [comment]
This was included in our November Release Radar 🎉 congrats
