### ISSUE TITLE
[Release Radar Request] MIllion.js 1.0.0

### ISSUE THREAD

**Issue by aidenybai** [github/release-radar#20]
### Open Source Project name

Million.js

### What is your project?

<1kb compiler-augmented virtual DOM. It's fast!

### Version

1.0.0

### Date

November 29, 2021

### Description of changes

Added new composable API and improved the `childrenDriver`, revamped benchmarks speed test site. Improved documentation to be more beginner friendly and centralize all assets.

### GitHub Repo

https://github.com/aidenybai/million

### Website

https://million.js.org

### Link to changelog

https://github.com/aidenybai/million/releases/tag/v1.0.0

### Social media

https://dev.to/aidenybai/millionjs-100-release-3pna

### Anything else to add?

Video: https://www.youtube.com/watch?v=dAHD-k0zSuo

**Comment by mishmanners** [comment]
This is awesome! Sorry we couldn't include it in the November Release Radar as that had already shipped. Please definitely submit again for v2.0 and we'd love to include it 😄
