### ISSUE TITLE
[RR Request]: Papermark v0.9.0

### ISSUE THREAD

**Issue by mfts** [github/release-radar#200]
### Open Source Project name

Papermark

### What is your project?

Papermark is the open-source DocSend alternative with real-time engagement analytics and fully customizable including custom domains, custom branding, and custom metatags.

### Version

v0.9.0

### Date

February 1, 2024

### Description of breaking changes

This is the first named release of Papermark, which is still pretty big because now Papermark is 100% white-label. This means document senders can add their own custom domain, their own logo and brand color as well as custom metatags (title, description, image) for each shared link. 

Viewers of documents through the shared links will only engage with the brand of the sender. 

Furthermore, we added gravatar support to show the user images of viewers based on their Gravatar image.

![Gravatar support](https://github.com/github/release-radar/assets/4049052/41dbddf8-2e0e-495e-833f-f1e0bd44ac12)

### GitHub Repo

https://github.com/mfts/papermark

### Website

https://www.papermark.io

### Link to changelog

https://github.com/mfts/papermark/releases/tag/v0.9.0

### Social media

https://twitter.com/papermarkio/status/1752984941418467765?s=20

### Anything else to add?

This is actually the first ever named release of Papermark. Plus a big milestone in becoming 100% white-label solution.

**Comment by mishmanners** [comment]
Thanks for submitting this. We have a tonne of projects that shipped major version releases in January so we have to give preference to those. We'd love to feature this project, so please submit when you have version 1.0 and we can feature it 😄
