### ISSUE TITLE
[Release Radar Request] PacketFence

### ISSUE THREAD

**Issue by satkunas** [github/release-radar#201]
### Open Source Project name

PacketFence

### What is your project?

PacketFence is a [fully supported](https://www.packetfence.org/support.html#/commercial), trusted, Free and Open Source network access control (NAC) solution. Boasting an impressive feature set including a captive-portal for registration and remediation, centralized wired, wireless and VPN management, industry-leading BYOD capabilities, 802.1X and RBAC support, integrated network anomaly detection with layer-2 isolation of problematic devices; PacketFence can be used to effectively secure small to very large heterogeneous networks.

### Version

13.1

### Date

January 17, 2024

### Description of breaking changes

**New Features**

- New NTLM authentication service (no more domain joins, Cloud-ready)
- Added ACL precreation for individual and all switches (#7936)
- Integrated Apache Kafka for flows reporting
- Rewrote pfqueue in Go language

**Enhancements**

- RADIUS proxy configuration documentation and examples
- Node import supports IPv4 address (#7808)
- Added TCP flags parameter from role configuration in ACL for Cisco
- Added documentation for Azure AD EAP-TLS machine authentication
- Reuse the websocket buffer to reduce memory usage.
- Force mechanism LOGIN PLAIN for SMTP (#7813)
- Use the same timezone in all Docker images (#7862)
- Integrated Fingerbank Perl client into Packet``Fence’s source code
- Added many PKI improvements (generate CSR from CA, SCEP server proxy and resign certificate)

### GitHub Repo

https://github.com/inverse-inc/packetfence

### Website

https://packetfence.org

### Link to changelog

https://github.com/inverse-inc/packetfence/compare/v13.0.0...v13.1.0

### Social media

https://twitter.com/packetfence/status/1689307403068608513

**Comment by mishmanners** [comment]
When did 13.0 release? I can't find the date in your view changes.

**Comment by satkunas** [comment]
@mishmanners yes, August 9, 2023

**Comment by mishmanners** [comment]
We featured projects that shipped major releases each month. For example, the February Release Radar will be published the first week of March, and will featured projects that shipped major releases in February. When you have version 14.0 please submit again so we can feature you 😄
