### ISSUE TITLE
[Release Radar Request] Wagtail 6.0

### ISSUE THREAD

**Issue by thibaudcolas** [github/release-radar#202]
### Open Source Project name

Wagtail

### What is your project?

Wagtail is the most popular Python CMS. It combines Django’s powerful customization capabilities with a delightful user interface.

### Version

6.0

### Date

February 7, 2024

### Description of breaking changes

Wagtail 6.0 ships with Django 5.0 support, a new searchable and filterable listing UI, the accessibility checker built into the admin interface, and a brand new 10-step tutorial for developers.

### GitHub Repo

https://github.com/wagtail/wagtail

### Website

https://wagtail.org/

### Link to changelog

https://wagtail.org/blog/wagtail-6-0/

### Social media

https://twitter.com/WagtailCMS/status/1755275592042250269

### Anything else to add?

This release marks Wagtail’s 10th birthday! On our blog, we separately reflected on [10 years of Wagtail](https://wagtail.org/blog/10-years/).

**Comment by mishmanners** [comment]
Congrats on being featured in the February Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-february-2024-edition-4i99)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1775383491880116294)
