### ISSUE TITLE
[Release Radar Request] libredwg-0.13.2

### ISSUE THREAD

**Issue by rurban** [github/release-radar#203]
### Open Source Project name

libredwg

### What is your project?

Free implementation of the DWG file format.

### Version

0.13.2

### Date

2024-02-10

### Description of breaking changes

Added pre-R13 DWG support for all old DWG formats.
Add support for VS2019 (msvc with ucrt) and clang-cl cross-compilation to Windows.
Added read support on bigendian platforms, write not yet.
Full support for en-/decoding foreign codepages, also the MIF \M=1-5xxxx format. (With and without iconv)
Added WMF and PNG support to dwgbmp

### GitHub Repo

https://github.com/LibreDWG/libredwg

### Website

https://www.gnu.org/software/libredwg/

### Link to changelog

https://github.com/LibreDWG/libredwg/releases/tag/0.13.2

### Social media

https://twitter.com/Reini_Urban/status/1756590133149598172

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄

**Comment by rurban** [comment]
0.13 was a major release, just broken.

**Comment by mishmanners** [comment]
How do you name your releases? As per the submission form, we usually go by x.0 as major releases, asking submitters if yours doesn't follow semantic versioning then you need to let us know
