### ISSUE TITLE
[Release Radar Request] Podlite markup language specification

### ISSUE THREAD

**Issue by zag** [github/release-radar#204]
### Open Source Project name

Podlite

### What is your project?

<div align="center">

![image](https://github.com/github/release-radar/assets/31441/e1bbb472-a1bc-4705-b596-d5cf8d470e03)

</div>

Podlite is a block-based markup language designed for flexibility and ease of use.

It's designed to make documentation, blogging, educational materials, and much more, a breeze to create and manage.

**Key features of Podlite include:**

* **Blocks as the basic unit:** Each document is built from blocks, which are the basic units that can have their own defined attributes.
* **Flexible linking:** Link blocks together in various relationships.
* **Formula support:** Perfect for academic and scientific documentation.
* **Markdown support:** Love Markdown? Podlite does too. It includes a standard block for Markdown, so you can switch modes seamlessly.
* **Rich content support:** Tables, images, table of contents, and all sorts of lists are all supported.
* **Extensibility:** Extend Podlite with your own custom blocks and inline codes to fit your needs

### Version

v1.0.0-beta1

### Date

Feb 4, 2024

### Description of breaking changes

-   task lists

-   intro Selectors,

-    table of contents, `=toc`,

-   include block, `=include`,

-   inserting pictures, `=picture`, `P<>`,

-   mathematical formulas, `=formula`, `F<>`,

-   Markdown support, `=markdown`

-   Emoji, `E<>`,

-   contextual backlinks, `W<>`

### GitHub Repo

https://github.com/podlite/podlite-specs

### Website

https://podlite.org/

### Link to changelog

https://github.com/podlite/podlite-specs/releases/tag/v1.0.0-beta1

### Social media

https://dev.to/zag/introducing-podlite-a-lightweight-block-based-markup-language-48n8

### Anything else to add?

thank you!

**Comment by zag** [comment]
ahh, not a major version.
thank you

**Comment by mishmanners** [comment]
Thanks @zag. This looks like such a cool project. Can't wait to see the first major version and feature it 😄
