### ISSUE TITLE
[RR Request]: <Nitric v1.0.0>

### ISSUE THREAD

**Issue by ddown24** [github/release-radar#205]
### Open Source Project name

Nitric

### What is your project?

Nitric is a multi-language framework that helps teams rapidly build cloud applications. Nitric unites backend and infrastructure code and automates the process of provisioning and deploying infrastructure. 

### Version

1.0.0

### Date

February 20, 2024

### Description of breaking changes

In v1, we’ve made significant DX improvements to the Nitric CLI to support productive cloud development, including detailed live output of what Nitric is doing for you. We also shipped new architecture visualizations to both preview infrastructure during development and see infrastructure on deployment. V1 also includes a new SDK for building and extending Nitric providers, so it’s easy to customize without getting off the upgrade path. 

### GitHub Repo

https://github.com/nitrictech/nitric

### Website

https://nitric.io

### Link to changelog

https://nitric.io/blog/v1-release 

### Social media

https://twitter.com/nitric_io/status/1760335359051735081

**Comment by ddown24** [comment]
Additional social link - https://www.linkedin.com/feed/update/urn:li:activity:7166101152034439168/
Thank you Github Release Radar team!

**Comment by mishmanners** [comment]
Congrats on being featured in the February Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-february-2024-edition-4i99)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1775383491880116294)
