### ISSUE TITLE
[Release Radar Request] Contrast v1.0 release

### ISSUE THREAD

**Issue by liamdebeasi** [github/release-radar#206]
### Open Source Project name

Contrast

### What is your project?

Contrast is a cross-platform tool that allows you to quickly know if foreground and background colors pass accessibility guidelines defined by the W3C. It reports if the colors chosen pass normal text, large text, and UI component requirements as well as what level they pass (A, AA, or AAA).

### Version

v1.0

### Date

February 26th, 2024

### Description of breaking changes

nil

### GitHub Repo

https://github.com/liamdebeasi/contrast

### Website

https://github.com/liamdebeasi/contrast

### Link to changelog

https://github.com/liamdebeasi/contrast/releases/tag/v1.0

### Social media

https://twitter.com/LiamDeBeasi/status/1762256280062746866

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the February Release Radar, as that had already been finalised. Please definitely submit again for version 2.0and we'd love to consider your project 😄

**Comment by liamdebeasi** [comment]
No problem, thanks!
