### ISSUE TITLE
[Release Radar Request] Wasp v0.12 release

### ISSUE THREAD

**Issue by matijaSos** [github/release-radar#207]
### Open Source Project name

Wasp

### What is your project?

Wasp is a full-stack web framework, built on top of React, Node.js and Prisma. It is powered by a custom-made compiler which makes it extremely flexible and made it possible to drastically reduce boilerplate code.

### Version

0.12

### Date

February 27, 2024

### Description of breaking changes

New project structure is introduced, that makes it possible to group together client and server code. Users can now use package.json as expected. New, simplified authentication model is introduced.

### GitHub Repo

https://github.com/wasp-lang/wasp

### Website

https://wasp-lang.dev/

### Link to changelog

https://github.com/wasp-lang/wasp/releases/tag/v0.12.0

### Social media

https://twitter.com/WaspLang/status/1762882925291561133

**Comment by mishmanners** [comment]
See: https://github.com/github/release-radar/issues/208
