### ISSUE TITLE
[Release Radar Request] Wasp-lang

### ISSUE THREAD

**Issue by Martinsos** [github/release-radar#208]
### Open Source Project name

Wasp

### What is your project?

Rails-like framework for React, Node.js and Prisma. Build your app in a day and deploy it with a single CLI command.

### Version

0.12

### Date

February 27, 2024

### Description of breaking changes

1. Changed the structure of Wasp project: Your code inside of Wasp is not actually a proper npm package with package.json. Also, you can now organize your code vertically, by feature, instead of the client/server/shared organization that we forced before.
2. Most of the Wasp SDK imports got rewritten, so now they are much more logical!
3. Big overhaul of the Wasp Auth: you don't have to define fields like username / pass and similar in your Prisma schema anymore, those and more are now handled by Wasp in the background. Also, Wasp Auth is now using Lucia https://github.com/lucia-auth/lucia .

### GitHub Repo

https://github.com/wasp-lang/wasp

### Website

https://wasp-lang.dev/

### Link to changelog

https://github.com/wasp-lang/wasp/releases/tag/v0.12.0

### Social media

https://twitter.com/WaspLang/status/1762882925291561133

### Anything else to add?

We are using 0.major.minor as the versioning scheme since Wasp is still in Beta, which is why 0.12.0 is a major version for us.
Although in Beta, Wasp has been used so far to create tens of thousands of apps and is growing every day!
We are not yet releasing 1.0 until we have better support for some production-level features, but will probably release 1.0 during this year.

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the February Release Radar, as that had already been finalised. Also, the Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
