### ISSUE TITLE
[RR Request]: Carapace 1.0

### ISSUE THREAD

**Issue by rsteube** [github/release-radar#210]
### Open Source Project name

Carapace

### What is your project?

A multi-shell completion **[library](https://github.com/carapace-sh/carapace)** and **[binary](https://github.com/carapace-sh/carapace-bin)**.
It enables complex argument completion consistent across every major shell and provides over [![Completers](https://carapace-sh.github.io/carapace-bin/badge.svg)](https://carapace-sh.github.io/carapace-bin/completers.html) and [![Macros](https://carapace-sh.github.io/carapace-bin/macros-badge.svg)](https://carapace-sh.github.io/carapace-bin/spec/macros.html).

### Version

1.0

### Date

March 13, 2024

### Description of breaking changes

Carapace consists of a [pflag](https://github.com/carapace-sh/carapace-pflag) fork, a yaml [spec](https://github.com/carapace-sh/carapace-spec), a shell [lexer](https://github.com/carapace-sh/carapace-shlex), a completion [bridge](https://github.com/carapace-sh/carapace-bridge) and various scrapers.
It has grown to over 13 projects so it is a good time to move them to a separate organization account.
Since this includes a change in the package name they all got a major bump to 1.0.
Apart from that the library has been fairly stable for quite a while now which also contributes to this change.

### GitHub Repo

https://github.com/carapace-sh/carapace-bin

### Website

https://carapace.sh/

### Link to changelog

https://carapace-sh.github.io/carapace-bin/release_notes/v1.0.html

### Social media

https://mastodon.social/@carapace_sh/112090531275321447

**Comment by mishmanners** [comment]
Congrats on being featured in the March Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-march-2024-edition-481i)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1778642835266478246)

**Comment by mishmanners** [comment]
Congrats on being featured in the March Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-march-2024-edition-481i)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1778642835266478246)
