### ISSUE TITLE
[RR Request]: Brainchop v3.0.0

### ISSUE THREAD

**Issue by Mmasoud1** [github/release-radar#211]
### Open Source Project name

Brainchop

### What is your project?

[Brainchop.org](brainchop.org) is a browser-based 3D MRI rendering and segmentation tool that simplifies volumetric analysis of structural MRI. It processes full brain volumes in one pass using the MeshNet segmentation model, offering extensibility via an open-source framework. Brainchop performs client-side processing, ensuring privacy, and utilizes hardware acceleration across different brands and architectures.

### Version

3.0.0

### Date

March 28, 2024

### Description of breaking changes

Brainchop can now run powerful models on weaker devices. The Brainchop Models Zoo has three classes of models, as shown in the attached gif: 

- **Flash filet** is a small, fast model that works well on data similar to HCP structural MRIs. You can find it in the menu as "Tissue GWM (light)" with a lightning bolt symbol (⚡).

- **Thin slice** models are high-quality but fragile if input T1s are highly variable. They are temporarily marked with a 🔪 icon in the menu to indicate their thin slice class.
 
- **Rough Chop** is a new model for brainchop.org. It produces reasonable results on various data types, including clinical scans and infant data. 🪓

### GitHub Repo

https://github.com/neuroneural/brainchop

### Website

brainchop.org

### Link to changelog

https://github.com/neuroneural/brainchop/releases/tag/v3.0.0

### Social media

https://twitter.com/PlisSergey/status/1773349780736876554

### Anything else to add?

![1711633478492](https://github.com/github/release-radar/assets/36082112/666697b3-0791-426e-8d4c-f7f10005dd7b)

**Comment by mishmanners** [comment]
Congrats on being featured in the March Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-march-2024-edition-481i)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1778642835266478246)

**Comment by Mmasoud1** [comment]
Thank you!
