### ISSUE TITLE
[RR Request]: ESLint v9.0.0

### ISSUE THREAD

**Issue by nzakas** [github/release-radar#212]
### Open Source Project name

ESLint

### What is your project?

ESLint helps you find and fix problems in your JavaScript. With over 120 million npm downloads each month, it is by far the most popular JavaScript linter in the world.

### Version

9.0.0

### Date

April 5, 2024

### Description of breaking changes

This version introduces a new configuration system that is designed to simplify all of the available configuration options. Old and deprecated rules have been removed, and a new configuration inspector was added.

### GitHub Repo

https://github.com/eslint/eslint

### Website

https://eslint.org

### Link to changelog

https://eslint.org/blog/2024/04/eslint-v9.0.0-released/

### Social media

https://twitter.com/geteslint/status/1776364162329035110

### Anything else to add?

ESLint has been around since 2013 and is still going strong!

**Comment by mishmanners** [comment]
Congrats on being featured: https://dev.to/github/release-radar-april-2024-edition-major-updates-from-the-open-source-community-37k1
