### ISSUE TITLE
[Release Radar Request] Spoon 11.0.0 Major Release

### ISSUE THREAD

**Issue by MartinWitt** [github/release-radar#213]
### Open Source Project name

Spoon

### What is your project?

Spoon is a metaprogramming library to analyze and transform Java source code. 🥄 is made with ❤️, 🍻 and ✨. It parses source files to build a well-designed AST with powerful analysis and transformation API.

### Version

11.0.0

### Date

5. April.2024

### Description of breaking changes

We dropped Java 11 support and our default language level is now Java 17. As we changed the modelling of receiver parameters in our AST.

### GitHub Repo

https://github.com/INRIA/spoon

### Website

https://spoon.gforge.inria.fr/

### Link to changelog

https://github.com/INRIA/spoon/releases/tag/v11.0.0

### Social media

none

**Comment by mishmanners** [comment]
Congrats on being featured: https://dev.to/github/release-radar-april-2024-edition-major-updates-from-the-open-source-community-37k1
