### ISSUE TITLE
[Release Radar Request] Podlite v1.0 released: A lightweight, block-oriented markup language designed for organizing knowledge.

### ISSUE THREAD

**Issue by zag** [github/release-radar#214]
### Open Source Project name

Podlite markup language

### What is your project?

[Podlite](https://podlite.org), a lightweight block-oriented markup language that's all about flexibility and ease of use. 

* Unbound by any specific domain, programming language, or concept, Podlite stands out as a universal markup language

* In addition, the support for Markdown markup as a standard block adds convenience and allows for the use of familiar syntax for text formatting

* It's perfect for documentation, educational materials, blogging, and much more for organizing knowledge.

* One of the key features of Podlite is its extensibility. This allows for defining unique and domain-specific blocks and expanding the language's functionality according to the requirements of your project.

* [The Podlite specification](https://github.com/podlite/podlite-specs) is published under the Artistic license 2.0.

![bigtitle-social-release-1 0](https://github.com/github/release-radar/assets/31441/095ba9ee-92a0-4852-86cd-ce94059380e2)

![photo](https://github.com/github/release-radar/assets/31441/18338dcc-ef0d-4392-9af1-3002a990f219)

### Version

1.0

### Date

April 23

### Description of breaking changes

this is the first release of a long time 😅

## Summary of Release

This release of Podlite introduces significant enhancements aimed at improving the flexibility, customization, and user interaction of the markup language. With the addition of new blocks, attributes, and support for rich media, Podlite is better equipped to handle a variety of documentation needs.

Concurrently, the deprecation and removal of certain features have simplified the toolset, reducing overlap and enhancing user experience. These changes reflect a commitment to the continuous improvement of Podlite, ensuring it remains a versatile and powerful tool for content creators.

## Podlite v1.0 Release Notes

Podlite has introduced a range of new features designed to enhance the flexibility and usability of the markup language:

### Customization and Extensibility
   
   - **Refactoring of Custom blocks:** Enhanced customization through refactored named custom blocks.
   
   - **Inline Markup extension:** `M<>` now extends inline markup features, allowing for more expressive text formatting.
   

### Processing and data handling

   - **Markdown support:** The ``=markdown` block is now a standard block. Integration of a new markdown mode for the parser.
   
   - **MIME type specification:** Added `:mime-type` attribute for `=include` and `=data` blocks, facilitating better handling of diverse data types.
      
   - **Data schema introduction:** Implemented `data:` schema for use in `=picture` and `=table` blocks, simplifying data embedding.
      
   - **Embedding binary data:** Support for embedding binary data directly into documents with `:filename` and `:encoding` attributes in `=data` blocks.
   
   - **CSV tables:** Capability to render tables directly from CSV files with the enhanced `=table` block.

### Content Structuring and Navigation
   
   - **Selectors:** Introduced selectors for dynamic content interaction and manipulation.
   
   - **Comprehensive TOC:** Enhanced `=toc` block for generating detailed tables of contents.
   
   - **Including external content:** New `=include` block for incorporating external files and documents seamlessly.
  
   - **Advanced table formatting:** New `=row` and `=cell` blocks with `:header`, `:rowspan`, and `:colspan` attributes for intricate table designs.
     
   - **Additional attributes for linking:** Addition of `:id`, `:caption`, and `:lang` attributes to enrich document metadata and accessibility.
         
   - **Contextual backlinks:** `W<>` for creating contextual backlinks, enhancing document navigation and reference capabilities.
   
   - **Foldable content:** New `:folded` attribute to toggle visibility of content, and `:folded-levels` for nested visibility control in table of contents (TOC) blocks.

   

### Document Presentation Enhancements

   - **Notification blocks:** Introduced notification blocks with a `:notify` attribute, improving interactivity within documents.
   
   
   - **Task lists:** Introduction of task lists with the `=item` block and a `:checked` attribute to manage to-do items effectively.
    
   - **Mistake marking:** Introduced `O<>` for highlighting and marking mistakes, useful in educational and review settings.
   
   - **Text positioning:** New attributes `J<>` for justifying and `H<>` for horizontal positioning of text.
   
   - **Emojis:** Added support for emojis with `E<>`, enriching the expressiveness of documents.
   
   - **Picture insertions:** New features in the `=picture` block and `P<>` for improved image handling.
   
   - **Mathematical formulas:** Enhanced support for complex mathematical formulas with `=formula` and `F<>`.

### Deprecated/removed

With the introduction of new functionalities, certain features have been deprecated or removed to streamline Podlite:

-   `P<toc:>` due to `=toc` block,

-   `P<man:>`, `P<doc:>` due to `=include` block,

-   `:margin` attribute, `=encoding` directive, Declarator block been removed due to redundancy.

-   Contextual aliases, the `=finish` directive, and markers in comments, `P<>` - placement links, `:formatted` attribute, `:like` attribute have been removed due to redundancy and enhancements in other areas.

### GitHub Repo

https://github.com/podlite/podlite-specs

### Website

https://podlite.org/

### Link to changelog

https://github.com/podlite/podlite-specs/releases/tag/v1.0

### Social media

https://dev.to/zag/podlite-v10-released-a-lightweight-block-oriented-markup-language-for-organizing-knowledge-313l

## Feedback and Contributions

Feedback is encouraged and can be provided through [Github Discussions](https://github.com/podlite/podlite-specs/discussions). This input is crucial for the ongoing development and enhancement of Podlite.

**Thank You!**

**Comment by mishmanners** [comment]
Epic congrats on being featured: https://dev.to/github/release-radar-april-2024-edition-major-updates-from-the-open-source-community-37k1

**Comment by zag** [comment]
Thank you for this wonderful opportunity!
