### ISSUE TITLE
[Release Radar Request] Uno Platform 5.2 Release

### ISSUE THREAD

**Issue by kazo0** [github/release-radar#215]
### Open Source Project name

Uno Platform

### What is your project?

Uno Platform is an open-source platform for building single codebase native mobile, web, desktop, and embedded apps quickly. It allows C# and WinUI XAML and/or C# code to run on all target platforms while allowing you control of every pixel.

### Version

5.2

### Date

April 22, 2024

### Description of breaking changes

First and only true .NET Single Project for Nine Platform Targets across Mobile, Web, Desktop, and Embedded.

Introducing Uno.SDK Features for easy NuGet package management.

Multi-Window support.

Enhanced Skia renderers for improved performance.

### GitHub Repo

https://github.com/unoplatform/uno

### Website

https://platform.uno/

### Link to changelog

https://aka.platform.uno/blog-5-2

### Social media

https://x.com/UnoPlatform/status/1782496737271087537

### Anything else to add?

This release adds new large features and a new project structure, but technically no breaking changes so it did not necessitate a major version bump.

We had 2400 commits included in this release compared to less than 1500 commits in a typical release.

**Comment by mishmanners** [comment]
As mentioned via Twitter DMs, thanks for submitting, and we're really excited to feature this project. The Release Radar features major version releases. Please submit again when you have version 6.0 and we'll feature you 😄
