### ISSUE TITLE
[RR Request]: Social Switch v1.0

### ISSUE THREAD

**Issue by claromes** [github/release-radar#216]
### Open Source Project name

Social Switch

### What is your project?

Redirect Instagram and TikTok URLs to anonymous viewers. Access any profile, posts, tagged posts, stories profile or tags on Instagram or any profile on TikTok and the extension will redirect automatically to web viewers. From **Instagram URLs** to Picuki.com or Imginn.com, and from **TikTok URLs** to UrleBird.com or Xaller.com.

Select a viewer option and enable or disable redirection through the popup:

![popup](https://github.com/github/release-radar/assets/28742647/0334ca9a-401e-4c2b-a0d3-75283919b18e)

## Installation

Firefox: https://addons.mozilla.org/en-US/firefox/addon/social-switch/

Firefox for Android: https://addons.mozilla.org/en-US/android/addon/social-switch/

Google Chrome: https://chromewebstore.google.com/detail/social-switch-anonymous-i/elmbjjhgiifenlhffpjcjfkjmilbbfki

### Version

1.0

### Date

May 12, 2024

### Description of breaking changes

- Update the code to comply with Firefox/Firefox for Android extension rules
    - Background script and Popup
    - Update tests
    - CSS for Android compatibility
    - Switch from using the `tabs` API to the `webRequest` API in Firefox/Firefox for Android version
    - Organize directories to separate code for Chrome and Firefox
- Update docs
    - Provide more detailed information about tests, installation, and privacy
- Fix IG Tagged Profile parsing for Firefox

### GitHub Repo

https://github.com/claromes/socialswitch

### Website

https://github.com/claromes/socialswitch

### Link to changelog

https://claromes.com/blog/social-switch-v1.html

### Social media

https://ruby.social/@claromes/112434842648371282

### Anything else to add?

- First release for Firefox and Firefox for Android (minor releases only included the Chrome version)
- This extension is not affiliated with Instagram, TikTok, Picuki, Imginn, UrleBird, and Xaller

**Comment by mishmanners** [comment]
Congrats on being featured in the May Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-may-2024-edition-major-updates-from-the-open-source-community-4oj3)
- Feel free to [retweet Mish's tweet featuring you](https://x.com/MishManners/status/1798956918008057981)
- Check out the [Linked post featuring you](https://www.linkedin.com/feed/update/urn:li:activity:7204725590195642372/) 😄
