### ISSUE TITLE
[RR Request]: rho-mu 4.0.0

### ISSUE THREAD

**Issue by cicirello** [github/release-radar#217]
### Open Source Project name

ρμ

### What is your project?

ρμ is a Java library of Randomization enHancements and Other Math Utilities (rho mu).

### Version

4.0.0

### Date

May 14, 2024

### Description of breaking changes

ρμ version 4.0.0 makes improvements to the generation of random pairs and triples of distinct integers, adds support for generating streams of random pairs and triples of distinct integers, adds methods for efficiently shuffling arrays and Lists, removes a couple previously deprecated classes, and includes some improvements to internal library code.

### GitHub Repo

https://github.com/cicirello/rho-mu

### Website

https://rho-mu.cicirello.org/

### Link to changelog

https://github.com/cicirello/rho-mu/blob/main/CHANGELOG.md

### Social media

I didn't post this on social media.

**Comment by mishmanners** [comment]
Congrats on being featured in the May Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-may-2024-edition-major-updates-from-the-open-source-community-4oj3)
- Feel free to [retweet Mish's tweet featuring you](https://x.com/MishManners/status/1798956918008057981)
- Check out the [Linked post featuring you](https://www.linkedin.com/feed/update/urn:li:activity:7204725590195642372/) 😄
