### ISSUE TITLE
[Release Radar Request] simple-data-analysis v3.0.0

### ISSUE THREAD

**Issue by nshiab** [github/release-radar#218]
### Open Source Project name

simple-data-analysis

### What is your project?

SDA is an easy-to-use and high-performance JavaScript library for data analysis.

### Version

3.0.0

### Date

June 7, 2024

### Description of breaking changes

SDA is now easier to use and can process both tabular and geospatial data. It operates seamlessly in the browser and with NodeJS/Bun. It's fast and efficient. We've even tackled the 1 Billion Row Challenge with it!

### GitHub Repo

https://github.com/nshiab/simple-data-analysis

### Website

https://github.com/nshiab/simple-data-analysis

### Link to changelog

https://github.com/nshiab/simple-data-analysis/releases/tag/v3.0.0

### Social media

https://x.com/NaelShiab/status/1799098028600742311

### Anything else to add?

I am a computational journalist and senior data producer for [CBC News](https://www.cbc.ca/news).

SDA is born out of the frustration of switching between Python, R, and JavaScript to produce data journalism projects. Usually, data crunching and analysis are done with Python or R, and interactive data visualizations are coded in JavaScript. However, being proficient in multiple programming languages is hard. Why can't we do everything in JS?

The missing piece in the JavaScript/TypeScript ecosystem was an easy-to-use and performant library for data analysis. This is why SDA was created!

Thank you for your consideration! :)

**Comment by mishmanners** [comment]
Congrats on being featured in the June 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/major-updates-from-the-open-source-community-release-radar-june-2024-4mf5)
- Feel free to [retweet Mish's tweet featuring you](https://x.com/MishManners/status/1810110537633865884)
- See and share [LinkedIn post](https://www.linkedin.com/posts/mishmanners_major-updates-from-the-open-source-community-activity-7215875331612659713-9n08?utm_source=share&utm_medium=member_desktop)

Please share via your networks too, and congrats again ✨
