### ISSUE TITLE
[Release Radar Request] FakeRest

### ISSUE THREAD

**Issue by fzaninotto** [github/release-radar#219]
### Open Source Project name

FakeRest

### What is your project?

A browser library that intercepts AJAX calls to mock a REST server based on JSON data.

### Version

4.0

### Date

June 10, 2024

### Description of breaking changes

- Add support for MSW
- Add support for string identifiers
- Add support for custom id generation
- Refactor interceptors as middlewares
- Add ability to delay the response
- Add ability to simulate server-side validation
- Add ability to simulate authentication checks
- Add TypeScript types

### GitHub Repo

https://github.com/marmelab/FakeRest

### Website

https://github.com/marmelab/FakeRest

### Link to changelog

https://github.com/marmelab/FakeRest/releases/tag/v4.0.0

### Social media

https://x.com/marmelab/status/1800105197391561167

**Comment by mishmanners** [comment]
Congrats on being featured in the June 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/major-updates-from-the-open-source-community-release-radar-june-2024-4mf5)
- Feel free to [retweet Mish's tweet featuring you](https://x.com/MishManners/status/1810110537633865884)
- See and share [LinkedIn post](https://www.linkedin.com/posts/mishmanners_major-updates-from-the-open-source-community-activity-7215875331612659713-9n08?utm_source=share&utm_medium=member_desktop)

Please share via your networks too, and congrats again ✨
