### ISSUE TITLE
[Release Radar Request] Goyave v5

### ISSUE THREAD

**Issue by System-Glitch** [github/release-radar#220]
### Open Source Project name

Goyave

### What is your project?

Goyave an opinionated all-in-one Golang web framework focused on REST APIs, with emphasis on code reliability, maintainability and developer experience.

### Version

5.0.0

### Date

June 6, 2024

### Description of breaking changes

The framework has been redesigned and rewritten from the ground up to fix all the flaws of the previous design and take advantage of the modern language features. 

### GitHub Repo

https://github.com/go-goyave/goyave

### Website

https://goyave.dev/

### Link to changelog

https://github.com/go-goyave/goyave/releases/tag/v5.0.0

### Social media

https://x.com/ImFlyingPancake/status/1800544287840690200

**Comment by mishmanners** [comment]
Congrats on being featured in the June 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/major-updates-from-the-open-source-community-release-radar-june-2024-4mf5)
- Feel free to [retweet Mish's tweet featuring you](https://x.com/MishManners/status/1810110537633865884)
- See and share [LinkedIn post](https://www.linkedin.com/posts/mishmanners_major-updates-from-the-open-source-community-activity-7215875331612659713-9n08?utm_source=share&utm_medium=member_desktop)

Please share via your networks too, and congrats again ✨
