### ISSUE TITLE
[RR Request]: React-admin v5

### ISSUE THREAD

**Issue by fzaninotto** [github/release-radar#221]
### Open Source Project name

react-admin

### What is your project?

React-admin is a Single-Page Application framework that lets you build web apps running on top of REST/GraphQL APIs, using TypeScript, React and Material Design.

### Version

5.0

### Date

20/06/24

### Description of breaking changes

📜 Refined Lists & Forms (improved DX and UX)
🔧 Dependency Updates (Tanstack query, react-router, React 18)
🚀 Easier App Initialization (CLI, deeper GraphQL integration)

### GitHub Repo

https://github.com/marmelab/react-admin

### Website

https://marmelab.com/react-admin/

### Link to changelog

https://github.com/marmelab/react-admin/releases/tag/v5.0.0

### Social media

https://x.com/ReactAdmin/status/1803762059202404857

### Anything else to add?

More than 25,000 companies around the world use react-admin to build dashboards, internal apps, ERPs, and B2B apps. This new version has been 7 months in the making and is the new foundation for many more features to come.

**Comment by fzaninotto** [comment]
Any updates on this one?

**Comment by mishmanners** [comment]
Congrats on being featured in the June 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/major-updates-from-the-open-source-community-release-radar-june-2024-4mf5)
- Feel free to [retweet Mish's tweet featuring you](https://x.com/MishManners/status/1810110537633865884)
- See and share [LinkedIn post](https://www.linkedin.com/posts/mishmanners_major-updates-from-the-open-source-community-activity-7215875331612659713-9n08?utm_source=share&utm_medium=member_desktop)

Please share via your networks too, and congrats again ✨
