### ISSUE TITLE
[Release Radar Request] Keuss 2.0 deployed!

### ISSUE THREAD

**Issue by mjkwak** [github/release-radar#222]
### Open Source Project name

Keuss

### What is your project?

A serverless, persistent and high-available queue middleware, build on Node.js, supporting delays/schedule, using a preexisting database to provide most of the backend functionality; we currently support `mongodb`, `redis` and `postgresql`

### Version

2.0

### Date

June 23, 2024

### Description of breaking changes

- Added a new major backend: now Keuss supports queues over PostgreSQL databases!
-The initialization for the queue system factory.queue(), is now asynchronous, and requires a callback.

### GitHub Repo

https://github.com/pepmartinez/keuss

### Website

https://pepmartinez.github.io/keuss/

### Link to changelog

https://pepmartinez.github.io/keuss/docs/changelog/

### Social media

none

### Anything else to add?

You rock!

**Comment by mishmanners** [comment]
Congrats on being featured in the June 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/major-updates-from-the-open-source-community-release-radar-june-2024-4mf5)
- Feel free to [retweet Mish's tweet featuring you](https://x.com/MishManners/status/1810110537633865884)
- See and share [LinkedIn post](https://www.linkedin.com/posts/mishmanners_major-updates-from-the-open-source-community-activity-7215875331612659713-9n08?utm_source=share&utm_medium=member_desktop)

Please share via your networks too, and congrats again ✨
