### ISSUE TITLE
[RR Request]: GoodJob v4

### ISSUE THREAD

**Issue by bensheldon** [github/release-radar#223]
### Open Source Project name

GoodJob

### What is your project?

GoodJob is a multithreaded, Postgres-based, Active Job backend for Ruby on Rails.

### Version

4.0

### Date

July 6, 2024

### Description of breaking changes

GoodJob v4 does not introduce any new features on its own; instead, GoodJob's major releases resolve deferred database schema changes and remove deprecated behavior. 

Since the previous major version, GoodJob v3.0 (June 2022), there have been 110 minor/patch releases from 88 contributors with many new features and improvements including: batches, bulk enqueuing, labelled jobs, job throttling, dark mode for the web dashboard, storage of error backtraces and contexts, ordered queues, the ability to pause repeating/cron-like jobs, systemd integration, healthchecks, and much more.  

Significantly, GoodJob v4 changes how job and job execution records are stored in the database; moving from job and executions being commingled in the `good_jobs` table to Jobs (still in `good_jobs`) having many discrete Execution records in the `good_job_executions` table. GoodJob v4 requires Rails 6.1+, CRuby 3.0+, or JRuby 9.4+.

### GitHub Repo

https://github.com/bensheldon/good_job

### Website

http://github.com/bensheldon/good_job

### Link to changelog

https://github.com/bensheldon/good_job/discussions/1396

### Social media

https://ruby.social/@bensheldon/112743421143107997

### Anything else to add?

Excited to finally make a submission for the Release Radar 🎉

**Comment by mishmanners** [comment]
Congrats on being featured in the August 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-july-2024-major-updates-from-the-open-source-community-446f)
- [Check out our GitHub Tweet](https://x.com/github/status/1820700080103456978)
- [Check out Mish's Tweet](https://x.com/MishManners/status/1820616406414860429)
- [DEV featured the article on Twitter](https://x.com/ThePracticalDev/status/1822341645989200036)
- Feel free to [share Mish's LinkedIn post featuring you](https://www.linkedin.com/posts/mishmanners_release-radar-july-2024-major-updates-activity-7226383276037283840-fhmU)

Please share via your networks too, and congrats again ✨
