### ISSUE TITLE
[Release Radar Request] DataChain - open source Python library for processing and curating unstructured data at scale

### ISSUE THREAD

**Issue by jendefig** [github/release-radar#224]
### Open Source Project name

DataChain

### What is your project?

DataChain is an open-source Python library for processing and curating unstructured data at scale.

🤖 AI-Driven Data Curation: Use local ML models or LLM APIs calls to enrich your data.
🚀 GenAI Dataset scale: Handle tens of millions of multimodal files.
🐍 Python-friendly: Use strictly-typed [Pydantic](https://github.com/pydantic/pydantic) objects instead of JSON.

DataChain supports parallel processing, parallel data downloads, and out-of-memory computing. It excels at optimizing offline batch operations.

The typical use cases include Computer Vision data curation, LLM analytics, and validation of multimodal AI applications.

### Version

0.2.12 (debut to the public)

### Date

July 23, 2024

### Description of breaking changes

nil

### GitHub Repo

https://github.com/iterative/datachain

### Website

https://dvc.ai

### Link to changelog

https://github.com/iterative/datachain/releases/tag/0.2.12

### Social media

https://x.com/DVCorg/status/1815735081551729119

### Anything else to add?

This release is the debut of this open-source tool to the community!

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄

**Comment by jendefig** [comment]
Thank you!  Will do!

Jeny De Figueiredo

Community Manager

***@***.*** ( ***@***.*** )

( https://calendly.com/jeny-dvc/30min ) ( https://github.com/iterative ) ( https://www.linkedin.com/company/iterative-ai/ )

( https://dvc.ai/ )

Sent via Superhuman ( ***@***.*** )
