### ISSUE TITLE
[RR Request] Meteor.js 3.0

### ISSUE THREAD

**Issue by fredmaiaarantes** [github/release-radar#225]
### Open Source Project name

Meteor.js

### What is your project?

Meteor.js is a full-stack framework that simplifies web and mobile application development. It allows developers to use React, Vue, Svelte, Solid, or Blaze for the front end. With a zero-configuration setup, TypeScript support, and RPC APIs, it enables the quick creation of real-time features and comes with a built-in accounts package for seamless authentication.

### Version

3.0

### Date

July 16, 2024

### Description of breaking changes

Meteor.js has undergone a significant transformation with its latest update, Meteor 3.0. This upgrade not only modernizes the framework but also enhances its capabilities by integrating the latest Node.js 20 features, moving from Fibers to native async/await, Express integration, ARM support, and package updates.

Here's the link to the new documentation: https://v3-docs.meteor.com.

### GitHub Repo

https://github.com/meteor/meteor

### Website

https://meteor.com

### Link to changelog

https://dev.to/meteor/meteor-3-is-officially-here-3gml

### Social media

https://x.com/meteorjs/status/1813591601157222648

**Comment by mishmanners** [comment]
Congrats on being featured in the August 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-july-2024-major-updates-from-the-open-source-community-446f)
- [Check out our GitHub Tweet](https://x.com/github/status/1820700080103456978)
- [Check out Mish's Tweet](https://x.com/MishManners/status/1820616406414860429)
- [DEV featured the article on Twitter](https://x.com/ThePracticalDev/status/1822341645989200036)
- Feel free to [share Mish's LinkedIn post featuring you](https://www.linkedin.com/posts/mishmanners_release-radar-july-2024-major-updates-activity-7226383276037283840-fhmU)

Please share via your networks too, and congrats again ✨
