### ISSUE TITLE
[Release Radar Request] JavaPermutationTools 6.0.0

### ISSUE THREAD

**Issue by cicirello** [github/release-radar#226]
### Open Source Project name

JavaPermutationTools

### What is your project?

The JavaPermutationTools (JPT) library provides Java classes and interfaces, etc that enable representing and generating permutations and sequences, as well as performing computation on permutations and sequences. It includes implementations of a variety of permutation distance metrics as well as distance metrics on sequences (i.e., Strings, arrays, and other ordered data types).

### Version

6.0.0

### Date

July 25, 2024

### Description of breaking changes

The latest changes include various improvements to implementations of algorithms for randomly sampling from arrays, as well as removing previously deprecated interfaces, and a variety of minor fixes to issues identified by static analysis with SpotBugs.

### GitHub Repo

https://github.com/cicirello/JavaPermutationTools

### Website

https://jpt.cicirello.org/

### Link to changelog

https://github.com/cicirello/JavaPermutationTools/releases/tag/v6.0.0

### Social media

I didn't post this on social media.

**Comment by mishmanners** [comment]
Congrats on being featured in the August 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-july-2024-major-updates-from-the-open-source-community-446f)
- [Check out our GitHub Tweet](https://x.com/github/status/1820700080103456978)
- [Check out Mish's Tweet](https://x.com/MishManners/status/1820616406414860429)
- [DEV featured the article on Twitter](https://x.com/ThePracticalDev/status/1822341645989200036)
- Feel free to [share Mish's LinkedIn post featuring you](https://www.linkedin.com/posts/mishmanners_release-radar-july-2024-major-updates-activity-7226383276037283840-fhmU)

Please share via your networks too, and congrats again ✨
