### ISSUE TITLE
[RR Request]: enioka Scan 3.0.0

### ISSUE THREAD

**Issue by DaSpood** [github/release-radar#227]
### Open Source Project name

enioka Scan

### What is your project?

enioka Scan is an integration library for all your Android hardware barcode scanner needs. It lets developers write their application once and keep the freedom of choosing their scanner manufacturer without worrying about vendor lock-in.

### Version

3.0.0

### Date

July 31st, 2024

### Description of breaking changes

The library's structure was reworked to give more control to the developer, who can now choose only the modules they need. A proper documentation page is now available, making it easy to start developing with the library, or contribute to it. And the demo application was completely overhauled and published on the Google Play Store.

### GitHub Repo

https://github.com/enioka-Haute-Couture/enioka_scan

### Website

https://github.com/enioka-Haute-Couture/enioka_scan

### Link to changelog

https://github.com/enioka-Haute-Couture/enioka_scan/releases/tag/3.0.0

### Social media

N/A

### Anything else to add?

This release focuses mainly on improving the user and developer experience. While it contains a limited amount of new features, the fixes and reworks make it easier than ever for people to start using the library in their projects.

**Comment by mishmanners** [comment]
Congrats on being featured in the August 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-july-2024-major-updates-from-the-open-source-community-446f)
- [Check out our GitHub Tweet](https://x.com/github/status/1820700080103456978)
- [Check out Mish's Tweet](https://x.com/MishManners/status/1820616406414860429)
- [DEV featured the article on Twitter](https://x.com/ThePracticalDev/status/1822341645989200036)
- Feel free to [share Mish's LinkedIn post featuring you](https://www.linkedin.com/posts/mishmanners_release-radar-july-2024-major-updates-activity-7226383276037283840-fhmU)

Please share via your networks too, and congrats again ✨
