### ISSUE TITLE
[Release Radar Request] OrangeHRM 5.7

### ISSUE THREAD

**Issue by Super-Chama** [github/release-radar#228]
### Open Source Project name

OrangeHRM Open Source

### What is your project?

OrangeHRM is a comprehensive Human Resource Management (HRM) System that captures all the essential functionalities required for any enterprise.

### Version

5.7

### Date

July 19, 2024

### Description of breaking changes

None

### GitHub Repo

https://github.com/orangehrm/orangehrm

### Website

https://www.orangehrm.com/en/orangehrm-starter-open-source-software/

### Link to changelog

https://github.com/orangehrm/orangehrm/releases/tag/v5.7

### Social media

https://www.facebook.com/OrangeHRM

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 6.0 and we'd love to consider your project for feature 😄
