### ISSUE TITLE
[Release Radar Request] PostCSS Preset Env

### ISSUE THREAD

**Issue by romainmenke** [github/release-radar#229]
### Open Source Project name

PostCSS Preset Env

### What is your project?

PostCSS Preset Env lets you convert modern CSS into something most browsers can understand, determining the polyfills you need based on your targeted browsers or runtime environments.

### Version

10.0.0

### Date

Augustus 3, 2024

### Description of breaking changes

We updated support for CSS Nesting to align with the latest specification.
This latest iteration preserves the order of nested declarations and rules to better support mixins.

We also dropped support for older node versions and only support node 18 and later.

https://github.com/csstools/postcss-plugins/wiki/PostCSS-Preset-Env-10

### GitHub Repo

https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env

### Website

https://preset-env.cssdb.org/

### Link to changelog

https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/CHANGELOG.md

### Social media

nil

**Comment by mishmanners** [comment]
Congrats on being featured in the August 2024 Release Radar 🥳

- Read the blog [here](https://dev.to/github/release-radar-august-2024-major-updates-from-the-open-source-community-54mo)
- [Check out our GitHub Tweet](https://x.com/github/status/1832922112975126537)
- Feel free to [retweet Mish's tweet featuring you](https://x.com/MishManners/status/1831863241229922643)

**Comment by romainmenke** [comment]
Awesome!
Thank you so much @mishmanners
