### ISSUE TITLE
[RR Request]: Front Matter v5.7.0

### ISSUE THREAD

**Issue by estruyf** [github/release-radar#23]
### Open Source Project name

Front Matter

### What is your project?

Front Matter is a CMS that runs within Visual Studio Code. It gives you the power and control of a full-blown CMS while also providing you the flexibility and speed of the static site generator of your choice. Jump right into editing and creating content with Front Matter and be able to preview it straight in VS Code.

### Version

5.7.0

### Date

December 7, 2021

### Description of changes

Release notes: https://frontmatter.codes/updates/v5.7.0

## What you see is what you get (WYSIWYG) controls

To help out content editors write their content in Markdown. Front Matter provides a couple of helpful, what you see is what you get (WYSIWYG), controls while working in a Markdown file.

All the controls can be found on the top right of the opened file title bar.

![WYSIWYG controls](https://user-images.githubusercontent.com/2900833/145001311-ff2f765f-852e-43ca-810d-a6dd771fa19f.png)

Currently supported are:

- Headings
- Bold
- Italic
- Strikethrough
- Blockquote
- Code snippet
- Code block
- Ordered list
- Unordered list
- Tasklist

Find out more about the `WYSIWYG` control at the [WYSIWYG section](/docs/markdown#wysiwyg) of the markdown page.

## Diagnostic output

When you encounter an issue, you will now be able to use the `Diagnostic logging` command in order to get an overview of the current state of your project. Over time, this diagnostic output will be improved and more information will be added.

## Markdown file extension support

Besides the `.md` and `.mdx`, the Front Matter now supports files with the `.markdown` extension as well.

### 🎨 Enhancements

- [#188](https://github.com/estruyf/vscode-front-matter/issues/188): Support for `.markdown` files added to the dashboard
- [#190](https://github.com/estruyf/vscode-front-matter/issues/190): Diagnostic output for the extension
- [#194](https://github.com/estruyf/vscode-front-matter/issues/194): WYSIWYG controls added for markdown files + configuration to enable/disable the functionality

### 🐞 Fixes

- [#191](https://github.com/estruyf/vscode-front-matter/issues/191): Fix beta settings page
- [#200](https://github.com/estruyf/vscode-front-matter/issues/200): Fix last modified date sorting for media files
- [#201](https://github.com/estruyf/vscode-front-matter/issues/201): Fix overflow issue with the media filename
- [#202](https://github.com/estruyf/vscode-front-matter/issues/202): Fix checkbox label color for light themes

### GitHub Repo

https://github.com/estruyf/vscode-front-matter

### Website

https://frontmatter.codes

### Link to changelog

https://frontmatter.codes/updates

### Social media

https://twitter.com/eliostruyf/status/1468148453704450049?s=20

### Anything else to add?

This is a great initiative 🤘

**Comment by mishmanners** [comment]
Thanks for submitting. We loved your project, but we had so many submissions for the December 2021 release radar that we priortised Version X.0 releases. Please submit again when you have the next major version and we'd love to consider your project for feature again 😄
