### ISSUE TITLE
[Release Radar Request] SQL StringBuilder DSL Release 0.0.11

### ISSUE THREAD

**Issue by psycotrompus** [github/release-radar#230]
### Open Source Project name

sql-stringbuilder-dsl

### What is your project?

A Java based SQL statement builder but fancy.

### Version

0.0.11

### Date

12 Aug 2024

### Description of breaking changes

* added support for a number of SQL comparators
* added contributor notes

### GitHub Repo

https://github.com/psycotrompus/sql-stringbuilder-dsl

### Website

https://psycotrompus.github.io

### Link to changelog

https://github.com/psycotrompus/sql-stringbuilder-dsl/releases/tag/0.0.11

### Social media

https://github.com/psycotrompus

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
