### ISSUE TITLE
[RR Request]: SQL StringBuilder DSL 0.0.12

### ISSUE THREAD

**Issue by psycotrompus** [github/release-radar#232]
### Open Source Project name

sql-stringbuilder-dsl

### What is your project?

A Java based SQL statement builder but fancy.

### Version

0.0.12

### Date

14 Aug 2024

### Description of breaking changes

* added support for `GROUP BY ... HAVING`
* modified the projection design to accommodate aggregate functions

### GitHub Repo

https://github.com/psycotrompus/sql-stringbuilder-dsl

### Website

https://psycotrompus.github.io

### Link to changelog

https://github.com/psycotrompus/sql-stringbuilder-dsl/releases/tag/0.0.12

### Social media

https://github.com/psycotrompus

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
