### ISSUE TITLE
[Release Radar Request] Steadfast Self-Hosting 1.3.2

### ISSUE THREAD

**Issue by meonkeys** [github/release-radar#233]
### Open Source Project name

Steadfast Self-Hosting

### What is your project?

Steadfast Self-Hosting is a book and source code to help you set up a server and host your own web services.

### Version

1.3.2

### Date

August 19, 2024

### Description of breaking changes

This is a stability/maintenance 1.x release with the latest errata from feedback during my book tour.

### GitHub Repo

https://github.com/meonkeys/shb/

### Website

https://selfhostbook.com/

### Link to changelog

https://github.com/meonkeys/shb/blob/main/ChangeLog

### Social media

https://fosstodon.org/@meonkeys/112990403139133899

**Comment by meonkeys** [comment]
Ah shoot, I guess the 10th part out of this 10-part series was already posted?

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 2.0 and we'd love to consider your project for feature 😄
