### ISSUE TITLE
[Release Radar Request] Llamafile 0.8.13

### ISSUE THREAD

**Issue by stlhood** [github/release-radar#235]
### Open Source Project name

Llamafile

### What is your project?

Mozilla's Llamafile democratizes access to open source AI. It combines [llama.cpp](https://github.com/ggerganov/llama.cpp) with [Cosmopolitan Libc](https://github.com/jart/cosmopolitan) into one framework that collapses all the complexity of LLMs down to a single-file executable (called a "llamafile") that runs locally on most computers, with no installation.

### Version

0.8.13

### Date

August 19, 2024

### Description of breaking changes

This latest release of Llamafile adds support for the very latest models like Mistral Nemo, Gemma 2B, and the 1.58 bit TriLM model. It also adds new commands like whisperfile (speech to text / translation) and sdfile (image generation). Llamafile also continues to provide the highest available performance for CPU inference.

### GitHub Repo

https://github.com/Mozilla-Ocho/llamafile

### Website

https://llamafile.ai

### Link to changelog

https://github.com/Mozilla-Ocho/llamafile/releases/tag/0.8.13

### Social media

https://x.com/JustineTunney/status/1825551821857010143

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
