### ISSUE TITLE
[RR Request]: Tailwind 3.0 release

### ISSUE THREAD

**Issue by bdougie** [github/release-radar#24]
### Open Source Project name

Tailwind

### What is your project?

A utility-first CSS framework packed with classes like flex, pt-4, text-center and rotate-90 that can be composed to build any design, directly in your markup.

### Version

3.0

### Date

12/9/2022

### Description of changes

https://tailwindcss.com/blog/tailwindcss-v3

### GitHub Repo

https://github.com/tailwindlabs/tailwindcss

### Website

https://tailwindcss.com/

### Link to changelog

https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.0

### Social media

https://twitter.com/tailwindcss/status/1469011535569821702

**Comment by mishmanners** [comment]
Congrats on being featured in the December Release Radar 🥳 
- [Read the blog here](https://github.blog/2022-01-21-release-radar-dec-2021/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1484671401659359235)
- [Feel free to retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1485499076775137280)

Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github/videos) for a December Release Radar promo video 😄
