### ISSUE TITLE
[Release Radar Request] Git quick stats

### ISSUE THREAD

**Issue by arzzen** [github/release-radar#240]
### Open Source Project name

GIT quick statistics

### What is your project?

 ▁▅▆▃▅ Git quick statistics is a simple and efficient way to access various statistics in git repository. 

> Any git repository may contain tons of information about commits, contributors, and files. Extracting this information is not always trivial, mostly because there are a gadzillion options to a gadzillion git commands - I don't think there is a single person alive who knows them all. Probably not even [Linus Torvalds](https://github.com/torvalds) himself :).

### Version

2.5.8

### Date

October 10, 2024

### Description of breaking changes

Adjust commitsByYear() to support multiple dates by @tomice in https://github.com/arzzen/git-quick-stats/pull/174

### GitHub Repo

https://github.com/arzzen/git-quick-stats

### Website

https://git-quick-stats.sh/

### Link to changelog

https://github.com/arzzen/git-quick-stats/releases/tag/2.5.8

### Social media

no

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 3.0 and we'd love to consider your project for feature 😄
