### ISSUE TITLE
[Release Radar Request]: JSON For You 3.0

### ISSUE THREAD

**Issue by loggerhead** [github/release-radar#241]
### Open Source Project name

JSON For You

### What is your project?

JSON For You is a comprehensive JSON toolkit designed for visualizing, comparing, formatting and validating JSON data, with support for conversion and powerful JSON processing capabilities.

![Graph mode](https://raw.githubusercontent.com/loggerhead/json4u/refs/heads/main/public/example/graph.webp)
![Table mode](https://raw.githubusercontent.com/loggerhead/json4u/refs/heads/main/public/example/table.webp)

### Version

3.0

### Date

September 24, 2024

### Description of breaking changes

The latest changes introduce the following features:

1. Added graph and table view modes for visualization.
2. Redesign the UI for better scalability.
3. Separated command execution into web worker to boost performance.

### GitHub Repo

https://github.com/loggerhead/json4u

### Website

https://json4u.com/

### Link to changelog

https://json4u.com/changelog

### Social media

https://x.com/1oggerhead/status/1838504288668299442

**Comment by mishmanners** [comment]
Thanks for submitting. I would have loved to feature you. But we couldn't include your project in the September Release Radar, as that had already shipped. Please definitely submit again for version 4.0 and we'd love to consider your project 😄
