### ISSUE TITLE
[Release Radar Request] Residents - www.residents.rest

### ISSUE THREAD

**Issue by conorluddy** [github/release-radar#243]
### Open Source Project name

Residents

### What is your project?

Residents is an open-source, robust, TypeScript-based backend API designed to serve as a solid foundation for building user-centric applications. Built out of the need for a reusable, secure, and feature-rich starting point, this project focuses on providing essential user management, authentication, and authorization functionalities. With an emphasis on developer experience, code quality, and best practices, Residents aims to streamline the development process for various applications requiring user accounts and access control.

![GitHub Actions Workflow Status](https://img.shields.io/github/actions/workflow/status/conorluddy/Residents/ci.yml) [![codecov](https://codecov.io/gh/conorluddy/Residents/branch/main/graph/badge.svg?token=WTHO1C6UL4)](https://codecov.io/gh/conorluddy/Residents) ![Dynamic JSON Badge](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2Fconorluddy%2FResidents%2Fmain%2F.github%2Ftype-coverage.json&query=%24.percentString&suffix=%25&style=flat&logo=typescript&label=TS%20Coverage&color=abff3d)
 ![Last Commit](https://img.shields.io/github/last-commit/conorluddy/Residents) ![License](https://img.shields.io/github/license/conorluddy/Residents) ![Version](https://img.shields.io/github/package-json/v/conorluddy/Residents) 

### Version

0.2.5

### Date

October 26th 2024

### Description of breaking changes

nil

### GitHub Repo

https://github.com/conorluddy/Residents

### Website

https://www.residents.rest

### Link to changelog

https://github.com/conorluddy/Residents/releases

### Social media

Nope - I try to avoid social media 😅

### Anything else to add?

Thanks for your consideration! This is very much an ongoing work in progress, but it's at a point now where it may bring value to people.

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄

**Comment by conorluddy** [comment]
No problem at all - I thought that might be the case 😆  I'll get some more features in before I release 1.0 and come back again. 👋🏻
