### ISSUE TITLE
[Release Radar Request] Llama

### ISSUE THREAD

**Issue by antonmedv** [github/release-radar#25]
### Open Source Project name

Llama

### What is your project?

The Llama is a new terminal file manager. Minimalistic and beautiful. 

### Version

1.0.0

### Date

November 9

### Description of changes

First release!

### GitHub Repo

https://github.com/antonmedv/llama

### Website

https://github.com/antonmedv/llama

### Link to changelog

https://github.com/antonmedv/llama/releases/tag/v1.0.0

### Social media

https://twitter.com/antonmedv/status/1469077533815627778?s=21

**Comment by mishmanners** [comment]
This is awesome! Sorry we couldn't include it in the November Release Radar as that had already shipped. Please definitely submit again for v2.0 and we'd love to include it 😄
