### ISSUE TITLE
[RR Request]: Pacstall

### ISSUE THREAD

**Issue by Henryws** [github/release-radar#27]
### Open Source Project name

Pacstall

### What is your project?

Pacstall is an AUR like package manager for Ubuntu, aimed at solving the issue of outdated packages in the standard repos

### Version

1.7

### Date

December 4th, 2021

### Description of changes

The latest release includes many quality of life features and bug fixes. The most notable is the inclusion of the `-K` flag, which allows testers of packages to keep a broken build in a tmp folder, allowing them to inspect the broken builds and fix the issue quicker

### GitHub Repo

https://github.com/pacstall/pacstall

### Website

https://pacstall.dev

### Link to changelog

https://github.com/pacstall/pacstall/releases/tag/1.7

### Social media

https://social.linux.pizza/web/@pacstall/107389438386122455

**Comment by mishmanners** [comment]
Thanks for submitting. We loved your project, but we had so many submissions for the December 2021 release radar that we priortised Version X.0 releases. Please submit again when you have the next major version and we'd love to consider your project for feature 😄
