### ISSUE TITLE
[Release Radar Request] ugit

### ISSUE THREAD

**Issue by Bhupesh-V** [github/release-radar#28]
### Open Source Project name

ugit

### What is your project?

ugit helps you undo git commands without much hassle, no need to visit StackOverflow each time you fuck-up with your git flow. Undo from more than 15+ Git fuckups.

### Version

5.0

### Date

Oct 2, 2021

### Description of changes

- Show git diff FZF previews at various places
- Minor TUI improvements
- Support for opening ugit guide on windows/wsl
- Improve code readability
- Support for fetching changelogs after updating ugit

### GitHub Repo

https://github.com/Bhupesh-V/ugit

### Website

https://bhupesh-v.github.io/undo-your-last-git-mistake-with-ugit/

### Link to changelog

https://github.com/Bhupesh-V/ugit/releases/tag/v5.0

### Social media

https://twitter.com/bhupeshimself/status/1436959224341229568

### Anything else to add?

ugit ships with a [git undo text guide](https://bhupesh.gitbook.io/notes/git/how-to-undo-anything-in-git) as well. just run `ugit --guide` to view what commands does ugit runs under the hood.

**Comment by mishmanners** [comment]
This is awesome! Sorry we couldn't include it in the October Release Radar as that had already shipped. Please definitely submit again for v6.0 and we'd love to include it 😄 (also please watch the language) 😉

**Comment by Bhupesh-V** [comment]
> This is awesome! Sorry we couldn't include it in the October Release Radar as that had already shipped. Please definitely submit again for v6.0 and we'd love to include it 😄 (also please watch the language) 😉

Thanks :)
