### ISSUE TITLE
[RR Request]: File Manager

### ISSUE THREAD

**Issue by Sas2k** [github/release-radar#29]
### Open Source Project name

File Manager

### What is your project?

__File Manager__ is a simple Terminal Based File Manager. This is still simple but I am making Updates to it everyday

### Version

3.1

### Date

December 6th 2021

### Description of changes

Settings and History and the ability to see the current path

### GitHub Repo

https://github.com/Sas2k/File-Manager

### Website

https://github.com/Sas2k/File-Manager

### Link to changelog

https://github.com/Sas2k/File-Manager

### Social media

https://github.com/Sas2k/File-Manager

**Comment by mishmanners** [comment]
Thanks for submitting. We loved your project, but we had so many submissions for the December 2021 release radar that we priortised Version X.0 releases. Please submit again when you have the next major version and we'd love to consider your project for feature again 😄

**Comment by Sas2k** [comment]
> Thanks for submitting. We loved your project, but we had so many submissions for the December 2021 release radar that we priortised Version X.0 releases. Please submit again when you have the next major version and we'd love to consider your project for feature 😄

Thanks
