### ISSUE TITLE
[Release Radar Request] PHPStan

### ISSUE THREAD

**Issue by ondrejmirtes** [github/release-radar#3]
### Open Source Project name

PHPStan

### What is your project?

PHPStan is a static analyser for PHP codebases and acts as a compiler for the interpreted language in the sense that it finds bugs without running the code and without writing tests.

### Version

1.0

### Date

November 1, 2021

### Description of changes

First major version of a popular PHP static analyser. It brings a brand-new rule level 9 that behaves stricter about checking the `mixed` type, and contains dozens of other improvements accumulated over the past 1½ years. PHPStan 1.0 also comes with a backward compatibility promise aimed towards end users and extension developers.

Here's the [accompanying blog article about the release](https://phpstan.org/blog/phpstan-1-0-released) and here are the [comprehensive release notes on GitHub](https://github.com/phpstan/phpstan/releases/tag/1.0.0).

### GitHub Repo

https://github.com/phpstan/phpstan

### Website

https://phpstan.org/

### Link to changelog

https://github.com/phpstan/phpstan/releases/tag/1.0.0

### Social media

https://twitter.com/OndrejMirtes/status/1455070385049948165

### Anything else to add?

I love how GitHub enables this project's existence, from both providing the infrastructure, and the funding through GitHub Sponsors which enables me to work on PHPStan full-time! Thank you.

**Comment by mishmanners** [comment]
This was included in our November Release Radar 🎉 congrats
