### ISSUE TITLE
[RR Request]: PyBaMM v21.11

### ISSUE THREAD

**Issue by priyanshuone6** [github/release-radar#30]
### Open Source Project name

PyBaMM

### What is your project?

PyBaMM (Python Battery Mathematical Modelling) solves physics-based electrochemical DAE models by using state-of-the-art automatic differentiation and numerical solvers. 

Like the Doyle-Fuller-Newman model can be solved in under 0.1 seconds, while the reduced-order Single Particle Model and Single Particle Model with electrolyte can be solved in just a few milliseconds.

### Version

21.11

### Date

December 1, 2021

### Description of changes

In PyBaMM v21.11 we have added
- 🔋Experiments with drive cycles
- 🔋SPM & SPMe half-cell models
- 🔋A reformatted structure for SEI models

plus many other features and optimisations.

### GitHub Repo

https://github.com/pybamm-team/PyBaMM

### Website

https://www.pybamm.org/
https://pybamm.readthedocs.io/en/latest/ (docs)

### Link to changelog

https://github.com/pybamm-team/PyBaMM/releases/tag/v21.11

### Social media

https://twitter.com/pybamm_/status/1466026041030316038

### Anything else to add?
The introductory paper is now out in the Journal of Open Research Software! This paper explains the motivation and design philosophy behind PyBaMM
Find it here: https://doi.org/10.5334/jors.309

Dropping the images into the issue

**Comment by priyanshuone6** [comment]
![compare_models](https://user-images.githubusercontent.com/64051212/145958130-25d3d628-4647-44d0-8506-f9739cf7956b.png)
![thermal_pouch](https://user-images.githubusercontent.com/64051212/145958362-838f531d-2f2d-4404-87f1-ba8a87dc0171.png)
![drive_cycle](https://user-images.githubusercontent.com/64051212/145960064-96289dfd-fc73-4fd1-b3a4-9003cc8305d5.png)
![experiments](https://user-images.githubusercontent.com/64051212/145960083-90c0ab83-0205-4a23-9dd7-2177356f1919.png)
![jelly roll](https://user-images.githubusercontent.com/64051212/145958241-450da907-db06-41ce-a33e-00e0589eab30.png)

**Comment by mishmanners** [comment]
Thanks for submitting. We loved your project, but we had so many submissions for the December 2021 release radar that we priortised Version X.0 releases. Please submit again when you have the next major version and we'd love to include your project 😄

**Comment by priyanshuone6** [comment]
PyBaMM have now moved to monthly releases to better suit the needs of the community. 
Hence smaller releases, but more frequent. The version number format is now YEAR.MONTH
Thanks

**Comment by mishmanners** [comment]
Oh awesome as. Definitely submit for the next month. I would love to include it. December ones already chosen, but would love to include for the January article.
