### ISSUE TITLE
[Release Radar Request] Tiny Land 1.0 - 1st Deno based online RPG

### ISSUE THREAD

**Issue by diguifi** [github/release-radar#31]
### Open Source Project name

Tiny Land Online

### What is your project?

Tiny Land online is a minimalistic online RPG created using Deno's WebSockets and HTML5 canvas. You can do quests, get strong gear, level up, all while saving this tiny world from evil creatures and grind yourself to the top 3!

### Version

1.0

### Date

January 26, 2021

### Description of changes

- 50 new areas (100 unique areas in total!!!)
- 16 new monsters (27 in total)
- 5 new quests (7 in total)
- 8 new items (40 in total)
- 22 new NPCs (33 in total)

### GitHub Repo

https://github.com/tiny-devs/tiny-dungeon-online

### Website

https://diguifi.itch.io/tiny-land

### Link to changelog

https://github.com/tiny-devs/tiny-dungeon-online/releases/tag/1.0.0

### Social media

https://diguifi.itch.io/tiny-land

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the January 2021 Release Radar, as that had already shipped. Please definitely submit again for v2.0 and we'd love to consider your project 😄
