### ISSUE TITLE
[Release Radar Request] raylib 4.0

### ISSUE THREAD

**Issue by raysan5** [github/release-radar#32]
### Open Source Project name

raylib

### What is your project?

raylib is a simple and easy-to-use library to enjoy videogames programming.

### Version

4.0

### Date

November 4, 2021

### Description of changes

Complete API review for naming consistency, events automation system, custom game loop controls, major version release of auxiliar libraries (rlgl, raygui and raymath), raylib-parser tool.

### GitHub Repo

https://github.com/raysan5/raylib

### Website

https://www.raylib.com/

### Link to changelog

https://github.com/raysan5/raylib/releases/tag/4.0.0

### Social media

https://twitter.com/raysan5/status/1456359846920458240

### Anything else to add?

Sorry for the late release news, I didn't know about the release-radar issue system.

**Comment by mishmanners** [comment]
This is awesome! Sorry we couldn't include it in the November Release Radar as that had already shipped. Please definitely submit again for v5.0 and we'd love to include it 😄
