### ISSUE TITLE
[Release Radar Request] NativeBase v3.2.2

### ISSUE THREAD

**Issue by surajahmed** [github/release-radar#33]
### Open Source Project name

NativeBase

### What is your project?

NativeBase is an accessible, utility-first component library that helps you build consistent UI across Android, iOS, and Web.

### Version

3.2.2

### Date

November 11, 2021

### Description of changes

Fix FormControlErrorMessage rendering
Fix shadow/opacity not working with Input
Fix dependency issues when installing with npm 7+
Fix Text variant typing
Fix textAlign property
Fix nested text styling
Fix TextArea alignment on Android
Fix SSRProvider warning
Avatar group flex-direction error

### GitHub Repo

https://github.com/GeekyAnts/NativeBase

### Website

https://nativebase.io

### Link to changelog

https://github.com/GeekyAnts/NativeBase/releases/tag/v3.2.2

### Social media

https://twitter.com/nativebase

**Comment by mishmanners** [comment]
Sorry we couldn't include this in the November Release Radar as that had already shipped. Please definitely submit again for v4.0 and we'd love to consider your project 😄
