### ISSUE TITLE
[Release Radar Request] Mettle v1.0.0 by Johnson & Johnson

### ISSUE THREAD

**Issue by gforti** [github/release-radar#34]
### Open Source Project name

Mettle Components

### What is your project?

Mettle components is a suite of custom elements to be used on a front-end JavaScript application.  These are built under the Web Components spec. These tags can be dropped into any front end application like html. You can use this package in addition to your own or with other custom element.

### Version

1.0.0

### Date

November 09, 2021

### Description of changes

This initial release of Mettle-Components will feature nine(9) custom elements that can be used in any modern browser.

### GitHub Repo

https://github.com/johnsonandjohnson/mettle-components

### Website

https://johnsonandjohnson.github.io/mettle-components/?path=/docs/welcome-introduction--page

### Link to changelog

https://github.com/johnsonandjohnson/mettle-components/packages/1088563?version=1.0.0

### Social media

https://medium.com/johnson-johnson-open-source/meddle-into-mettle-web-components-e2d1559dd7eb

### Anything else to add?

<img width="126" alt="mettle-logo" src="https://user-images.githubusercontent.com/4631279/146565553-3aa87c7e-a126-4fae-a19f-97f43b672fcd.png">
Johnson & Johnson IT is proud to release it’s first web based front-end package called Mettle.

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the December 2021 Release Radar and we couldn't include them all. Please submit your project again for consideration when you have another major version release and we'd love to include it.
