### ISSUE TITLE
[RR Request]: type-flag v2

### ISSUE THREAD

**Issue by privatenumber** [github/release-radar#35]
### Open Source Project name

type-flag

### What is your project?

Strongly typed argv parser for Node.js

This is a great choice for TypeScript users that want to parse `process.argv` with confidence.

### Version

2.0

### Date

December 17, 2021

### Description of changes

Latest changes adds:
- support for array types
- default values
- Automatically parse `process.argv.slice(2)`
- Export types

### GitHub Repo

https://github.com/privatenumber/type-flag

### Website

https://github.com/privatenumber/type-flag

### Link to changelog

https://github.com/privatenumber/type-flag/releases/tag/v2.0.0

### Social media

https://twitter.com/privatenumbr/status/1471943245794000898

### Anything else to add?

You're the best!

Wil be posting a screenshot below.

**Comment by privatenumber** [comment]
<img width="696" alt="Screen Shot 2021-12-17 at 3 22 51 PM" src="https://user-images.githubusercontent.com/1075694/146610083-69817462-02e2-4575-ba50-c299d3899adf.png">

**Comment by mishmanners** [comment]
Congrats on being featured in the December Release Radar 🥳 
- [Read the blog here](https://github.blog/2022-01-21-release-radar-dec-2021/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1484671401659359235)
- [Feel free to retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1485499076775137280)

Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github/videos) for a December Release Radar promo video 😄
