### ISSUE TITLE
[RR Request]: Soft Maple Editor v1.0.0

### ISSUE THREAD

**Issue by zhyd007** [github/release-radar#36]
### Open Source Project name

SoftMaple Editor

### What is your project?

A Paper Typesetting Editor:

- write the paper like Microsoft Word or Google Docs and generate LaTeX source code for better typesetting.

### Version

1.0.0

### Date

Dec 20, 2021

### Description of changes

- Using Nextjs to render the Draftjs component.
- Online.
- No backend is needed.

### GitHub Repo

https://github.com/SoftMaple/Editor

### Website

https://softmaple.vercel.app/

### Link to changelog

https://github.com/SoftMaple/Editor/releases/tag/v1.0.0

### Social media

https://twitter.com/Tom61319231/status/1472768975813545985

**Comment by mishmanners** [comment]
Congrats on being featured in the December Release Radar 🥳 
- [Read the blog here](https://github.blog/2022-01-21-release-radar-dec-2021/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1484671401659359235)
- [Feel free to retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1485499076775137280)

Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github/videos) for a December Release Radar promo video 😄
