### ISSUE TITLE
[Release Radar Request] Keep your secrets secret!

### ISSUE THREAD

**Issue by rovandep** [github/release-radar#37]
### Open Source Project name

Trousseau

### What is your project?

The Trousseau project provides a Kubernetes native way to encrypt the secret resources within the standard *etcd* using the Kubernetes KMS provider framework. 
This allows to no have to deploy application with an extra set of sidecars, have the Dev team learns about how to manage/interact different KMS solutions, and adapt deployments for CD/GitOps workflows by leverage the standard Kubernetes API for secret management and a fully transparent in-transit encryption using a remote key from e.g. Vault.

### Version

1.0.0

### Date

December 1st, 2021

### Description of changes

This is our first major and stable release hitting the ground this December 1st with full support of Hashicorp Vault Community and Enterprise edition. More KMS to come!

### GitHub Repo

https://github.com/Trousseau-io/trousseau

### Website

https://trousseau.io/

### Link to changelog

https://github.com/Trousseau-io/trousseau/releases/tag/v1.0.0

### Social media

https://www.linkedin.com/posts/trousseau-io_github-trousseau-iotrousseau-store-and-activity-6878980107009171456-22IY

### Anything else to add?

Indeed You rock! Thank you for providing such a great platform and exposure.

**Comment by mishmanners** [comment]
Congrats on being featured in the December Release Radar 🥳 
- [Read the blog here](https://github.blog/2022-01-21-release-radar-dec-2021/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1484671401659359235)
- [Feel free to retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1485499076775137280)

Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github/videos) for a December Release Radar promo video 😄
