### ISSUE TITLE
[Release Radar Request] Database Lab Engine v3.0.0

### ISSUE THREAD

**Issue by NikolayS** [github/release-radar#38]
### Open Source Project name

Database Lab Engine

### What is your project?

Database Lab Engine (DLE) enables instant thin cloning for Postgres to scale the development process. DLE can run many independent Postgres copies on a single machine, helping you solve development, testing, SQL optimization, and troubleshooting tasks much faster.

### Version

v3.0.0

### Date

December 20, 2021

### Description of changes

DLE v3.0.0 includes more than 100 individual changes. Among major changes:
- UI included to the core, it allows working with a single DLE instance
- Persistent clones: clones now survive DLE (or VM) restart
- For the "logical" data provisioning mode: the ability to switch reset clone's state using a snapshot from a different pool/dataset
- Better logging, easier configuration
- Improvements for the cases with multiple DLEs are running a single machine
- PostgreSQL 14 support

### GitHub Repo

https://github.com/postgres-ai/database-lab-engine

### Website

https://postgres.ai

### Link to changelog

https://github.com/postgres-ai/database-lab-engine/releases/tag/v3.0.0

### Social media

https://twitter.com/Database_Lab

### Anything else to add?

DLE 3.0 announcement on PostgreSQL.org: https://www.postgresql.org/about/news/database-lab-engine-30-ui-persistent-clones-postgresql-14-more-2376/

UI demonstration video: https://user-images.githubusercontent.com/1345402/147144663-64e47a92-7800-419b-82db-b9504875b37f.mov

UI screenshot: <img width="792" alt="big-menu-collapsed" src="https://user-images.githubusercontent.com/1345402/147144700-cccf11ce-a468-4cc4-bb62-a3cd5d3a293e.png">

**Comment by mishmanners** [comment]
Congrats on being featured in the December Release Radar 🥳 
- [Read the blog here](https://github.blog/2022-01-21-release-radar-dec-2021/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1484671401659359235)
- [Feel free to retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1485499076775137280)

Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github/videos) for a December Release Radar promo video 😄
