### ISSUE TITLE
student-recommender-dashboard

### ISSUE THREAD

**Issue by herkura** [github/release-radar#39]
### Open Source Project name

student-recommender-dashboard

### What is your project?

With online classes now becoming more prominent than ever teachers will or have a hard time evaluating and understanding their students thereby focus on those students who more need attention and direction. This project tries to explore ways to automate the process of assessing previous exam performance and predict if a student will drop the course or needs special attention or not.

### Version

1.0

### Date

December 23 2021

### Description of changes

It is a pre-release of the dashboard.

### GitHub Repo

https://github.com/herkura/student-recommender-dashboard

### Website

https://student-recommender-dashboard.herokuapp.com/

### Link to changelog

https://github.com/herkura/student-recommender-dashboard/releases

### Social media

NIL

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the December 2021 Release Radar and we couldn't include them all. Please submit your project again for consideration when you have another major version release.
