### ISSUE TITLE
[Release Radar Request] React v18

### ISSUE THREAD

**Issue by bdougie** [github/release-radar#4]
### Open Source Project name

React v18

### What is your project?

A JavaScript library for building user interfaces

### Version

18

### Date

November 15th

### Description of changes

React 18 has been in alpha since June, not sure if this Beta switch is worth mentioning but I am sure they could use help getting the word out for Beta testers.

### GitHub Repo

https://github.com/facebook/react

### Website

https://reactjs.org/

### Link to changelog

https://github.com/reactwg/react-18/discussions/112

### Social media

https://twitter.com/dan_abramov/status/1464743989123371008?s=20

**Comment by mishmanners** [comment]
This was included in our November Release Radar 🎉 congrats
