### ISSUE TITLE
[RR Request]: Firezone WireGuard VPN Server v0.2.0

### ISSUE THREAD

**Issue by gongjason** [github/release-radar#41]
### Open Source Project name

Firezone

### What is your project?

Firezone is an open-source VPN server and egress firewall for Linux that makes it simple to manage secure remote access to your company’s private networks. Built on modern technologies, including the new blazing fast WireGuard tunneling protocol, Firezone is lightweight and easy to set up while being up to 3-4x faster than alternative solutions like OpenVPN and IPsec. 

### Version

0.2.0

### Date

December 27, 2021

### Description of changes

Our current goal is adding features on top of WireGuard to let you easily manage your team’s remote access. Eventually, we’d like the product to be ready for companies both small and large to manage their entire workforce’s access to private networks and internal services. In this update we did that by:
* **Multiple Users**: Users are now first-class entities in Firezone. Devices now belong to users, and administrators can create users that authenticate to the Firezone web UI with email/password auth.
* **Require Web Authentication for VPN**: Administrators can optionally require VPN users to sign in periodically to the Firezone web UI to keep their VPN session active.
* **Device Defaults**: Device defaults like AllowedIPs, DNS, and VPN endpoint are now configurable. Devices can be configured to override these on a per-device basis as needed.
* **More Ways to Share Device Configs**: New shareable link and download config buttons allow an Administrator to more easily share device configs to VPN users.
* **Connectivity Checks**: New Diagnostics panel shows periodic connectivity checks to the Internet to ensure your Firezone instance is reachable by VPN users.

### GitHub Repo

https://github.com/firezone/firezone

### Website

https://www.firez.one/

### Link to changelog

https://github.com/firezone/firezone/releases/tag/0.2.0

### Social media

https://twitter.com/firezonevpn

### Anything else to add?

thanks for considering us!

**Comment by gongjason** [comment]
Adding some screenshots to the new features in the update:

General usage:
![hero-main](https://user-images.githubusercontent.com/52545545/147493911-4bb0dd2d-7056-4d70-a153-cb79a683b77b.gif)

Multiple Users: Users are now first-class entities in Firezone. Devices now belong to users, and administrators can create users that authenticate to the Firezone web UI with email/password auth.
![image](https://user-images.githubusercontent.com/52545545/147494174-56d03e56-c08e-42ea-bb47-8dd77a62ad57.png)

Require Web Authentication for VPN: Administrators can optionally require VPN users to sign in periodically to the Firezone web UI to keep their VPN session active.
![image](https://user-images.githubusercontent.com/52545545/147494092-6b484a9d-1c90-4a8d-8e01-5bd2be82c43c.png)

Device Defaults: Device defaults like AllowedIPs, DNS, and VPN endpoint are now configurable. Devices can be configured to override these on a per-device basis as needed.
![image](https://user-images.githubusercontent.com/52545545/147494121-a4159178-93cb-4fec-b99c-413aff6bd267.png)

More Ways to Share Device Configs: New shareable link and download config buttons allow an Administrator to more easily share device configs to VPN users.
![image](https://user-images.githubusercontent.com/52545545/147494138-7099f77d-9e0f-4890-8e77-5c4b21c124cc.png)

Connectivity Checks: New Diagnostics panel shows periodic connectivity checks to the Internet to ensure your Firezone instance is reachable by VPN users.
![image](https://user-images.githubusercontent.com/52545545/147494144-e02468b6-301d-46ff-acf9-6278460eae7f.png)

**Comment by mishmanners** [comment]
Thanks for submitting. We loved your project, but we had so many submissions for the December 2021 release radar that we priortised Version X.0 releases. Please submit again when you have the next major version and we'd love to consider your project for feature again 😄
