### ISSUE TITLE
[Release Radar Request] Weffe v1.0.0

### ISSUE THREAD

**Issue by intermezzio** [github/release-radar#42]
### Open Source Project name

Weffe

### What is your project?

Since Zoom, WebEx, and other video calling platforms tend to have fewer features for Linux users, this project adds webcam video effects on Linux using minimal computer resources. Some effects include background blur and overlaying text and images to the webcam feed, which is streamed to a virtual webcam that can be used on any video call.

### Version

1.0.0

### Date

December 27, 2021

### Description of changes

nil

### GitHub Repo

https://github.com/intermezzio/weffe

### Website

nil

### Link to changelog

https://github.com/intermezzio/weffe/releases/tag/v1.0.0

### Social media

nil

### Anything else to add?

All of the video effects are written in shell and directly call ffmpeg, making these effects easier to use than ML-related solutions for webcam effects. I originally created this so that I could use it while taking remote college classes, and have now turned it into a more stable package for anyone interested in using it on their own calls.

**Comment by intermezzio** [comment]
![image](https://user-images.githubusercontent.com/31703249/147516115-6d197aaf-8fb3-4e6f-bad3-42bae872a25c.png)

**Comment by mishmanners** [comment]
Congrats on being featured in the December Release Radar 🥳 
- [Read the blog here](https://github.blog/2022-01-21-release-radar-dec-2021/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1484671401659359235)
- [Feel free to retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1485499076775137280)

Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github/videos) for a December Release Radar promo video 😄
