### ISSUE TITLE
[RR Request]: RxDB 11.0.0

### ISSUE THREAD

**Issue by pubkey** [github/release-radar#43]
### Open Source Project name

RxDB

### What is your project?

RxDB (short for Reactive Database) is a NoSQL-database for JavaScript Applications like Websites, hybrid Apps, Electron-Apps, Progressive Web Apps and NodeJs. Reactive means that you can not only query the current state, but subscribe to all state changes like the result of a query or even a single field of a document. This is great for UI-based realtime applications in way that makes it easy to develop and also has great performance benefits. To replicate data between your clients and server, RxDB provides modules for realtime replication with any CouchDB compliant endpoint and also with custom GraphQL endpoints.

### Version

11.0.0

### Date

January 3, 2022

### Description of changes

https://github.com/pubkey/rxdb/blob/master/orga/releases/11.0.0.md

### GitHub Repo

https://github.com/pubkey/rxdb

### Website

https://rxdb.info/

### Link to changelog

https://github.com/pubkey/rxdb/blob/master/CHANGELOG.md

### Social media

https://twitter.com/rxdbjs/status/1477993564265189378

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄
