### ISSUE TITLE
[RR Request]: GoReleaser

### ISSUE THREAD

**Issue by dirien** [github/release-radar#44]
### Open Source Project name

GoReleaser

### What is your project?

Deliver Go binaries as fast and easily as possible by @caarlos0

### Version

v1.2.0

### Date

21.12.2021

### Description of changes

- keyless signing 
- improve universal binaries on krew/brew/gofish
- improve universal binaries on krew/brew/gofish 
- and much much more 

### GitHub Repo

https://github.com/goreleaser/goreleaser

### Website

https://goreleaser.com/

### Link to changelog

https://github.com/goreleaser/goreleaser/releases/tag/v1.2.0

### Social media

https://twitter.com/GoReleaser

### Anything else to add?

Love this format so much! Thanks for doing this!

**Comment by dirien** [comment]
FYI @caarlos0

**Comment by mishmanners** [comment]
Thanks for submitting. We loved your project, but we had so many submissions for the December 2021 release radar that we priortised Version X.0 releases. Please submit again when you have the next major version and we'd love to include your project 😄
