### ISSUE TITLE
[Release Radar Request] Minimal Theme for Twitter 4.0

### ISSUE THREAD

**Issue by thomaswang** [github/release-radar#45]
### Open Source Project name

Minimal Theme for Twitter

### What is your project?

Minimal Theme for Twitter (aka Minimal Twitter) is a browser extension that adds an opinionated base layer of styles to clean up the Twitter UI. In addition, it provides extra customization on top to allow you to personalize your Twitter experience. 

### Version

4.0

### Date

January 7, 2021

### Description of changes

What's new:
+ All new Popup UI that can also be accessed in Extension Options or Preferences
+ More granular control over feed & navigation
+ Zen Mode!

![popup](https://user-images.githubusercontent.com/41944255/149463159-4ab169bb-f2bf-4ffc-ba62-a167efbbbc97.png)

Extras include selectively hide vanity counts (e.g. likes, retweets, follower count, etc.)

![extras](https://user-images.githubusercontent.com/41944255/149463182-bf96d7e8-c256-4871-9fb2-3ad6c919dfd2.png)

### GitHub Repo

https://github.com/thomaswang/minimal-twitter

### Website

https://wang.sh/minimal-twitter

### Link to changelog

https://github.com/thomaswang/minimal-twitter/releases/tag/v4.0.8

### Social media

https://twitter.com/ThomasWang/status/1482070433465655296

### Anything else to add?

The extension recently became a Firefox Recommended Extension!

> Recommended extensions are editorially curated extensions that meet the highest standards of security, functionality, and user experience. — [Firefox](https://support.mozilla.org/en-US/kb/add-on-badges?utm_content=promoted-addon-badge&utm_medium=referral&utm_source=addons.mozilla.org)

![firefox](https://user-images.githubusercontent.com/41944255/149463348-6455b1ae-2ecd-4e09-bda4-deb639cb1dfc.png)

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄
