### ISSUE TITLE
[RR Request]: AnotherPomodoro 1.0

### ISSUE THREAD

**Issue by Hanziness** [github/release-radar#46]
### Open Source Project name

AnotherPomodoro

### What is your project?

AnotherPomodoro is a modern productivity timer web app with an integrated to-do list, multiple timer displays and lots of customization. It helps you stay productive by setting up timers in a Pomodoro fashion while keeping the screen distraction-free.

### Version

1.0

### Date

January 19, 2022

### Description of changes

Compared to the previous version (0.11), there is a revamped home page and settings panel, a rewritten to-do list, friendly error pages, a setup page with live preview and much more.

### GitHub Repo

https://github.com/Hanziness/AnotherPomodoro

### Website

https://another-pomodoro.app

### Link to changelog

https://github.com/Hanziness/AnotherPomodoro/releases/tag/v1.0.0

### Social media

https://twitter.com/Hanziness/status/1483900997764272138

### Anything else to add?

This is my first very own open-source project to release version 1.0, and it only took 430+ commits on the default branch! I'm very excited about it and I hope someone will find it helpful during their productivity sessions.

**Comment by Hanziness** [comment]
I'm attaching the most used screenshot of the app (showing a run with the default settings) and also the picture used as the Open Graph image and the social preview image of the repo (it features a few more screenshots :) ).

![Main screenshot](https://user-images.githubusercontent.com/18259108/150213072-4e6315f2-0139-4e32-b592-95139e6bc05e.png)

![Open Graph image (16:9)](https://user-images.githubusercontent.com/18259108/150213293-bb436ca9-3b5d-4e8e-8037-00412bc35e83.png)

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄
