### ISSUE TITLE
[RR Request]: Front Matter v6 release

### ISSUE THREAD

**Issue by estruyf** [github/release-radar#47]
### Open Source Project name

Front Matter

### What is your project?

Front Matter is a CMS that runs within Visual Studio Code. It gives you the power and control of a full-blown CMS while also providing you the flexibility and speed of the static site generator of your choice. Jump right into editing and creating content with Front Matter and be able to preview it straight in VS Code.

### Version

6.0.0

### Date

January 25, 2022

### Description of changes

There are various changes, all are listed here: https://beta.frontmatter.codes/updates/v6.0.0 (once live, it will be available on https://frontmatter.codes/updates/v6.0.0)

### ✨ New features

- [#193](https://github.com/estruyf/vscode-front-matter/issues/193): Support added for editing data files.
- [#197](https://github.com/estruyf/vscode-front-matter/issues/197): Support for multi-dimensional content type fields on content creation and editing.
- [#225](https://github.com/estruyf/vscode-front-matter/issues/225): Placeholder support for front matter field values (template and content type).
- [#226](https://github.com/estruyf/vscode-front-matter/issues/226): Ability to specify the local server start command and trigger it from the UI.
- [#227](https://github.com/estruyf/vscode-front-matter/issues/227): Specify the file types to support with the new `frontMatter.content.supportedFileTypes` setting.
- [#228](https://github.com/estruyf/vscode-front-matter/issues/228): Show bulk button actions in panel and dashboard view.
- [#231](https://github.com/estruyf/vscode-front-matter/issues/231): Once you authenticate via GitHub as a supporter, the support links will be hidden from the UI.

### 🎨 Enhancements

- Added default field value for content type fields
- HMR support for panel webview development
- Added reveal media file action
- [#187](https://github.com/estruyf/vscode-front-matter/issues/187): Svelte support with the [#227](https://github.com/estruyf/vscode-front-matter/issues/227) features has been added.
- [#198](https://github.com/estruyf/vscode-front-matter/issues/198): Additional media sort options (alt, caption, and size).
- [#230](https://github.com/estruyf/vscode-front-matter/issues/230): JSON front matter support added.
- [#233](https://github.com/estruyf/vscode-front-matter/issues/233): Partial update when a page is updated.

### 🐞 Fixes

- [#234](https://github.com/estruyf/vscode-front-matter/issues/234): Fix for multi-word keywords
- [#235](https://github.com/estruyf/vscode-front-matter/issues/235): Fix for reselecting the previously removed value from a choice field

### GitHub Repo

https://github.com/estruyf/vscode-front-matter

### Website

https://frontmatter.codes

### Link to changelog

https://frontmatter.codes/updates/v6.0.0

### Social media

https://twitter.com/eliostruyf/status/1486021199461294083

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄

**Comment by estruyf** [comment]
Thank you @mishmanners 🙏
