### ISSUE TITLE
[Release Radar Request] d3-graph-controller

### ISSUE THREAD

**Issue by DerYeger** [github/release-radar#48]
### Open Source Project name

d3-graph-controller

### What is your project?

d3-graph-controller is a TypeScript library for visualizing and simulating directed, interactive graphs.
It wraps D3 to make displaying graphs a configuration task and manages all lifecycle events behind the scenes.

### Version

2.0

### Date

January 8, 2022

### Description of changes

The configuration API has been refined based on experience gathered using d3-graph-controller on actual projects.
In addition, new configuration options were added to put even more control in a developer's hands.

### GitHub Repo

https://github.com/DerYeger/d3-graph-controller

### Website

https://graph-controller.yeger.eu/

### Link to changelog

https://github.com/DerYeger/d3-graph-controller/blob/master/CHANGELOG.md#200-2022-01-08

### Social media

https://twitter.com/DerYeger/status/1484814405699309570

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄

**Comment by DerYeger** [comment]
Thank you very much!
