### ISSUE TITLE
[Release Radar Request] nut.js v2.0.0

### ISSUE THREAD

**Issue by s1hofmann** [github/release-radar#49]
### Open Source Project name

nut.js

### What is your project?

nut.js is a desktop automation framework for Node.js. 

It works across macOS, Windows and Linux and provides a plugin system to easily tweak it to custom needs even on the lowest level.

Besides clipboard access and mouse/keyboard control it comes with a ready to use image matching plugin to navigate your screen using template images. All wrapped up in a nice API

### Version

2.0.0

### Date

January 1st, 2022

### Description of changes

This release introduced a powerful plugin system that makes the framework even more flexible and gives users the ability to customize it to their needs.

Starting with release 2.0.0, nut.js also natively supports Apple Silicon chips.

### GitHub Repo

https://github.com/nut-tree/nut.js

### Website

https://nutjs.dev

### Link to changelog

https://github.com/nut-tree/nut.js/releases/tag/v2.0.0

### Social media

https://twitter.com/s1hofmann/status/1477419475599343616?s=20

### Anything else to add?

Thanks for doing the awesome job that you do, nut.js relies heavily on GitHub!

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄

**Comment by s1hofmann** [comment]
Awesome, thank you very much! 🎉
