### ISSUE TITLE
[Release Radar Request] Material Design Icons 6.5.95

### ISSUE THREAD

**Issue by Templarian** [github/release-radar#5]
### Open Source Project name

Material Design Icons

### What is your project?

Material Design Icons contains over 6000 community created icons and has been integrated into many large Open Source projects such as Home Assistant. The set starting in June 2014 provides an easy integration for designers or developers to use the icons in any project from web to print media.

### Version

6.5.95

### Date

November 13, 2021

### Description of changes

100 New Icons created by the community. Bringing the total icon count to 6595.

Preview: https://pictogrammers.github.io/@mdi/font/6.5.95/

### GitHub Repo

https://github.com/Templarian/MaterialDesign/

### Website

https://materialdesignicons.com (it's being rewritten right now, it's also nearly 8 years old)

### Link to changelog

https://dev.materialdesignicons.com/changelog

### Social media

https://twitter.com/MaterialIcons

### Anything else to add?

https://pictogrammers.com/ is the parent Organization of designers and developers that maintain Material Design Icons.

I left out any stats, but this project is about to close the 6000th issue request. Since we don't really do pull requests this is how we measure community involvement. Usage Stats: [JSdelivr CDN's 16th](https://www.jsdelivr.com/package/npm/@mdi/font) most requested package. The NPM org `@mdi` accounts for 300,000 Weekly Downloads.

**Comment by Templarian** [comment]
Thanks @mishmanners! ⭐ A few people shared that we were featured in the November Release Radar. 💯

**Comment by mishmanners** [comment]
This was included in our November Release Radar 🎉 congrats
