### ISSUE TITLE
[Release Radar Request] Blockly Automation 

### ISSUE THREAD

**Issue by ignatandrei** [github/release-radar#50]
### Open Source Project name

BlocklyAutomation

### What is your project?

Blockly Automation is a project to transform HTTP and Swagger / OPEN API calls into Google Blockly blocks. See a demo at https://ignatandrei.github.io/BlocklyAutomation/ 

### Version

2021.12.30

### Date

 2021.12.30

### Description of changes

The latest change includes generating blocks from swagger and more demos.

### GitHub Repo

http://github.com/ignatandrei/BlocklyAutomation

### Website

https://ignatandrei.github.io/BlocklyAutomation/ 

### Link to changelog

https://ignatandrei.github.io/BlocklyAutomation/ 

### Social media

https://ignatandrei.github.io/BlocklyAutomation/

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the January 2022 Release Radar and we couldn't include them all. Please submit your project again for consideration when you have another major version release.
