### ISSUE TITLE
[RR Request]: HTTPie 3.0

### ISSUE THREAD

**Issue by isidentical** [github/release-radar#51]
### Open Source Project name

HTTPie

### What is your project?

Modern, user-friendly command-line HTTP client for the API era. JSON support, colors, sessions, downloads, plugins & more.

### Version

3.0

### Date

Jan 21, 2022

### Description of changes

🌲️ Nested JSON, 🔌 Plugin manager, ⏱️ Response metadata, 🚀 Speed-ups, 🎨 Improved UI/UX , ✨ Other minor features 
🪲 Lots of Bug fixes. 

### GitHub Repo

https://github.com/httpie/httpie

### Website

https://httpie.io/cli

### Link to changelog

https://httpie.io/blog/httpie-3.0.0

### Social media

https://twitter.com/httpie/status/1485684105085919234

### Anything else to add?

This image covers 3 (Nested JSON, Response Timing, Stylish UI) out of 6 major features we've shipped in this release:

![img](https://user-images.githubusercontent.com/47358913/151134931-92b6035c-226a-4f65-9520-aa5341b0ff3a.png)

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄
