### ISSUE TITLE
[Release Radar Request] Shlink 3.0.0

### ISSUE THREAD

**Issue by acelaya** [github/release-radar#52]
### Open Source Project name

Shlink

### What is your project?

A PHP-based self-hosted URL shortener that can be used to serve shortened URLs under your own domain.

### Version

3.0.0

### Date

January 28, 2022

### Description of changes

This release includes support for emojis everywhere (short URLs, long URLs, titles, etc), allows to fetch all visits received by the instance and adds pagination to tags lists and extended filtering options to short URLs lists.

On the ops side, it brings performance improvements, reduces the docker image size to less than half and starts treating env vars as first class citizens, ensuring they always have precedence over any other kind of configuration.

### GitHub Repo

https://github.com/shlinkio/shlink

### Website

https://shlink.io

### Link to changelog

https://github.com/shlinkio/shlink/releases/tag/v3.0.0

### Social media

https://twitter.com/shlinkio

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the January Release Radar, as we had already chosen the projects. So sorry I missed this one. It's really cool. Can you submit it again when you have version 4.0, so we can include it! 😄

**Comment by acelaya** [comment]
I don't think I get v4.0 released before a couple of years from now.

Would it be an option to include it in next release radar even though it's not technically released in February? I saw in last month you included a project that was submited/released in November last year.
