### ISSUE TITLE
[Release Radar Request] tfsec v1.0

### ISSUE THREAD

**Issue by liamg** [github/release-radar#53]
### Open Source Project name

tfsec

### What is your project?

*tfsec* is a static analysis security scanner for your Terraform code.

Designed to run locally and in your CI pipelines, developer-friendly output and fully documented checks mean detection and remediation can take place as quickly and efficiently as possible

*tfsec* takes a developer-first approach to scanning your Terraform templates; using static analysis and deep integration with the official HCL parser it ensures that security issues can be detected before your infrastructure changes take effect.

### Version

1.0

### Date

January 28, 2022

### Description of changes

nil

### GitHub Repo

https://github.com/aquasecurity/tfsec

### Website

https://aquasecurity.github.io/tfsec/

### Link to changelog

https://github.com/aquasecurity/tfsec/releases/tag/v1.0.0

### Social media

https://twitter.com/tfsec_dev/status/1487074647568961541

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄
