### ISSUE TITLE
[RR Request]: Inkline 3

### ISSUE THREAD

**Issue by alexgrozav** [github/release-radar#54]
### Open Source Project name

Inkline

### What is your project?

Inkline is the intuitive UI Components library that gives you a developer-friendly foundation for building high-quality, accessible, and customizable Vue.js 3 Design Systems.

### Version

3.0

### Date

January 5, 2022

### Description of changes

Inkline 3 is a complete rewrite and redesign, strengthening features that Inkline was already known to be great for. We've improved Developer Experience, Customizability, Components, and Form Validation. With this release, we wanted to create the go-to UI Components Library for implementing any Vue.js 3 Design System.

### GitHub Repo

https://github.com/inkline/inkline

### Website

https://inkline.io

### Link to changelog

https://github.com/inkline/inkline/releases/tag/v3.0.0

### Social media

https://twitter.com/inkline/status/1485639415213010954

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the January 2022 Release Radar and we couldn't include them all. Please submit your project again for consideration when you have version 4.0 released. We'd love to include it 😄
