### ISSUE TITLE
[RR Request]: PyBaMM v21.12

### ISSUE THREAD

**Issue by priyanshuone6** [github/release-radar#55]
### Open Source Project name

PyBaMM

### What is your project?

PyBaMM (Python Battery Mathematical Modelling) solves physics-based electrochemical DAE models by using state-of-the-art automatic differentiation and numerical solvers.

Like the Doyle-Fuller-Newman model can be solved in under 0.1 seconds, while the reduced-order Single Particle Model and Single Particle Model with electrolyte can be solved in just a few milliseconds.

### Version

v21.12

### Date

January 1, 2022

### Description of changes

In PyBaMM 21.12 we have added
-🔋Voltage termination criteria for experiments
-🔋New reaction kinetics
-🔋Cylindrical geometry
plus many other features and optimisations.

### GitHub Repo

https://github.com/pybamm-team/PyBaMM

### Website

https://www.pybamm.org/
https://pybamm.readthedocs.io/en/latest/ (docs)

### Link to changelog

https://github.com/pybamm-team/PyBaMM/releases/tag/v21.12

### Social media

https://twitter.com/pybamm_/status/1477347002409267210

### Anything else to add?

- PyBaMM have now moved to monthly releases to better suit the needs of the community.
Hence smaller releases, but more frequent. The version number format is now YEAR.MONTH

- The introductory paper is now out in the Journal of Open Research Software! This paper explains the motivation and design philosophy behind PyBaMM
Find it here: https://doi.org/10.5334/jors.309

Dropping the images into the issue

**Comment by priyanshuone6** [comment]
![compare_models](https://user-images.githubusercontent.com/64051212/145958130-25d3d628-4647-44d0-8506-f9739cf7956b.png)
![thermal_pouch](https://user-images.githubusercontent.com/64051212/145958362-838f531d-2f2d-4404-87f1-ba8a87dc0171.png)
![drive_cycle](https://user-images.githubusercontent.com/64051212/145960064-96289dfd-fc73-4fd1-b3a4-9003cc8305d5.png)
![experiments](https://user-images.githubusercontent.com/64051212/145960083-90c0ab83-0205-4a23-9dd7-2177356f1919.png)
![jelly roll](https://user-images.githubusercontent.com/64051212/145958241-450da907-db06-41ce-a33e-00e0589eab30.png)

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄
