### ISSUE TITLE
[RR Request]: Mailwind v2

### ISSUE THREAD

**Issue by soheilpro** [github/release-radar#56]
### Open Source Project name

Mailwind

### What is your project?

Mailwind allows Tailwind CSS to be used for designing HTML emails.

### Version

2.0

### Date

February 3, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/soheilpro/mailwind

### Website

https://github.com/soheilpro/mailwind

### Link to changelog

https://github.com/soheilpro/mailwind/releases/tag/v2

### Social media

https://twitter.com/soheilpro/status/1489077770856501254

**Comment by mishmanners** [comment]
This is cool. You should definitely include your changes in the Changelog 😄 the tweet is good, but unless developers are looking at your tweet, they'll have no idea what's changed.

**Comment by soheilpro** [comment]
Thank you :) You're right. I'll do that.

**Comment by mishmanners** [comment]
Congrats on being featured in the February 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-03-17-release-radar-feb-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1505718263400914944)
