### ISSUE TITLE
[RR Request]: ToolJet v1.0

### ISSUE THREAD

**Issue by withshubh** [github/release-radar#57]
### Open Source Project name

ToolJet

### What is your project?

ToolJet is a low-code platform built on ReactJS and NestJS that can be used to build and deploy internal tools and business applications. The drag and drop application builder can be used to compose the user interface of applications and to set up events such as on click. ToolJet can connect to databases, cloud storages, API endpoints, GraphQL endpoints, and products you love such as Airtable, Google Sheets, Slack, etc.

### Version

1.0

### Date

February 8, 2020

### Description of breaking changes

Here are the changes since the launch of beta ( v0.5.3 ) in June 2021:
- Ported ToolJet server from Ruby to Node.js.
- Ability to extend ToolJet using plugins.
- Comandline tool ( https://www.npmjs.com/package/@tooljet/cli ) to bootstrap plugins and add dependencies.
- Started with 7 integrations and now we have 20+ datasource integrations.
- Started with 15 widgets and now there are 35+ UI widgets.
- Ability to run JavaScript snippets.
- Redesigned the application builder and dashboard for better usability.
- Auto-save for changes in editor and version control for apps to support multiple environments.
- Supports keyboard shortcuts for canvas actions like undo, redo, delete, clone, and more.
- Permissions based on user groups.
- Realtime collaboration features to communicate with your team members.
- Support for deploying on more platforms ( Azure AKS, Google Cloud Run, and more ).
- Support for SSO. Google & GitHub SSO on the community edition. Okta, AzureAD, and more on enterprise edition.
- Audit logs for enterprise edition users

### GitHub Repo

https://github.com/ToolJet/ToolJet/releases/tag/v1.0

### Website

https://tooljet.com/

### Link to changelog

https://github.com/ToolJet/ToolJet/releases/tag/v1.0

### Social media

https://twitter.com/ToolJet/status/1490970429841838080

### Anything else to add?

https://blog.tooljet.com/announcing-tooljet-v1/

**Comment by withshubh** [comment]
Hey @mishmanners 
Not sure if this is right time to make corrections but I have mistakenly added the like to release in **GitHub Repo**.

Here's the correct link to repository: 
https://github.com/ToolJet/ToolJet

**Comment by mishmanners** [comment]
Congrats on being featured in the February 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-03-17-release-radar-feb-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1505718263400914944)
