### ISSUE TITLE
[Release Radar Request] GLPI v10

### ISSUE THREAD

**Issue by flegastelois** [github/release-radar#58]
### Open Source Project name

GLPI

### What is your project?

GLPI stands for Gestionnaire Libre de Parc Informatique is a free automatic inventory Asset and IT Software Management package, that provides ITIL Service Desk (Incident, Request, Problem, Change, Project), licenses tracking, software auditing and hundreds of other features.

### Version

10.0

### Date

February 3, 2022

### Description of breaking changes

Almost 20 years after the first version, and after more than a year and a half of development, GLPI comes out with a very important major version! A brand new interface with modern components (Bootstrap + tabler.io + Twig), a redesign of service desk management, a new protocol to manage automatic inventory natively, and hundreds of other features and improvements!

### GitHub Repo

https://github.com/glpi-project/glpi

### Website

https://glpi-project.org

### Link to changelog

https://glpi10.com

### Social media

https://twitter.com/GLPI_PROJECT/status/1489568660721180676

### Anything else to add?

I want to specify that we released:
- Beta v10.0 : December 15, 2021
- Release Candidate v10.0 : February 3, 2022
- Stable v10.0 : planned for the first half of March 2022

and also, I mean, you rock! 💯

**Comment by mishmanners** [comment]
Congrats on being featured in the February 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-03-17-release-radar-feb-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1505718263400914944)
