### ISSUE TITLE
[Release Radar Request] Ionic v6.0.0

### ISSUE THREAD

**Issue by mhartington** [github/release-radar#59]
### Open Source Project name

Ionic

### What is your project?

Ionic is an open source UI toolkit for building cross-platform apps with web technologies. With over 100 different components and support for Angular, React, or Vue, Ionic let's web developers build for native iOS and Android with the skills they already know.

### Version

6.0.0

### Date

December 8, 2021

### Description of breaking changes

Ionic v6.0.0 brings a refreshed UI design to be more aligned with the latest design and UX standards from Apple and Google. Along with the design refresh, new, highly requested components have been added like accordion, breadcrumbs, bottom sheet, and a brand new datetime.

### GitHub Repo

https://github.com/ionic-team/ionic-framework

### Website

http://ionicframework.com/

### Link to changelog

https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#600-titanium-2021-12-08

### Social media

https://twitter.com/Ionicframework/status/1470415766478626821

### Anything else to add?

https://ionicframework.com/blog/announcing-ionic-6

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the December Release Radar, as that had already shipped. Please definitely submit again for version 7.0 and we'd love to consider your project 😄
