### ISSUE TITLE
[Release Radar Request] GoReleaser v1.1.0

### ISSUE THREAD

**Issue by dirien** [github/release-radar#6]
### Open Source Project name

GoReleaser

### What is your project?

Deliver Go binaries as fast and easily as possible by @caarlos0

### Version

v1.1.0

### Date

29.11.2021

### Description of changes

- feat(deps): update nfpm (@caarlos0)
- feat: add changelog sorting (#2670) (@dirien)
- feat: add cosign tool in the goreleaser image (#2542) (@cpanato)

### GitHub Repo

https://github.com/goreleaser/goreleaser

### Website

https://goreleaser.com/

### Link to changelog

https://github.com/goreleaser/goreleaser/releases/tag/v1.1.0

### Social media

https://twitter.com/GoReleaser

### Anything else to add?

You rock!

**Comment by mishmanners** [comment]
Sorry that we couldn't include this in the November Release Radar as the projects had already been chosen. Please submit again for your next major release and we'd love to include you 😄
