### ISSUE TITLE
[RR Request]: rsadsb v0.5.0

### ISSUE THREAD

**Issue by wcampbell0x2a** [github/release-radar#60]
### Open Source Project name

rsadsb

### What is your project?

`rsadsb` is a group of projects that can demodulate and display ADS-B(Automatic Dependent Surveillance–Broadcast) data from airplanes in the sky with the Rust language.

### Version

v0.5.0

### Date

Febuary 12, 2022

### Description of breaking changes

- Now uses mercator projection
- Add mouse and touchscreen controls
- Import airport information
- Fixed mis-decodes
- Added builds for `x86_64-unknown-linux-gnu`, `armv7-unknown-linux-gnueabihf`, and `aarch64-linux-android`.

### GitHub Repo

https://github.com/rsadsb/adsb_deku

### Website

https://rsadsb.github.io

### Link to changelog

https://rsadsb.github.io/v0.5.0.html

### Social media

https://twitter.com/wcampbell42/status/1492607956294250505

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
