### ISSUE TITLE
[Release Radar Request] Appsmith

### ISSUE THREAD

**Issue by vihar** [github/release-radar#61]
### Open Source Project name

Appsmith

### What is your project?

Appsmith is the first open-source low code software that helps developers quickly build custom (often critical yet tedious) internal and CRUD type applications.

### Version

v1.6.10

### Date

February 14, 2022

### Description of breaking changes

The latest changes on Appsmith include the most requested feature from our GitHub community: The GitSync.

GitSync allows you to version-control your appsmith apps by connecting them with a Git hosting provider (GitHub, GitLab, Bitbucket), making it easier to track changes, create rollbacks or collaborate using git branches.

The flow is similar to how you work on Git - Commit the changes to push them to the remote branch. You can create new branches from the app and pull the changes from the repository if your app is out of sync with the branch you are working on.

More details on documentation here: https://docs.appsmith.com/core-concepts/git-sync

### GitHub Repo

https://github.com/appsmithorg/appsmith

### Website

https://www.appsmith.com/

### Link to changelog

https://github.com/appsmithorg/appsmith/releases/tag/v1.6.10

### Social media

https://twitter.com/theappsmith/status/1493869333101289472

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 2.0 and we'd love to consider your project for feature 😄
