### ISSUE TITLE
[Release Radar Request] JSON Visio

### ISSUE THREAD

**Issue by AykutSarac** [github/release-radar#62]
### Open Source Project name

JSON Visio

### What is your project?

JSON Visio is an app to view JSON data into graphs without having to restructure the initial data.

### Version

1.0

### Date

February 17, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/AykutSarac/jsonvisio.com

### Website

https://jsonvisio.com/

### Link to changelog

https://github.com/AykutSarac/jsonvisio.com/releases/tag/v1.0.0

### Social media

https://twitter.com/aykutsarach/status/1494329405086187528

**Comment by mishmanners** [comment]
Congrats on being featured in the February 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-03-17-release-radar-feb-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1505718263400914944)
