### ISSUE TITLE
[Release Radar Request] Pipelinit

### ISSUE THREAD

**Issue by joao10lima** [github/release-radar#63]
### Open Source Project name

Pipelinit

### What is your project?

 Say goodbye to YAML and create a complete GitHub Actions workflow for your project in seconds.

### Version

0.4.0

### Date

January 25, 2022

### Description of breaking changes

Add terraform stack by
Add support for setup.py
Add Ruby SAST stage
Add Docker SAST stage

Support for GitLab CI

### GitHub Repo

https://github.com/pipelinit/pipelinit-cli

### Website

https://pipelinit.com/

### Link to changelog

https://github.com/pipelinit/pipelinit-cli/releases/tag/v0.4.0

### Social media

https://twitter.com/pipelinit

### Anything else to add?

Checkout our playground

Paste the link of your public repository, and we'll do the rest. Then, download the workflow files and add them to your project or create a new pull request directly on the repository!

https://pipelinit.com/playground/

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
