### ISSUE TITLE
[RR Request]: EdgeDB 1.0, now released 2.0

### ISSUE THREAD

**Issue by 1st1** [github/release-radar#67]
### Open Source Project name

EdgeDB

### Short description:

EdgeDB is an open-source graph-relational database designed to address some major ergonomic limitations of SQL and relational schema modeling, without sacrificing type safety or performance.

### Longer description:

EdgeDB is an open-source graph-relational database. It lets you model data the way you think about it: not as tables or rows, but as collections of strongly-typed objects that contain properties and links to other objects. Its query language EdgeQL is designed as a spiritual successor to SQL, with JOIN-less deep fetching, nestable syntax, and a set-theoretic foundation. 

### Version

1.0

### Date

February 10, 2022

### Description of breaking changes

This is our first major release, no breaking changes.

### GitHub Repo

https://github.com/edgedb/edgedb

### Website

https://edgedb.com

### Link to changelog

https://www.edgedb.com/blog/edgedb-1-0

### Social media

https://twitter.com/edgedatabase/status/1492236899817193472

### Anything else to add?

This is our first stable release and a major milestone. We've spent multiple years building up to this moment, with a string of major contributions to various open source projects like the Python programming language. Read our full story here: [Building a production database in 10 years or less](https://www.edgedb.com/blog/building-a-production-database-in-ten-years-or-less).

We believe that EdgeDB is a unique project: it's a fully open source database that pushes the relational model to new limits, defining a new category. Getting featured in GH Release Radar would help us a lot!

cc @andreagriffiths11

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the February Release Radar and we couldn't include them all. We look forward to seeing your submission again in future.

**Comment by mishmanners** [comment]
Congrats on being featured in the MONTHOF Release Radar 🥳

- Read the blog [here](https://github.blog/2022-08-05-release-radar-jul-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1557773344996458497)
- [Feel free to retweet Mish's tweet mentioning you](https://twitter.com/MishManners/status/1564440638556622848)
- Check out our [Release Radar YouTube video](https://youtu.be/pAD2ZYYBHKA) for the July Release Radar promo video 😄
