### ISSUE TITLE
[Release Radar Request] Cross-platform YouTube Module for PowerShell

### ISSUE THREAD

**Issue by pcgeek86** [github/release-radar#68]
### Open Source Project name

YouTube PowerShell Module

### What is your project?

The YouTube PowerShell module is an open source project, hosted on GitHub, that enables PowerShell developers to retrieve data from YouTube v3 Data API. It also provides the ability for developers to perform operations such as "liking" videos, leaving comments, or deleting content.

### Version

0.3.6

### Date

January 29th, 2022

### Description of breaking changes

n/a

### GitHub Repo

https://github.com/pcgeek86/youtube

### Website

https://github.com/pcgeek86/youtube

### Link to changelog

https://github.com/pcgeek86/youtube/blob/main/youtube.psd1

### Social media

https://www.youtube.com/watch?v=SGAu0LTULYw&t=309s

### Anything else to add?

This project is in its infancy, but more exposure would help me to understand how people want to use it, and what features might be missing from it!

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
