### ISSUE TITLE
[Release Radar Request] Buf 1.0

### ISSUE THREAD

**Issue by lucperkins** [github/release-radar#69]
### Open Source Project name

Buf

### What is your project?

The [`buf`](https://buf.build/) CLI is an all-in-one tool for working with [Protocol Buffers](https://developers.google.com/protocol-buffers) APIs. It offers features like the ability to manage Protobuf assets on the [Buf Schema Registry](https://docs.buf.build/bsr), a Protobuf [linter](https://docs.buf.build/lint/usage) that enforces configured linting [rules](https://docs.buf.build/lint/rules), a [breaking change detector](https://docs.buf.build/breaking/usage) that ensures compatibility across the lifecycle of an API, and a code stub [generator](https://docs.buf.build/generate/usage) that invokes your Protobuf plugins based on your supplied [configuration](https://docs.buf.build/configuration/v1/buf-gen-yaml).

### Version

1.0

### Date

February 17, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/bufbuild/buf

### Website

https://buf.build

### Link to changelog

https://github.com/bufbuild/buf/blob/main/CHANGELOG.md

### Social media

https://twitter.com/bufbuild

### Anything else to add?

Blog post: https://buf.build/blog/buf-cli-v1

**Comment by mishmanners** [comment]
Congrats on being featured in the February 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-03-17-release-radar-feb-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1505718263400914944)
