### ISSUE TITLE
[Release Radar Request] PHP 8.1

### ISSUE THREAD

**Issue by pronskiy** [github/release-radar#7]
### Open Source Project name

PHP

### What is your project?

PHP is a popular general-purpose scripting language that is especially suited to web development.

### Version

8.1

### Date

November 25, 2021

### Description of changes

PHP 8.1 is a major update of the PHP language.
It contains many new features, including enums, readonly properties, first-class callable syntax, fibers, intersection types, as well as performance improvements and a bunch of deprecations.

The most notable new features:
- Enumerations
- Readonly properties
- Fibers
- `new` operator in initializers
- Pure intersection types
- `never` return type
- First-class callable syntax
- `final` class constants
- Explicit octal numeral notation

### GitHub Repo

https://github.com/php/php-src

### Website

https://www.php.net

### Link to changelog

https://www.php.net/releases/8.1/en.php

### Social media

https://twitter.com/official_php/status/1463943033234276360

**Comment by mishmanners** [comment]
This was included in our November Release Radar 🎉 congrats
