### ISSUE TITLE
[RR Request]: @virtualstate/promise v1 (v1.0.1)

### ISSUE THREAD

**Issue by fabiancook** [github/release-radar#70]
### Open Source Project name

@virtualstate/promise

### What is your project?

[`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) & [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled), with [`for await...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) support

### Version

v1.0.1

### Date

Feb 27th 2022

### Description of breaking changes

None, initial release. 

### GitHub Repo

https://github.com/virtualstate/promise

### Website

https://fabiancook.dev/2022/02/26/an-async-thing

### Link to changelog

https://github.com/virtualstate/promise/releases/tag/v1.0.1

### Social media

https://twitter.com/FabianCook/status/1497488354275115008

### Anything else to add?

This is the first non alpha release of this module. [`v1`](https://github.com/virtualstate/promise/releases/tag/v1.0.1). The semver version used is [`v1.0.1`](https://github.com/virtualstate/promise/commit/f0e0cdd417cb127194bb2c0a792179f1bcc00ec8) because I had started with [`v1.0.1-alpha.0` ](https://github.com/virtualstate/promise/commit/fd9fa9d766e483e40532f181f97ff8fb27010e97#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R3)

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the February Release Radar, as we had already chosen our projects. Please definitely submit again for version 2.0 and we'd love to consider your project 😄
