### ISSUE TITLE
[RR Request]: GitLens 12

### ISSUE THREAD

**Issue by eamodio** [github/release-radar#71]
### Open Source Project name

GitLens

### What is your project?

GitLens supercharges Git inside VS Code and unlocks untapped knowledge within each repository. It helps you to visualize code authorship at a glance via Git blame annotations and CodeLens, seamlessly navigate and explore Git repositories, gain valuable insights via rich visualizations and powerful comparison commands, and so much more.

GitLens simply helps you better understand code by letting you quickly glimpse into whom, why, and when a line or code block was changed and effortlessly explore the history and evolution of a codebase.

### Version

12.0

### Date

February 28, 2022

### Description of breaking changes

This release introduces support for VS Code for the Web (vscode.dev & github.dev) for GitHub repositories. This allows any GitHub user to press `.` on any repository (and once GitLens is installed) and quickly get rich insights about how and why the code changed and evolved. As well as providing the ability to navigate and explore the Git repository (commits, branches, etc).

Additionally, we added a new guided Getting Started walkthrough experience to help new and existing users discover valuable features. And now users can see autolinked issues and pull requests for GitHub repositories in comparison -- so now when comparing tags, etc. you can quickly see all the referenced issues or pull requests.

There was also polish and enhancements to many workflows and performance and efficiency improvements.

### GitHub Repo

https://github.com/gitkraken/vscode-gitlens

### Website

https://www.gitkraken.com/gitlens

### Link to changelog

https://www.gitkraken.com/blog/gitlens-12 & https://github.com/gitkraken/vscode-gitlens/blob/main/CHANGELOG.md

### Social media

https://twitter.com/eamodio/status/1498459092192485384 & https://twitter.com/gitlens/status/1498340125809463301

### Anything else to add?

The VS Code for Web support is a huge feature to bring all the power and insights of GitLens directly on the web. And we will be continuing to expand the supported feature set as we can (and that the GitHub apis allow 😉 ).

**Comment by mishmanners** [comment]
Congrats on being featured in the February 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-03-17-release-radar-feb-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1505718263400914944)
