### ISSUE TITLE
[RR Request]: @xata/screenshot v1.0.0

### ISSUE THREAD

**Issue by TejasQ** [github/release-radar#72]
### Open Source Project name

@xata.io/screenshot

### What is your project?

A zero-dependency browser-native way to take screenshots powered by the native web MediaDevices API.

### Version

1.0.0

### Date

5 Feb, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/xataio/screenshot

### Website

https://xata.io/

### Link to changelog

https://www.xata.io/blog/introducing-screenshot/

### Social media

https://twitter.com/xatabase/status/1496142071048155146

**Comment by mishmanners** [comment]
Congrats on being featured in the February 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-03-17-release-radar-feb-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1505718263400914944)
