### ISSUE TITLE
[Release Radar Request] Mantine 4.0

### ISSUE THREAD

**Issue by rtivital** [github/release-radar#73]
### Open Source Project name

Mantine

### What is your project?

Mantine is a fully featured React hooks and components library. 

### Version

4.0.0

### Date

March 10th, 2022

### Description of breaking changes

New project with more than 120 premade component – [Mantine UI](https://ui.mantine.dev/)

New packages:
- [@mantine/form](https://mantine.dev/form/use-form/)
- [@mantine/spotlight](https://mantine.dev/others/spotlight/)

### GitHub Repo

https://github.com/mantinedev/mantine

### Website

https://mantine.dev/

### Link to changelog

https://mantine.dev/changelog/4-0-0/

### Social media

https://twitter.com/mantinedev/status/1501859220790075398

**Comment by mishmanners** [comment]
Congrats on being featured in the March 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-04-08-release-radar-mar-2022/)
- [Check out our GitHub LinkedIn post](https://www.linkedin.com/posts/github_congrats-to-babylonjs-mantine-front-matter-activity-6918286375012237312-nnl7)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1524538732418076672)
