### ISSUE TITLE
[Release Radar Request] Axentix v2.0

### ISSUE THREAD

**Issue by Xelzs** [github/release-radar#74]
### Open Source Project name

Axentix

### What is your project?

Axentix is a framework mixing fully customizable components & utility-first classes, leaving the design choice to the developer.

### Version

2.0

### Date

March 2, 2022

### Description of breaking changes

This version is centering the attention on the developer experience.
The main goal is to give fully customizable components & utility-first classes, leaving the design choice to the developer.

To achieve this, more components have been added and every part of the framework has been simplified to make the developer able to understand everything from the first reading.
Every component has now CSS variables for customization, which is described on every documentation component page.

### GitHub Repo

https://github.com/axentix/axentix

### Website

https://useaxentix.com/

### Link to changelog

https://github.com/axentix/axentix/releases/tag/2.0.0

### Social media

https://twitter.com/UseAxentix/status/1498955250417512452

### Anything else to add?

The next step is to end a major version of the VueJS integration, to continue adding more functionalities & components and to continue to simplify the current package depending on the community requests.

**Comment by mishmanners** [comment]
Congrats on being featured in the March 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-04-08-release-radar-mar-2022/)
- [Check out our GitHub LinkedIn post](https://www.linkedin.com/posts/github_congrats-to-babylonjs-mantine-front-matter-activity-6918286375012237312-nnl7)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1524538732418076672)
