### ISSUE TITLE
[RR Request]: Front Matter version 7

### ISSUE THREAD

**Issue by estruyf** [github/release-radar#75]
### Open Source Project name

Front Matter

### What is your project?

Front Matter is a CMS that runs within Visual Studio Code. It gives you the power and control of a full-blown CMS while also providing you the flexibility and speed of the static site generator of your choice. Jump right into editing and creating content with Front Matter and be able to preview it straight in VS Code.

### Version

7.0.0

### Date

March 21, 2022

### Description of breaking changes

Release notes of the v7.0.0 release can be found here: https://frontmatter.codes/updates/v7.0.0

### ✨ New Features

- [#175](https://github.com/estruyf/vscode-front-matter/issues/175): New snippet support + dashboard
- [#281](https://github.com/estruyf/vscode-front-matter/issues/281): New `isPublishDate` and `isModifiedDate` datetime field properties

### 🎨 Enhancements

- Light color theme enhancements to media cards
- Light color theme enhancements to folder cards
- Added collapse and dashboard button to the view title of the FM Panel
- Show content commands only when a supported file type is active
- Added `{{year}}`, `{{month}}`, and `{{day}}` placeholders for fields
- [#272](https://github.com/estruyf/vscode-front-matter/issues/272): New slide over panel for showing details of media files
- [#276](https://github.com/estruyf/vscode-front-matter/issues/276): Add a Front Matter walkthrough for VS Code
- [#270](https://github.com/estruyf/vscode-front-matter/issues/270): Only show media files from public folder if `pageBundle` is not enabled on any of the content types
- [#282](https://github.com/estruyf/vscode-front-matter/issues/282): Insert relative paths for media files located in a page bundle (also sub-folders)
- [#283](https://github.com/estruyf/vscode-front-matter/issues/283): Added published date sorting options for the content dashboard
- [#286](https://github.com/estruyf/vscode-front-matter/issues/286): Refresh button added for the content page
- [#287](https://github.com/estruyf/vscode-front-matter/issues/287): Show folder name on `index.md` files for recently modified files
- [#292](https://github.com/estruyf/vscode-front-matter/issues/292): Lower fuzzy search threshold for the content dashboard

### 🐞 Fixes

- [#279](https://github.com/estruyf/vscode-front-matter/issues/279): Fix for content dashboard updates for all registered types
- [#280](https://github.com/estruyf/vscode-front-matter/issues/280): Fix to not automatically set dates on new files that do not contain front matter
- [#284](https://github.com/estruyf/vscode-front-matter/issues/284): Show the WYSIWYG controls on all supported file types
- [#290](https://github.com/estruyf/vscode-front-matter/issues/290): Fix for onDidChangeTextEditorSelection listener sending metadata updates

### GitHub Repo

https://github.com/estruyf/vscode-front-matter

### Website

https://frontmatter.codes

### Link to changelog

https://frontmatter.codes/updates

### Social media

https://twitter.com/eliostruyf/status/1505971501585117187

**Comment by mishmanners** [comment]
Congrats on being featured in the March 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-04-08-release-radar-mar-2022/)
- [Check out our GitHub LinkedIn post](https://www.linkedin.com/posts/github_congrats-to-babylonjs-mantine-front-matter-activity-6918286375012237312-nnl7)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1524538732418076672)
