### ISSUE TITLE
[Release Radar Request] SchemaCrawler

### ISSUE THREAD

**Issue by sualeh** [github/release-radar#76]
### Open Source Project name

SchemaCrawler

### What is your project?

SchemaCrawler is a free database schema discovery and comprehension tool. SchemaCrawler supports almost any database that has a JDBC driver and allows you to [search for database schema objects](https://www.schemacrawler.com/schemacrawler-grep.html) using regular expressions, and output the schema and data in a readable text format.

### Version

16.16.12

### Date

March 21, 2022

### Description of breaking changes

SchemaCrawler supports [Teiid](https://teiid.io/) with a plugin, opening up schema discovery and diagramming to all kinds of data sources, including LDAP, Salesforce, web services and more. SchemaCrawler also supports the [cdata JDBC drivers](https://www.cdata.com/jdbc/), which open up access to a host of unconventional sources such as Dropbox, Facebook and more. 

### GitHub Repo

https://github.com/schemacrawler/SchemaCrawler

### Website

https://www.schemacrawler.com/

### Link to changelog

https://www.schemacrawler.com/changes-report.html

### Social media

https://twitter.com/schemacrawler

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 17.0 and we'd love to consider your project for feature 😄
