### ISSUE TITLE
[Release Radar Request] JobRunr v5.0.0

### ISSUE THREAD

**Issue by rdehuyss** [github/release-radar#78]
### Open Source Project name

JobRunr

### What is your project?

JobRunr is a distributed Java background job scheduler that allows you to perform fire-and-forget, delayed, scheduled and recurring jobs inside Java applications using only Java 8 lambda's. It comes with a smart retry-policy in case of a failure and a built-in dashboard so you can monitor all your background jobs.

### Version

5.0.0

### Date

March 30, 2022

### Description of changes

JobRunr now supports scheduled jobs with a repeating interval instead of a Cron expression - this means you can now schedule a recurring job as follows `BackgroundJob.scheduleRecurringly("my-recurring-job", Duration.parse("PT5D"), () -> service.doWork());`
There is also support for Spring Native - use the dependency `jobrunr-spring-boot-native` and your app will launch in milliseconds.
This latest release also introduces support for the [Mapped Diagnostics Context](https://www.baeldung.com/mdc-in-log4j-2-logback) of SLF4J. If you have a correlation id available and you log something in your job, this correlation id will still be available. 

### GitHub Repo

https://github.com/jobrunr/jobrunr

### Website

https://www.jobrunr.io

### Link to changelog

https://github.com/jobrunr/jobrunr/releases/tag/v5.0.0

### Social media

https://twitter.com/JobRunr/status/1509268533624115203

### Anything else to add?

Yes, thanks!

**Comment by mishmanners** [comment]
Congrats on being featured in the March 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-04-08-release-radar-mar-2022/)
- [Check out our GitHub LinkedIn post](https://www.linkedin.com/posts/github_congrats-to-babylonjs-mantine-front-matter-activity-6918286375012237312-nnl7)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1524538732418076672)
