### ISSUE TITLE
[Release Radar Request] neo.mjs version 4

### ISSUE THREAD

**Issue by tobiu** [github/release-radar#79]
### Open Source Project name

neo.mjs

### What is your project?

The application worker driven frontend framework

### Version

4.0.0

### Date

March 27, 2022

### Description of breaking changes

version 4 adds a ServiceWorker into the workers setup as well as remote method access to it from inside the app worker realm. we can now dynamically pre-load assets which have not been used yet.

### GitHub Repo

https://github.com/neomjs/neo

### Website

https://neomjs.github.io/pages/

### Link to changelog

https://github.com/neomjs/neo/releases/tag/4.0.0

### Social media

https://www.linkedin.com/posts/tobiasuhlig_release-new-major-version-neomjsneo-activity-6913757636421136384-NHrC?utm_source=linkedin_share&utm_medium=member_desktop_web

**Comment by tobiu** [comment]
Update: the blog post is finished now. friends link:
https://tobiasuhlig.medium.com/predictive-offline-support-for-assets-you-have-not-used-yet-aeeccccd3754?source=friends_link&sk=e946e0f25f508e6a8cec4136400291a3

**Comment by mishmanners** [comment]
Congrats on being featured in the March 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-04-08-release-radar-mar-2022/)
- [Check out our GitHub LinkedIn post](https://www.linkedin.com/posts/github_congrats-to-babylonjs-mantine-front-matter-activity-6918286375012237312-nnl7)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1524538732418076672)
