### ISSUE TITLE
[Release Radar Request] Master to Main

### ISSUE THREAD

**Issue by stephendpmurphy** [github/release-radar#8]
### Open Source Project name

master-to-main

### What is your project?

 Check if a Github user or org has any public repositories with "master" as the main branch and provide helpful material on how to update it to help increase inclusivity in our community.

### Version

1.0

### Date

Nov 15, 2021

### Description of changes

nil

### GitHub Repo

https://github.com/stephendpmurphy/master-to-main

### Website

master-to-main.herokuapp.com/

### Link to changelog

https://github.com/stephendpmurphy/master-to-main/deployments

### Social media

https://twitter.com/stephendpmurphy/status/1459234432104153100

**Comment by mishmanners** [comment]
This was included in our November Release Radar 🎉 congrats
