### ISSUE TITLE
[RR Request]: FeedbackFin v1.0

### ISSUE THREAD

**Issue by harinij** [github/release-radar#80]
### Open Source Project name

FeedbackFin

### What is your project?

Feedback Fin is a tiny widget to collect feedback anywhere on your website. Open-source, lightweight, and fully customizable. Send feedback via webhook, generate one instantly using [Rowy](https://rowy.io) to collaborate on spreadsheet-UI and automate your workflows.

### Version

1.0

### Date

March 31, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/rowyio/feedbackfin

### Website

https://feedbackfin.com

### Link to changelog

https://www.rowy.io/blog/feedback-fin

### Social media

TBD - Will be posted on April 7th

**Comment by mishmanners** [comment]
Congrats on being featured in the March 2022 Release Radar 🥳

- Read the blog [here](https://github.blog/2022-04-08-release-radar-mar-2022/)
- [Check out our GitHub LinkedIn post](https://www.linkedin.com/posts/github_congrats-to-babylonjs-mantine-front-matter-activity-6918286375012237312-nnl7)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1524538732418076672)
