### ISSUE TITLE
[RR Request]: Tiny Land Online 1.1.0

### ISSUE THREAD

**Issue by diguifi** [github/release-radar#81]
### Open Source Project name

Tiny Land

### What is your project?

Tiny Land online is a minimalistic online RPG created using Deno's WebSockets and HTML5 canvas. You can do quests, get strong gear, level up, all while saving this tiny world from evil creatures and grind yourself to the top 3!

### Version

1.1

### Date

April 10, 2022

### Description of breaking changes

Added the major feature "**stores**". Particular NPC's can now sell you items and buy from you.

### GitHub Repo

https://github.com/tiny-devs/tiny-dungeon-online

### Website

https://diguifi.itch.io/tiny-land

### Link to changelog

https://github.com/tiny-devs/tiny-dungeon-online/releases/tag/1.1.0

### Social media

https://diguifi.itch.io/tiny-land

### Anything else to add?

Any feedback is very appreciated! I hope you play and enjoy :)

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project, and I would especially love to feature this game in our release radar. The Release Radar however features major version releases. Please submit again when you have version 2.0 and we'd love to consider your project for feature 😄
