### ISSUE TITLE
[Release Radar Request] JReleaser v1.0.0

### ISSUE THREAD

**Issue by aalmiray** [github/release-radar#82]
### Open Source Project name

JReleaser

### What is your project?

JReleaser is a release automation tool for Java and non-Java projects. Its goal is to simplify creating releases and publishing artifacts to multiple package managers while providing customizable options.

### Version

1.0.0

### Date

April 10th 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/jreleaser/jreleaser

### Website

https://jreleaser.org

### Link to changelog

https://github.com/jreleaser/jreleaser/releases/tag/v1.0.0

### Social media

https://twitter.com/jreleaser/status/1513030818737840129

**Comment by mishmanners** [comment]
Congrats on being featured in the April Release Radar 🥳

- Read the blog [here](https://github.blog/2022-05-20-release-radar-apr-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1527801364633554944)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1534708609917104128)

**Comment by adriens** [comment]
:clap:
