### ISSUE TITLE
[RR Request]: Squealer v1.0.0

### ISSUE THREAD

**Issue by owenrumney** [github/release-radar#83]
### Open Source Project name

Squealer

### What is your project?

Squealer scans a git repository or filesystem for secrets that are being leaked deep within the commit history. Performance is achieved by only scanning the difference between each consecutive commit.

The built-in configuration has a large number of checks for common API keys and you can optionally add your own rules to a config file.

When an issue is identified, you can mitigate it and make it as an exclusion.

### Version

v1.0.0

### Date

April 22, 2022

### Description of breaking changes

No breaking changes were included in this release

### GitHub Repo

https://github.com/owenrumney/squealer

### Website

https://github.com/owenrumney/squealer

### Link to changelog

https://github.com/owenrumney/squealer/releases/tag/v1.0.0

### Social media

https://twitter.com/owenrum/status/1517494330629541893

### Anything else to add?

I love this project (ofcourse I do, its mine)

I genuinely believe it does secret scanning more efficiently than other tools but it only has 118 stars. I'd love people to use it and it help them

**Comment by owenrumney** [comment]
Hey @mishmanners, did I miss out on being in the April release radar?

**Comment by mishmanners** [comment]
Thanks for submitting your project. We had a lot of projects submitted for the April Release Radar and we couldn't include them all. We'd love to see you submit again, however the team did have some concerns over how you're doing secret scanning given GitHub already has that feature. If you can provide more detail for the next one that'd be great.
