### ISSUE TITLE
[Release Radar Request] Plural Launch

### ISSUE THREAD

**Issue by samweaver** [github/release-radar#84]
### Open Source Project name

Plural

### What is your project?

Plural is a unified application deployment platform that makes it easy to run open-source software on Kubernetes. It aims to make applications as portable as possible, without sacrificing the ability for the users to own the applications they desire to use.

The plural platform ingests all deployment artifacts needed to deploy cloud-native applications and tracks their dependencies, allowing for seamless installations and no-touch upgrades post-install. All applications are managed via GitOps, allowing you to reconfigure them at will, or even eject them from Plural entirely. It's your application, we just want to help you use it as easily as possible.

### Version

1.0

### Date

March 2022

### Description of breaking changes

Nil

### GitHub Repo

https://github.com/pluralsh/plural

### Website

https://www.plural.sh

### Link to changelog

https://blog.plural.sh/how-we-built-plural/

### Social media

https://twitter.com/plural_sh/status/1503775618965590022

### Anything else to add?

We make it easy for people to run production grade open source on kubernetes. We're cloud agnostic and totally open source! 

Some feedback we've had:

- Wow this is my favorite product of the decade! -- Head of Engineering at Justifi
- I've had 2 Aha moments in the last year: the first time i saw Airbyte and then when I saw Plural -- Head of data ops at 6 river systems

Thanks in advance for considering us in your release radar 🙏

**Comment by samweaver** [comment]
Feel free to email me with any questions: sam[at]plural.sh :-)

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the March 2022 Release Radar, as that had already shipped. Please definitely submit again for next major version and we'd love to consider your project 😄Also make sure you have a software release on GitHub to ensure we can feature you.
