### ISSUE TITLE
[Release Radar Request] Systeroid v0.1.1

### ISSUE THREAD

**Issue by orhun** [github/release-radar#85]
### Open Source Project name

systeroid

### What is your project?

[**systeroid**](https://github.com/orhun/systeroid) is "[sysctl(8)](https://man7.org/linux/man-pages/man8/sysctl.8.html) on steroids". Similar to sysctl, it is implemented using [procfs](https://en.wikipedia.org/wiki/Procfs) and the primary goal is to manage the kernel parameters. It has a bunch of features to ease the process of reading and modifying the values and even retrieving information about them from the Linux kernel documentation. It also has a text-based user interface to visualize the state of the kernel parameters and interactively perform these management operations.

![demo](https://raw.githubusercontent.com/orhun/systeroid/main/assets/systeroid-demo.gif)

### Version

0.1.1

### Date

April 19, 2022

### Description of breaking changes

nil

### GitHub Repo

https://github.com/orhun/systeroid

### Website

https://systeroid.cli.rs

### Link to changelog

https://github.com/orhun/systeroid/blob/main/CHANGELOG.md

### Social media

https://twitter.com/orhunp_/status/1515254550487257088

### Anything else to add?

Blog post: https://blog.orhun.dev/rewriting-sysctl-in-rust/

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
