### ISSUE TITLE
[RR Request]: financeager v1.0

### ISSUE THREAD

**Issue by pylipp** [github/release-radar#86]
### Open Source Project name

financeager

### What is your project?

`financeager` is an application that helps you administering your daily expenses and earnings using single-entry book-keeping. Interact via the command line interface fina.

### Version

1.0.0

### Date

Jan 28, 2022

### Description of breaking changes

- removed conversion command
- update semantics for filtering a list of entries

### GitHub Repo

https://github.com/pylipp/financeager

### Website

https://github.com/pylipp/financeager

### Link to changelog

https://github.com/pylipp/financeager/releases/tag/v1.0.0

### Social media

https://www.reddit.com/r/Python/comments/sey9j6/released_v100_of_financeager_a_singleentry/

### Anything else to add?

Currently on v1.0.3 including some bug fixes of v1.0.0

**Comment by mishmanners** [comment]
Thanks for submitting. Sorry we couldn't include your project in the January 2022 Release Radar, as that had already shipped. Please definitely submit again for version 2.0 and we'd love to consider your project 😄
