### ISSUE TITLE
[Release Radar Request] fx 23.0.0

### ISSUE THREAD

**Issue by antonmedv** [github/release-radar#88]
### Open Source Project name

https://github.com/antonmedv/fx

### What is your project?

Terminal JSON viewer. Fx allows browsing JSONs in the terminal. Fx allows working with JSON using JavaScript, Python, or Ruby.

Features:

- Mouse support
- Streaming support
- Preserves key order
- Preserves big numbers

### Version

23.0

### Date

May 3, 2022

### Description of breaking changes

Fx was rewritten in Go! (nodejs previously). 

Here is why:

In nodejs, I used my fork of blessed TUI library. Why fork? Because it was abandoned and had a few nasty bugs.  But still too many bugs I was not able to fix. Duch as surviving window resize and scrolling long texts.

In the new version of fx, TUI is implemented in go, but reducers are still on JavaScript (and now also on Ruby or Python). I still believe that for working with JSON, JavaScript is a perfect choice.  So, expressions line `fx 'map(x => x.startsWith("rt_"))'` will be executed by builtin JS vm.

In the new version, I spend a lot of time improving the terminal viewer in all places possible. For example, line wrapping works the same as in vscode. Preview in collapsed items. And the most important - themes :-D

### GitHub Repo

https://github.com/antonmedv/fx

### Website

https://github.com/antonmedv/fx

### Link to changelog

https://github.com/antonmedv/fx/releases/tag/23.0.0

### Social media

https://twitter.com/antonmedv/status/1521767077484412929

**Comment by mishmanners** [comment]
Congrats on being featured in the May Release Radar 🥳

- Read the blog [here](https://github.blog/2022-06-16-release-radar-may-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1537570753910038528)
