### ISSUE TITLE
[RR Request]: Enioka Scan 2.0.0

### ISSUE THREAD

**Issue by DaSpood** [github/release-radar#89]
### Open Source Project name

Enioka Scan

### What is your project?

Enioka Scan is an open source Android library that makes the integration of barcode scanners in your Android applications easy while avoiding vendor lock-in.

The library provides a service that automatically scans for scanners compatible with one of the many included drivers, which wrap or adapt the often proprietary or poorly documented vendor SDK, providing a simple API to access the core features of all supported devices. This allows you to build and maintain a single application without worrying about changing scanner vendor down the line.

### Version

2.0.0

### Date

May 9, 2022

### Description of breaking changes

The exposed APIs were reworked in-depth, making it easier to communicate with the scanner service and individual scanners, with better handling of scanner search options. The scanner service API now only serves as a holder managing scanner lifecycles, meaning many methods were removed and others were introduced. The scanner API was redesigned to make it clearer what features are compatible with a device. Finally, interfaces were streamlined and those with limited use were removed or combined with each other. More details in the release changelog.

### GitHub Repo

https://github.com/enioka/enioka_scan

### Website

https://github.com/enioka/enioka_scan

### Link to changelog

https://github.com/enioka/enioka_scan/releases/tag/2.0.0

### Social media

N/A

**Comment by mishmanners** [comment]
Congrats on being featured in the May Release Radar 🥳

- Read the blog [here](https://github.blog/2022-06-16-release-radar-may-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1537570753910038528)
