### ISSUE TITLE
[Release Radar Request] Big Book of R

### ISSUE THREAD

**Issue by oscarbaruffa** [github/release-radar#9]
### Open Source Project name

Big Book of R

### What is your project?

A collection of almost 300 R programming books which are mostly free and open-source themselves. 

### Version

1.0

### Date

August 26 2020

### Description of changes

The first collection of it's kind, and it blows peoples minds. 

### GitHub Repo

https://github.com/oscarbaruffa/BigBookofR

### Website

https://www.bigbookofr.com/

### Link to changelog

https://oscarbaruffa.com/category/r-programming/bigbookofr/

### Social media

https://twitter.com/OscarBaruffa

### Anything else to add?

I understand this is not the typical open-source project you might normally consider, plus please do consider it! The collection is a bit meta in that its open source and has multiple contributors, and what it collects are books made freely available by the extremely generous and awesome R programming community.

When people find this resource, they really love it and I often get messages of thanks for creating and maintaining it.

**Comment by mishmanners** [comment]
Thanks for submitting. As per the Release Radar, we feature open source projects that shipped major versions the previous month. I do however love this resource and we'll see what we can do to amply it 😄

**Comment by oscarbaruffa** [comment]
Thanks so much!

Regards,

*Oscar *

**Comment by oscarbaruffa** [comment]
Hi,

Maybe this counts a bit better now, but technically this is a v2.0 that
I've just released for Big Book of R :)

https://github.com/oscarbaruffa/BigBookofR/releases/tag/2.0

Regards,

*Oscar *

**Comment by mishmanners** [comment]
Awesome. I can look to include this in the January 2022 Release Radar.

**Comment by oscarbaruffa** [comment]
Cool, thanks for considering it again 👍

**Comment by mishmanners** [comment]
Congrats on being featured in the January Release Radar 🥳

- Read the blog [here](https://github.blog/2022-02-04-release-radar-jan-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1489739302410072066)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1490855085286785024)
- Keep an eye on our [YouTube Channel](https://www.youtube.com/c/github) for a January Release Radar promo video 😄
