### ISSUE TITLE
[RR Request]: Ghost v5

### ISSUE THREAD

**Issue by ErisDS** [github/release-radar#90]
### Open Source Project name

Ghost

### What is your project?

Ghost is a platform for creators & independent publishers written in Node.js. It is essentially blogging on steroids with support for memberships, subscriptions and newsletters built on top of Stripe and Mailgun alongside all the publishing tools you'd expect from a modern CMS. 

### Version

5.0

### Date

May 23, 2022

### Description of breaking changes

- Added custom premium tiers, multiple newsletters, special offers, detailed audience segmenting, and expanded analytics
- Improved API & theme layer, with several breaking changes that make things easier to use.
- Production stack is now Ubuntu 20, Node 16 & MySQL8.

### GitHub Repo

https://github.com/TryGhost/Ghost

### Website

https://ghost.org

### Link to changelog

https://ghost.org/changelog/5/

### Social media

https://twitter.com/Ghost/status/1528711705915695106

### Anything else to add?

Love open source? We’re hiring Node.js Engineers to work on Ghost full-time: https://careers.ghost.org/

**Comment by mishmanners** [comment]
Congrats on being featured in the May Release Radar 🥳

- Read the blog [here](https://github.blog/2022-06-16-release-radar-may-2022/)
- [Check out our GitHub Tweet](https://twitter.com/github/status/1537570753910038528)
