### ISSUE TITLE
[RR Request]: Plural Launch

### ISSUE THREAD

**Issue by samweaver** [github/release-radar#91]
### Open Source Project name

Plural

### What is your project?

Plural empowers DevOps teams to build and maintain cloud-native and production-ready open source infrastructure on Kubernetes. Made for your cloud, for projects big and small. Plural is the platform that takes the complexity out of building great infrastructure.

### Version

0.2.0

### Date

30 May 2022

### Description of breaking changes

- Support for AWS, Azure, GCP
- Fully integrated cloud shell experience
- Batteries included: Baked-in observability, logging, auditing, and user auth.

### GitHub Repo

https://github.com/pluralsh/plural

### Website

https://www.plural.sh

### Link to changelog

https://github.com/pluralsh/plural/commits/v0.2.0

### Social media

nil

### Anything else to add?

Watch: [How to deploy Airbyte on Kubernetes in under 10 minutes](https://www.youtube.com/watch?v=suvTJyJ6PzI)

Architecture:
![image](https://user-images.githubusercontent.com/91291764/171132316-c6ae8f3c-2f3e-4345-a314-811b18834a12.png)

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
