### ISSUE TITLE
[Release Radar Request] <title>

### ISSUE THREAD

**Issue by raiyanyahya** [github/release-radar#92]
### Open Source Project name

Freshenv

### What is your project?

freshenv is a command line application to provision and manage local developer environments. Build and develop your projects in completely isolated environments. Save, switch and restart your environments. Choose from a wide variety of flavours to get the developer tools you need.

### Version

1.2.4

### Date

May 24th 2021

### Description of breaking changes

Enabled custom flavours by adding build command. Also added the --logs flag to voew logs during build for custom flavours.

### GitHub Repo

http://github.com/raiyanyahya/freshenv

### Website

https://freshenv.io

### Link to changelog

https://github.com/raiyanyahya/freshenv/releases/tag/v1.2.4

### Social media

https://twitter.com/raiyan_yahya/status/1529511938497159170?t=U3_xExaieC8RcK9GOiei9g&s=19

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. The May 2021 Release Radar had also already shipped. Please definitely submit again for version 2.0 and we'd love to consider your project 😄
