### ISSUE TITLE
[Release Radar Request] CodeStream 13.0

### ISSUE THREAD

**Issue by CalvinAllen** [github/release-radar#94]
### Open Source Project name

CodeStream

### What is your project?

CodeStream helps dev teams discuss, review, and understand code. Discussing code is now as simple as commenting on a Google Doc — select the code and type your question.

### Version

13.0

### Date

June 2, 2022

### Description of breaking changes

CodeStream’s integration with GitHub pull requests and GitLab merge requests is one of our most popular features, and we’re excited to take that integration to the next level with CodeStream 13.0. 

### GitHub Repo

https://github.com/TeamCodeStream/codestream

### Website

https://www.codestream.com

### Link to changelog

https://www.codestream.com/blog/codestream-13-0-easier-code-reviews-with-all-new-pull-request-integration

### Social media

https://twitter.com/teamcodestream/status/1533893074262409218

**Comment by mishmanners** [comment]
Congrats on being featured in the June Release Radar 🥳

- Read the blog [here](https://github.blog/2022-07-27-release-radar-jun-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1555011732053012480)
- Check out our [YouTube video](https://youtu.be/bnXGngNKbbw) for the June Release Radar promo 😄
