### ISSUE TITLE
[Release Radar Request] pharmaverse/admiral 0.7.0

### ISSUE THREAD

**Issue by bms63** [github/release-radar#95]
### Open Source Project name

pharmaverse/admiral 0.7.0

### What is your project?

To provide an open source, modularized toolbox that enables the pharmaceutical programming community to develop ADaM datasets in R.

### Version

0.7.0

### Date

May 31, 2022

### Description of breaking changes

Updates to date/time imputation functions.  New functions added: for merging variables, to create queries datasets, to derive first or last dates from multiple source datasets.  Deprecated functions details: Many functions that did similar things were deprecated and merged into one function. Eg: derive_var_trtsdtm and derive_var_trtedtm combine into one function derive_vars_merged_dtm.

### GitHub Repo

https://github.com/pharmaverse/admiral

### Website

https://pharmaverse.github.io/admiral/index.html

### Link to changelog

https://pharmaverse.github.io/admiral/news/index.html

### Social media

https://www.linkedin.com/posts/ben-straub_adam-in-r-asset-library-activity-6938229951577948160-yFBv?utm_source=linkedin_share&utm_medium=member_desktop_web

### Anything else to add?

We use X.Y.Z version.

admiral is part of a family of R packages, https://[pharmaverse.org](https://pharmaverse.org/)/, that seeks to provide tools for doing Clinical Reporting of drug trials using the open source language R.

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
