### ISSUE TITLE
[Release Radar Request] Fastify v4!

### ISSUE THREAD

**Issue by mcollina** [github/release-radar#96]
### Open Source Project name

fastify

### What is your project?

Fastify is a web framework highly focused on providing the best developer experience with the least overhead and a powerful plugin architecture, inspired by Hapi and Express.

### Version

v4.0.0

### Date

June 8th, 2022

### Description of breaking changes

Read up the release notes at https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e.

The major changes are:
1. type safe query/body/headers
2. new pino transports (https://getpino.io/#/docs/transports)
3. synchronous route registration
4. faster and more complete router
5. avoid the "resolved with undefined" problem once and for all
6. new error handling composition
7. remove of variadic `.listen()` support

### GitHub Repo

https://github.com/fastify/fastify

### Website

https://www.fastify.io/

### Link to changelog

https://github.com/fastify/fastify/releases/tag/v4.0.0

### Social media

https://twitter.com/matteocollina/status/1534592431315877889?s=20&t=Cxd-gNJ1pu676vdgDhiE5g

**Comment by mishmanners** [comment]
Congrats on being featured in the June Release Radar 🥳

- Read the blog [here](https://github.blog/2022-07-27-release-radar-jun-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1555011732053012480)
- Check out our [YouTube video](https://youtu.be/bnXGngNKbbw) for the June Release Radar promo 😄

**Comment by mcollina** [comment]
Thanks!!
