### ISSUE TITLE
[RR Request]: Pino v8

### ISSUE THREAD

**Issue by mcollina** [github/release-radar#97]
### Open Source Project name

pino

### What is your project?

[Very low overhead](https://getpino.io/#/?id=low-overhead) Node.js logger.

### Version

v8.0.0

### Date

June 1st, 2022

### Description of breaking changes

- asynchronous logging by default
- support for Error.cause
- drop of all previous deprecations
- drop support for Node v12

### GitHub Repo

https://github.com/pinojs/pino

### Website

https://getpino.io

### Link to changelog

https://github.com/pinojs/pino/releases/tag/v8.0.0

### Social media

https://twitter.com/matteocollina/status/1531960265796902913

**Comment by mishmanners** [comment]
Congrats on being featured in the June Release Radar 🥳

- Read the blog [here](https://github.blog/2022-07-27-release-radar-jun-2022/)
- Feel free to [retweet Mish's tweet featuring you](https://twitter.com/MishManners/status/1555011732053012480)
- Check out our [YouTube video](https://youtu.be/bnXGngNKbbw) for the June Release Radar promo 😄

**Comment by mcollina** [comment]
Thanks!
