### ISSUE TITLE
Release Radar Request

### ISSUE THREAD

**Issue by eredotpkfr** [github/release-radar#98]
### Open Source Project name

fipv

### What is your project?

Fast IP validator with C language as a python module.

### Version

0.1.2

### Date

07 Oct 2021

### Description of breaking changes

None

### GitHub Repo

https://github.com/eredotpkfr/fipv

### Website

https://www.erdoganyoksul.com/projects/2021/11/05/fipv.html

### Link to changelog

https://github.com/eredotpkfr/fipv/releases/tag/v0.1.2

### Social media

https://twitter.com/eredot_pkfr/status/1446133755744165888?t=sDH64ZZtlxnYQuqC7lS9Gg&s=19

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄 we also already released the October Release Radar.
