### ISSUE TITLE
[Release Radar Request] Dendron v100 Release

### ISSUE THREAD

**Issue by kevinslin** [github/release-radar#99]
### Open Source Project name

Dendron

### What is your project?

Dendron is an open source note taking tool for developers to make managing knowledge fast, efficient, and delightful by combining the simplicity of markdown with the power of VSCode. Our goal is to be an IDE for knowledge. 

### Version

0.100

### Date

Jun 21, 2022

### Description of breaking changes

This release marks a culmination of things we've worked on to make Dendron better, faster and stronger over the last 2 years.  Highlights include a dedicated sidebar for Dendron related views,  100x speed improvements in initialization and common operations and programmatic notes using traits. A full list of updates can be found in our [blog post](https://blog.dendron.so/notes/8jp5brp2m2arrps7a5w9fk9)

### GitHub Repo

https://github.com/dendronhq/dendron

### Website

https://dendron.so/

### Link to changelog

https://wiki.dendron.so/notes/9bc92432-a24c-492b-b831-4d5378c1692b

### Social media

https://twitter.com/dendronhq/status/1539254314186600448

### Anything else to add?

We did a live stream with the vscode team last December which was really popular and showcases why developers use Dendron for their notes: https://youtu.be/dW6m4_O0qvQ?t=1102

**Comment by mishmanners** [comment]
Thanks for submitting, we loved your project. The Release Radar features major version releases. Please submit again when you have version 1.0 and we'd love to consider your project for feature 😄
